// Code generated by BobGen psql v0.38.1-0.20250722094724-08202428a120. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Animal is an object representing the database table.
type Animal struct {
	ID              int64               `db:"id,pk,generated" `
	UserID          null.Val[uuid.UUID] `db:"user_id" `
	OrganizationID  null.Val[int64]     `db:"organization_id" `
	Name            string              `db:"name" `
	TypeID          int64               `db:"type_id" `
	BreedID         int64               `db:"breed_id" `
	SpeciesID       int64               `db:"species_id" `
	Gender          null.Val[Gender]    `db:"gender" `
	Hermaphrodite   bool                `db:"hermaphrodite" `
	Age             string              `db:"age" `
	CoatLength      null.Val[string]    `db:"coat_length" `
	Size            string              `db:"size" `
	ImageURL        string              `db:"image_url" `
	Description     null.Val[string]    `db:"description" `
	Adopted         bool                `db:"adopted" `
	Status          null.Val[string]    `db:"status" `
	StatusChangedAt null.Val[time.Time] `db:"status_changed_at" `
	Distance        null.Val[string]    `db:"distance" `
	AdoptedAt       null.Val[time.Time] `db:"adopted_at" `
	CreatedAt       time.Time           `db:"created_at" `
	UpdatedAt       time.Time           `db:"updated_at" `

	R animalR `db:"-" `
}

// AnimalSlice is an alias for a slice of pointers to Animal.
// This should almost always be used instead of []*Animal.
type AnimalSlice []*Animal

// Animals contains methods to work with the animal table
var Animals = psql.NewTablex[*Animal, AnimalSlice, *AnimalSetter]("", "animal")

// AnimalsQuery is a query on the animal table
type AnimalsQuery = *psql.ViewQuery[*Animal, AnimalSlice]

// animalR is where relationships are stored.
type animalR struct {
	Adoptions       AdoptionSlice       // adoption.fk_adoption_animal_id_animal
	Organization    *Organization       // animal.fk_animal_organization_id_user
	User            *User               // animal.fk_animal_user_id_user
	AnimalBreeds    AnimalBreedSlice    // animal_breed.fk_animal_breed_animal_id_animal
	AnimalPhotos    AnimalPhotoSlice    // animal_photo.fk_animal_photo_animal_id_animal
	AnimalVideos    AnimalVideoSlice    // animal_video.fk_animal_video_animal_id_animal
	Colors          ColorSlice          // color.fk_color_animal_id_animal
	Contacts        ContactSlice        // contact.fk_contact_animal_id_animal
	Microchip       *Microchip          // microchip.fk_microchip_animal
	Tags            TagSlice            // tag.fk_tag_animal_id_animal
	UserAnimalLikes UserAnimalLikeSlice // user_animal_like.fk_user_animal_like_animal_id_user
}

type animalColumnNames struct {
	ID              string
	UserID          string
	OrganizationID  string
	Name            string
	TypeID          string
	BreedID         string
	SpeciesID       string
	Gender          string
	Hermaphrodite   string
	Age             string
	CoatLength      string
	Size            string
	ImageURL        string
	Description     string
	Adopted         string
	Status          string
	StatusChangedAt string
	Distance        string
	AdoptedAt       string
	CreatedAt       string
	UpdatedAt       string
}

var AnimalColumns = buildAnimalColumns("animal")

type animalColumns struct {
	tableAlias      string
	ID              psql.Expression
	UserID          psql.Expression
	OrganizationID  psql.Expression
	Name            psql.Expression
	TypeID          psql.Expression
	BreedID         psql.Expression
	SpeciesID       psql.Expression
	Gender          psql.Expression
	Hermaphrodite   psql.Expression
	Age             psql.Expression
	CoatLength      psql.Expression
	Size            psql.Expression
	ImageURL        psql.Expression
	Description     psql.Expression
	Adopted         psql.Expression
	Status          psql.Expression
	StatusChangedAt psql.Expression
	Distance        psql.Expression
	AdoptedAt       psql.Expression
	CreatedAt       psql.Expression
	UpdatedAt       psql.Expression
}

func (c animalColumns) Alias() string {
	return c.tableAlias
}

func (animalColumns) AliasedAs(alias string) animalColumns {
	return buildAnimalColumns(alias)
}

func buildAnimalColumns(alias string) animalColumns {
	return animalColumns{
		tableAlias:      alias,
		ID:              psql.Quote(alias, "id"),
		UserID:          psql.Quote(alias, "user_id"),
		OrganizationID:  psql.Quote(alias, "organization_id"),
		Name:            psql.Quote(alias, "name"),
		TypeID:          psql.Quote(alias, "type_id"),
		BreedID:         psql.Quote(alias, "breed_id"),
		SpeciesID:       psql.Quote(alias, "species_id"),
		Gender:          psql.Quote(alias, "gender"),
		Hermaphrodite:   psql.Quote(alias, "hermaphrodite"),
		Age:             psql.Quote(alias, "age"),
		CoatLength:      psql.Quote(alias, "coat_length"),
		Size:            psql.Quote(alias, "size"),
		ImageURL:        psql.Quote(alias, "image_url"),
		Description:     psql.Quote(alias, "description"),
		Adopted:         psql.Quote(alias, "adopted"),
		Status:          psql.Quote(alias, "status"),
		StatusChangedAt: psql.Quote(alias, "status_changed_at"),
		Distance:        psql.Quote(alias, "distance"),
		AdoptedAt:       psql.Quote(alias, "adopted_at"),
		CreatedAt:       psql.Quote(alias, "created_at"),
		UpdatedAt:       psql.Quote(alias, "updated_at"),
	}
}

type animalWhere[Q psql.Filterable] struct {
	ID              psql.WhereMod[Q, int64]
	UserID          psql.WhereNullMod[Q, uuid.UUID]
	OrganizationID  psql.WhereNullMod[Q, int64]
	Name            psql.WhereMod[Q, string]
	TypeID          psql.WhereMod[Q, int64]
	BreedID         psql.WhereMod[Q, int64]
	SpeciesID       psql.WhereMod[Q, int64]
	Gender          psql.WhereNullMod[Q, Gender]
	Hermaphrodite   psql.WhereMod[Q, bool]
	Age             psql.WhereMod[Q, string]
	CoatLength      psql.WhereNullMod[Q, string]
	Size            psql.WhereMod[Q, string]
	ImageURL        psql.WhereMod[Q, string]
	Description     psql.WhereNullMod[Q, string]
	Adopted         psql.WhereMod[Q, bool]
	Status          psql.WhereNullMod[Q, string]
	StatusChangedAt psql.WhereNullMod[Q, time.Time]
	Distance        psql.WhereNullMod[Q, string]
	AdoptedAt       psql.WhereNullMod[Q, time.Time]
	CreatedAt       psql.WhereMod[Q, time.Time]
	UpdatedAt       psql.WhereMod[Q, time.Time]
}

func (animalWhere[Q]) AliasedAs(alias string) animalWhere[Q] {
	return buildAnimalWhere[Q](buildAnimalColumns(alias))
}

func buildAnimalWhere[Q psql.Filterable](cols animalColumns) animalWhere[Q] {
	return animalWhere[Q]{
		ID:              psql.Where[Q, int64](cols.ID),
		UserID:          psql.WhereNull[Q, uuid.UUID](cols.UserID),
		OrganizationID:  psql.WhereNull[Q, int64](cols.OrganizationID),
		Name:            psql.Where[Q, string](cols.Name),
		TypeID:          psql.Where[Q, int64](cols.TypeID),
		BreedID:         psql.Where[Q, int64](cols.BreedID),
		SpeciesID:       psql.Where[Q, int64](cols.SpeciesID),
		Gender:          psql.WhereNull[Q, Gender](cols.Gender),
		Hermaphrodite:   psql.Where[Q, bool](cols.Hermaphrodite),
		Age:             psql.Where[Q, string](cols.Age),
		CoatLength:      psql.WhereNull[Q, string](cols.CoatLength),
		Size:            psql.Where[Q, string](cols.Size),
		ImageURL:        psql.Where[Q, string](cols.ImageURL),
		Description:     psql.WhereNull[Q, string](cols.Description),
		Adopted:         psql.Where[Q, bool](cols.Adopted),
		Status:          psql.WhereNull[Q, string](cols.Status),
		StatusChangedAt: psql.WhereNull[Q, time.Time](cols.StatusChangedAt),
		Distance:        psql.WhereNull[Q, string](cols.Distance),
		AdoptedAt:       psql.WhereNull[Q, time.Time](cols.AdoptedAt),
		CreatedAt:       psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:       psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

var AnimalErrors = &animalErrors{
	ErrUniqueAnimalPkey: &UniqueConstraintError{
		schema:  "",
		table:   "animal",
		columns: []string{"id"},
		s:       "animal_pkey",
	},
}

type animalErrors struct {
	ErrUniqueAnimalPkey *UniqueConstraintError
}

// AnimalSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type AnimalSetter struct {
	UserID          omitnull.Val[uuid.UUID] `db:"user_id" `
	OrganizationID  omitnull.Val[int64]     `db:"organization_id" `
	Name            omit.Val[string]        `db:"name" `
	TypeID          omit.Val[int64]         `db:"type_id" `
	BreedID         omit.Val[int64]         `db:"breed_id" `
	SpeciesID       omit.Val[int64]         `db:"species_id" `
	Gender          omitnull.Val[Gender]    `db:"gender" `
	Hermaphrodite   omit.Val[bool]          `db:"hermaphrodite" `
	Age             omit.Val[string]        `db:"age" `
	CoatLength      omitnull.Val[string]    `db:"coat_length" `
	Size            omit.Val[string]        `db:"size" `
	ImageURL        omit.Val[string]        `db:"image_url" `
	Description     omitnull.Val[string]    `db:"description" `
	Adopted         omit.Val[bool]          `db:"adopted" `
	Status          omitnull.Val[string]    `db:"status" `
	StatusChangedAt omitnull.Val[time.Time] `db:"status_changed_at" `
	Distance        omitnull.Val[string]    `db:"distance" `
	AdoptedAt       omitnull.Val[time.Time] `db:"adopted_at" `
	CreatedAt       omit.Val[time.Time]     `db:"created_at" `
	UpdatedAt       omit.Val[time.Time]     `db:"updated_at" `
}

func (s AnimalSetter) SetColumns() []string {
	vals := make([]string, 0, 20)
	if !s.UserID.IsUnset() {
		vals = append(vals, "user_id")
	}
	if !s.OrganizationID.IsUnset() {
		vals = append(vals, "organization_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.TypeID.IsValue() {
		vals = append(vals, "type_id")
	}
	if s.BreedID.IsValue() {
		vals = append(vals, "breed_id")
	}
	if s.SpeciesID.IsValue() {
		vals = append(vals, "species_id")
	}
	if !s.Gender.IsUnset() {
		vals = append(vals, "gender")
	}
	if s.Hermaphrodite.IsValue() {
		vals = append(vals, "hermaphrodite")
	}
	if s.Age.IsValue() {
		vals = append(vals, "age")
	}
	if !s.CoatLength.IsUnset() {
		vals = append(vals, "coat_length")
	}
	if s.Size.IsValue() {
		vals = append(vals, "size")
	}
	if s.ImageURL.IsValue() {
		vals = append(vals, "image_url")
	}
	if !s.Description.IsUnset() {
		vals = append(vals, "description")
	}
	if s.Adopted.IsValue() {
		vals = append(vals, "adopted")
	}
	if !s.Status.IsUnset() {
		vals = append(vals, "status")
	}
	if !s.StatusChangedAt.IsUnset() {
		vals = append(vals, "status_changed_at")
	}
	if !s.Distance.IsUnset() {
		vals = append(vals, "distance")
	}
	if !s.AdoptedAt.IsUnset() {
		vals = append(vals, "adopted_at")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s AnimalSetter) Overwrite(t *Animal) {
	if !s.UserID.IsUnset() {
		t.UserID = s.UserID.MustGetNull()
	}
	if !s.OrganizationID.IsUnset() {
		t.OrganizationID = s.OrganizationID.MustGetNull()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.TypeID.IsValue() {
		t.TypeID = s.TypeID.MustGet()
	}
	if s.BreedID.IsValue() {
		t.BreedID = s.BreedID.MustGet()
	}
	if s.SpeciesID.IsValue() {
		t.SpeciesID = s.SpeciesID.MustGet()
	}
	if !s.Gender.IsUnset() {
		t.Gender = s.Gender.MustGetNull()
	}
	if s.Hermaphrodite.IsValue() {
		t.Hermaphrodite = s.Hermaphrodite.MustGet()
	}
	if s.Age.IsValue() {
		t.Age = s.Age.MustGet()
	}
	if !s.CoatLength.IsUnset() {
		t.CoatLength = s.CoatLength.MustGetNull()
	}
	if s.Size.IsValue() {
		t.Size = s.Size.MustGet()
	}
	if s.ImageURL.IsValue() {
		t.ImageURL = s.ImageURL.MustGet()
	}
	if !s.Description.IsUnset() {
		t.Description = s.Description.MustGetNull()
	}
	if s.Adopted.IsValue() {
		t.Adopted = s.Adopted.MustGet()
	}
	if !s.Status.IsUnset() {
		t.Status = s.Status.MustGetNull()
	}
	if !s.StatusChangedAt.IsUnset() {
		t.StatusChangedAt = s.StatusChangedAt.MustGetNull()
	}
	if !s.Distance.IsUnset() {
		t.Distance = s.Distance.MustGetNull()
	}
	if !s.AdoptedAt.IsUnset() {
		t.AdoptedAt = s.AdoptedAt.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *AnimalSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Animals.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 20)
		if !s.UserID.IsUnset() {
			vals[0] = psql.Arg(s.UserID.MustGetNull())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if !s.OrganizationID.IsUnset() {
			vals[1] = psql.Arg(s.OrganizationID.MustGetNull())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[2] = psql.Arg(s.Name.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.TypeID.IsValue() {
			vals[3] = psql.Arg(s.TypeID.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.BreedID.IsValue() {
			vals[4] = psql.Arg(s.BreedID.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.SpeciesID.IsValue() {
			vals[5] = psql.Arg(s.SpeciesID.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.Gender.IsUnset() {
			vals[6] = psql.Arg(s.Gender.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.Hermaphrodite.IsValue() {
			vals[7] = psql.Arg(s.Hermaphrodite.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.Age.IsValue() {
			vals[8] = psql.Arg(s.Age.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.CoatLength.IsUnset() {
			vals[9] = psql.Arg(s.CoatLength.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if s.Size.IsValue() {
			vals[10] = psql.Arg(s.Size.MustGet())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if s.ImageURL.IsValue() {
			vals[11] = psql.Arg(s.ImageURL.MustGet())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		if !s.Description.IsUnset() {
			vals[12] = psql.Arg(s.Description.MustGetNull())
		} else {
			vals[12] = psql.Raw("DEFAULT")
		}

		if s.Adopted.IsValue() {
			vals[13] = psql.Arg(s.Adopted.MustGet())
		} else {
			vals[13] = psql.Raw("DEFAULT")
		}

		if !s.Status.IsUnset() {
			vals[14] = psql.Arg(s.Status.MustGetNull())
		} else {
			vals[14] = psql.Raw("DEFAULT")
		}

		if !s.StatusChangedAt.IsUnset() {
			vals[15] = psql.Arg(s.StatusChangedAt.MustGetNull())
		} else {
			vals[15] = psql.Raw("DEFAULT")
		}

		if !s.Distance.IsUnset() {
			vals[16] = psql.Arg(s.Distance.MustGetNull())
		} else {
			vals[16] = psql.Raw("DEFAULT")
		}

		if !s.AdoptedAt.IsUnset() {
			vals[17] = psql.Arg(s.AdoptedAt.MustGetNull())
		} else {
			vals[17] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[18] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[18] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[19] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[19] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s AnimalSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s AnimalSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 20)

	if !s.UserID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if !s.OrganizationID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "organization_id")...),
			psql.Arg(s.OrganizationID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.TypeID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "type_id")...),
			psql.Arg(s.TypeID),
		}})
	}

	if s.BreedID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "breed_id")...),
			psql.Arg(s.BreedID),
		}})
	}

	if s.SpeciesID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "species_id")...),
			psql.Arg(s.SpeciesID),
		}})
	}

	if !s.Gender.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "gender")...),
			psql.Arg(s.Gender),
		}})
	}

	if s.Hermaphrodite.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "hermaphrodite")...),
			psql.Arg(s.Hermaphrodite),
		}})
	}

	if s.Age.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "age")...),
			psql.Arg(s.Age),
		}})
	}

	if !s.CoatLength.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "coat_length")...),
			psql.Arg(s.CoatLength),
		}})
	}

	if s.Size.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "size")...),
			psql.Arg(s.Size),
		}})
	}

	if s.ImageURL.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "image_url")...),
			psql.Arg(s.ImageURL),
		}})
	}

	if !s.Description.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if s.Adopted.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "adopted")...),
			psql.Arg(s.Adopted),
		}})
	}

	if !s.Status.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if !s.StatusChangedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status_changed_at")...),
			psql.Arg(s.StatusChangedAt),
		}})
	}

	if !s.Distance.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "distance")...),
			psql.Arg(s.Distance),
		}})
	}

	if !s.AdoptedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "adopted_at")...),
			psql.Arg(s.AdoptedAt),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindAnimal retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAnimal(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Animal, error) {
	if len(cols) == 0 {
		return Animals.Query(
			SelectWhere.Animals.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Animals.Query(
		SelectWhere.Animals.ID.EQ(IDPK),
		sm.Columns(Animals.Columns().Only(cols...)),
	).One(ctx, exec)
}

// AnimalExists checks the presence of a single record by primary key
func AnimalExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Animals.Query(
		SelectWhere.Animals.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Animal is retrieved from the database
func (o *Animal) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Animals.AfterSelectHooks.RunHooks(ctx, exec, AnimalSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Animals.AfterInsertHooks.RunHooks(ctx, exec, AnimalSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Animals.AfterUpdateHooks.RunHooks(ctx, exec, AnimalSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Animals.AfterDeleteHooks.RunHooks(ctx, exec, AnimalSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Animal
func (o *Animal) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Animal) pkEQ() dialect.Expression {
	return psql.Quote("animal", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Animal
func (o *Animal) Update(ctx context.Context, exec bob.Executor, s *AnimalSetter) error {
	v, err := Animals.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Animal record with an executor
func (o *Animal) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Animals.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Animal using the executor
func (o *Animal) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Animals.Query(
		SelectWhere.Animals.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after AnimalSlice is retrieved from the database
func (o AnimalSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Animals.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Animals.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Animals.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Animals.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o AnimalSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("animal", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o AnimalSlice) copyMatchingRows(from ...*Animal) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o AnimalSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Animals.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Animal:
				o.copyMatchingRows(retrieved)
			case []*Animal:
				o.copyMatchingRows(retrieved...)
			case AnimalSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Animal or a slice of Animal
				// then run the AfterUpdateHooks on the slice
				_, err = Animals.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o AnimalSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Animals.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Animal:
				o.copyMatchingRows(retrieved)
			case []*Animal:
				o.copyMatchingRows(retrieved...)
			case AnimalSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Animal or a slice of Animal
				// then run the AfterDeleteHooks on the slice
				_, err = Animals.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o AnimalSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals AnimalSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Animals.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o AnimalSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Animals.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o AnimalSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Animals.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type animalJoins[Q dialect.Joinable] struct {
	typ             string
	Adoptions       modAs[Q, adoptionColumns]
	Organization    modAs[Q, organizationColumns]
	User            modAs[Q, userColumns]
	AnimalBreeds    modAs[Q, animalBreedColumns]
	AnimalPhotos    modAs[Q, animalPhotoColumns]
	AnimalVideos    modAs[Q, animalVideoColumns]
	Colors          modAs[Q, colorColumns]
	Contacts        modAs[Q, contactColumns]
	Microchip       modAs[Q, microchipColumns]
	Tags            modAs[Q, tagColumns]
	UserAnimalLikes modAs[Q, userAnimalLikeColumns]
}

func (j animalJoins[Q]) aliasedAs(alias string) animalJoins[Q] {
	return buildAnimalJoins[Q](buildAnimalColumns(alias), j.typ)
}

func buildAnimalJoins[Q dialect.Joinable](cols animalColumns, typ string) animalJoins[Q] {
	return animalJoins[Q]{
		typ: typ,
		Adoptions: modAs[Q, adoptionColumns]{
			c: AdoptionColumns,
			f: func(to adoptionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Adoptions.Name().As(to.Alias())).On(
						to.AnimalID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Organization: modAs[Q, organizationColumns]{
			c: OrganizationColumns,
			f: func(to organizationColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Organizations.Name().As(to.Alias())).On(
						to.ID.EQ(cols.OrganizationID),
					))
				}

				return mods
			},
		},
		User: modAs[Q, userColumns]{
			c: UserColumns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(cols.UserID),
					))
				}

				return mods
			},
		},
		AnimalBreeds: modAs[Q, animalBreedColumns]{
			c: AnimalBreedColumns,
			f: func(to animalBreedColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, AnimalBreeds.Name().As(to.Alias())).On(
						to.AnimalID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		AnimalPhotos: modAs[Q, animalPhotoColumns]{
			c: AnimalPhotoColumns,
			f: func(to animalPhotoColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, AnimalPhotos.Name().As(to.Alias())).On(
						to.AnimalID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		AnimalVideos: modAs[Q, animalVideoColumns]{
			c: AnimalVideoColumns,
			f: func(to animalVideoColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, AnimalVideos.Name().As(to.Alias())).On(
						to.AnimalID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Colors: modAs[Q, colorColumns]{
			c: ColorColumns,
			f: func(to colorColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Colors.Name().As(to.Alias())).On(
						to.AnimalID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Contacts: modAs[Q, contactColumns]{
			c: ContactColumns,
			f: func(to contactColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Contacts.Name().As(to.Alias())).On(
						to.AnimalID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Microchip: modAs[Q, microchipColumns]{
			c: MicrochipColumns,
			f: func(to microchipColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Microchips.Name().As(to.Alias())).On(
						to.AnimalID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Tags: modAs[Q, tagColumns]{
			c: TagColumns,
			f: func(to tagColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Tags.Name().As(to.Alias())).On(
						to.AnimalID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		UserAnimalLikes: modAs[Q, userAnimalLikeColumns]{
			c: UserAnimalLikeColumns,
			f: func(to userAnimalLikeColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, UserAnimalLikes.Name().As(to.Alias())).On(
						to.AnimalID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}

// Adoptions starts a query for related objects on adoption
func (o *Animal) Adoptions(mods ...bob.Mod[*dialect.SelectQuery]) AdoptionsQuery {
	return Adoptions.Query(append(mods,
		sm.Where(AdoptionColumns.AnimalID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AnimalSlice) Adoptions(mods ...bob.Mod[*dialect.SelectQuery]) AdoptionsQuery {
	pkID := make(pgtypes.Array[int64], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Adoptions.Query(append(mods,
		sm.Where(psql.Group(AdoptionColumns.AnimalID).OP("IN", PKArgExpr)),
	)...)
}

// Organization starts a query for related objects on organization
func (o *Animal) Organization(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationsQuery {
	return Organizations.Query(append(mods,
		sm.Where(OrganizationColumns.ID.EQ(psql.Arg(o.OrganizationID))),
	)...)
}

func (os AnimalSlice) Organization(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationsQuery {
	pkOrganizationID := make(pgtypes.Array[null.Val[int64]], len(os))
	for i, o := range os {
		pkOrganizationID[i] = o.OrganizationID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkOrganizationID), "bigint[]")),
	))

	return Organizations.Query(append(mods,
		sm.Where(psql.Group(OrganizationColumns.ID).OP("IN", PKArgExpr)),
	)...)
}

// User starts a query for related objects on user
func (o *Animal) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(UserColumns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os AnimalSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	pkUserID := make(pgtypes.Array[null.Val[uuid.UUID]], len(os))
	for i, o := range os {
		pkUserID[i] = o.UserID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkUserID), "uuid[]")),
	))

	return Users.Query(append(mods,
		sm.Where(psql.Group(UserColumns.ID).OP("IN", PKArgExpr)),
	)...)
}

// AnimalBreeds starts a query for related objects on animal_breed
func (o *Animal) AnimalBreeds(mods ...bob.Mod[*dialect.SelectQuery]) AnimalBreedsQuery {
	return AnimalBreeds.Query(append(mods,
		sm.Where(AnimalBreedColumns.AnimalID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AnimalSlice) AnimalBreeds(mods ...bob.Mod[*dialect.SelectQuery]) AnimalBreedsQuery {
	pkID := make(pgtypes.Array[int64], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return AnimalBreeds.Query(append(mods,
		sm.Where(psql.Group(AnimalBreedColumns.AnimalID).OP("IN", PKArgExpr)),
	)...)
}

// AnimalPhotos starts a query for related objects on animal_photo
func (o *Animal) AnimalPhotos(mods ...bob.Mod[*dialect.SelectQuery]) AnimalPhotosQuery {
	return AnimalPhotos.Query(append(mods,
		sm.Where(AnimalPhotoColumns.AnimalID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AnimalSlice) AnimalPhotos(mods ...bob.Mod[*dialect.SelectQuery]) AnimalPhotosQuery {
	pkID := make(pgtypes.Array[int64], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return AnimalPhotos.Query(append(mods,
		sm.Where(psql.Group(AnimalPhotoColumns.AnimalID).OP("IN", PKArgExpr)),
	)...)
}

// AnimalVideos starts a query for related objects on animal_video
func (o *Animal) AnimalVideos(mods ...bob.Mod[*dialect.SelectQuery]) AnimalVideosQuery {
	return AnimalVideos.Query(append(mods,
		sm.Where(AnimalVideoColumns.AnimalID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AnimalSlice) AnimalVideos(mods ...bob.Mod[*dialect.SelectQuery]) AnimalVideosQuery {
	pkID := make(pgtypes.Array[int64], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return AnimalVideos.Query(append(mods,
		sm.Where(psql.Group(AnimalVideoColumns.AnimalID).OP("IN", PKArgExpr)),
	)...)
}

// Colors starts a query for related objects on color
func (o *Animal) Colors(mods ...bob.Mod[*dialect.SelectQuery]) ColorsQuery {
	return Colors.Query(append(mods,
		sm.Where(ColorColumns.AnimalID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AnimalSlice) Colors(mods ...bob.Mod[*dialect.SelectQuery]) ColorsQuery {
	pkID := make(pgtypes.Array[int64], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Colors.Query(append(mods,
		sm.Where(psql.Group(ColorColumns.AnimalID).OP("IN", PKArgExpr)),
	)...)
}

// Contacts starts a query for related objects on contact
func (o *Animal) Contacts(mods ...bob.Mod[*dialect.SelectQuery]) ContactsQuery {
	return Contacts.Query(append(mods,
		sm.Where(ContactColumns.AnimalID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AnimalSlice) Contacts(mods ...bob.Mod[*dialect.SelectQuery]) ContactsQuery {
	pkID := make(pgtypes.Array[int64], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Contacts.Query(append(mods,
		sm.Where(psql.Group(ContactColumns.AnimalID).OP("IN", PKArgExpr)),
	)...)
}

// Microchip starts a query for related objects on microchip
func (o *Animal) Microchip(mods ...bob.Mod[*dialect.SelectQuery]) MicrochipsQuery {
	return Microchips.Query(append(mods,
		sm.Where(MicrochipColumns.AnimalID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AnimalSlice) Microchip(mods ...bob.Mod[*dialect.SelectQuery]) MicrochipsQuery {
	pkID := make(pgtypes.Array[int64], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Microchips.Query(append(mods,
		sm.Where(psql.Group(MicrochipColumns.AnimalID).OP("IN", PKArgExpr)),
	)...)
}

// Tags starts a query for related objects on tag
func (o *Animal) Tags(mods ...bob.Mod[*dialect.SelectQuery]) TagsQuery {
	return Tags.Query(append(mods,
		sm.Where(TagColumns.AnimalID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AnimalSlice) Tags(mods ...bob.Mod[*dialect.SelectQuery]) TagsQuery {
	pkID := make(pgtypes.Array[int64], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Tags.Query(append(mods,
		sm.Where(psql.Group(TagColumns.AnimalID).OP("IN", PKArgExpr)),
	)...)
}

// UserAnimalLikes starts a query for related objects on user_animal_like
func (o *Animal) UserAnimalLikes(mods ...bob.Mod[*dialect.SelectQuery]) UserAnimalLikesQuery {
	return UserAnimalLikes.Query(append(mods,
		sm.Where(UserAnimalLikeColumns.AnimalID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AnimalSlice) UserAnimalLikes(mods ...bob.Mod[*dialect.SelectQuery]) UserAnimalLikesQuery {
	pkID := make(pgtypes.Array[int64], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return UserAnimalLikes.Query(append(mods,
		sm.Where(psql.Group(UserAnimalLikeColumns.AnimalID).OP("IN", PKArgExpr)),
	)...)
}

func (o *Animal) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Adoptions":
		rels, ok := retrieved.(AdoptionSlice)
		if !ok {
			return fmt.Errorf("animal cannot load %T as %q", retrieved, name)
		}

		o.R.Adoptions = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Animal = o
			}
		}
		return nil
	case "Organization":
		rel, ok := retrieved.(*Organization)
		if !ok {
			return fmt.Errorf("animal cannot load %T as %q", retrieved, name)
		}

		o.R.Organization = rel

		if rel != nil {
			rel.R.Animals = AnimalSlice{o}
		}
		return nil
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("animal cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.Animals = AnimalSlice{o}
		}
		return nil
	case "AnimalBreeds":
		rels, ok := retrieved.(AnimalBreedSlice)
		if !ok {
			return fmt.Errorf("animal cannot load %T as %q", retrieved, name)
		}

		o.R.AnimalBreeds = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Animal = o
			}
		}
		return nil
	case "AnimalPhotos":
		rels, ok := retrieved.(AnimalPhotoSlice)
		if !ok {
			return fmt.Errorf("animal cannot load %T as %q", retrieved, name)
		}

		o.R.AnimalPhotos = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Animal = o
			}
		}
		return nil
	case "AnimalVideos":
		rels, ok := retrieved.(AnimalVideoSlice)
		if !ok {
			return fmt.Errorf("animal cannot load %T as %q", retrieved, name)
		}

		o.R.AnimalVideos = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Animal = o
			}
		}
		return nil
	case "Colors":
		rels, ok := retrieved.(ColorSlice)
		if !ok {
			return fmt.Errorf("animal cannot load %T as %q", retrieved, name)
		}

		o.R.Colors = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Animal = o
			}
		}
		return nil
	case "Contacts":
		rels, ok := retrieved.(ContactSlice)
		if !ok {
			return fmt.Errorf("animal cannot load %T as %q", retrieved, name)
		}

		o.R.Contacts = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Animal = o
			}
		}
		return nil
	case "Microchip":
		rel, ok := retrieved.(*Microchip)
		if !ok {
			return fmt.Errorf("animal cannot load %T as %q", retrieved, name)
		}

		o.R.Microchip = rel

		if rel != nil {
			rel.R.Animal = o
		}
		return nil
	case "Tags":
		rels, ok := retrieved.(TagSlice)
		if !ok {
			return fmt.Errorf("animal cannot load %T as %q", retrieved, name)
		}

		o.R.Tags = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Animal = o
			}
		}
		return nil
	case "UserAnimalLikes":
		rels, ok := retrieved.(UserAnimalLikeSlice)
		if !ok {
			return fmt.Errorf("animal cannot load %T as %q", retrieved, name)
		}

		o.R.UserAnimalLikes = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Animal = o
			}
		}
		return nil
	default:
		return fmt.Errorf("animal has no relationship %q", name)
	}
}

type animalPreloader struct {
	Organization func(...psql.PreloadOption) psql.Preloader
	User         func(...psql.PreloadOption) psql.Preloader
	Microchip    func(...psql.PreloadOption) psql.Preloader
}

func buildAnimalPreloader() animalPreloader {
	return animalPreloader{
		Organization: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Organization, OrganizationSlice](orm.Relationship{
				Name: "Organization",
				Sides: []orm.RelSide{
					{
						From: TableNames.Animals,
						To:   TableNames.Organizations,
						FromColumns: []string{
							ColumnNames.Animals.OrganizationID,
						},
						ToColumns: []string{
							ColumnNames.Organizations.ID,
						},
					},
				},
			}, Organizations.Columns().Names(), opts...)
		},
		User: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*User, UserSlice](orm.Relationship{
				Name: "User",
				Sides: []orm.RelSide{
					{
						From: TableNames.Animals,
						To:   TableNames.Users,
						FromColumns: []string{
							ColumnNames.Animals.UserID,
						},
						ToColumns: []string{
							ColumnNames.Users.ID,
						},
					},
				},
			}, Users.Columns().Names(), opts...)
		},
		Microchip: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Microchip, MicrochipSlice](orm.Relationship{
				Name: "Microchip",
				Sides: []orm.RelSide{
					{
						From: TableNames.Animals,
						To:   TableNames.Microchips,
						FromColumns: []string{
							ColumnNames.Animals.ID,
						},
						ToColumns: []string{
							ColumnNames.Microchips.AnimalID,
						},
					},
				},
			}, Microchips.Columns().Names(), opts...)
		},
	}
}

type animalThenLoader[Q orm.Loadable] struct {
	Adoptions       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Organization    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	User            func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	AnimalBreeds    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	AnimalPhotos    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	AnimalVideos    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Colors          func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Contacts        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Microchip       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Tags            func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UserAnimalLikes func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildAnimalThenLoader[Q orm.Loadable]() animalThenLoader[Q] {
	type AdoptionsLoadInterface interface {
		LoadAdoptions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrganizationLoadInterface interface {
		LoadOrganization(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserLoadInterface interface {
		LoadUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type AnimalBreedsLoadInterface interface {
		LoadAnimalBreeds(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type AnimalPhotosLoadInterface interface {
		LoadAnimalPhotos(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type AnimalVideosLoadInterface interface {
		LoadAnimalVideos(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ColorsLoadInterface interface {
		LoadColors(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ContactsLoadInterface interface {
		LoadContacts(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MicrochipLoadInterface interface {
		LoadMicrochip(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TagsLoadInterface interface {
		LoadTags(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserAnimalLikesLoadInterface interface {
		LoadUserAnimalLikes(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return animalThenLoader[Q]{
		Adoptions: thenLoadBuilder[Q](
			"Adoptions",
			func(ctx context.Context, exec bob.Executor, retrieved AdoptionsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAdoptions(ctx, exec, mods...)
			},
		),
		Organization: thenLoadBuilder[Q](
			"Organization",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganization(ctx, exec, mods...)
			},
		),
		User: thenLoadBuilder[Q](
			"User",
			func(ctx context.Context, exec bob.Executor, retrieved UserLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUser(ctx, exec, mods...)
			},
		),
		AnimalBreeds: thenLoadBuilder[Q](
			"AnimalBreeds",
			func(ctx context.Context, exec bob.Executor, retrieved AnimalBreedsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAnimalBreeds(ctx, exec, mods...)
			},
		),
		AnimalPhotos: thenLoadBuilder[Q](
			"AnimalPhotos",
			func(ctx context.Context, exec bob.Executor, retrieved AnimalPhotosLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAnimalPhotos(ctx, exec, mods...)
			},
		),
		AnimalVideos: thenLoadBuilder[Q](
			"AnimalVideos",
			func(ctx context.Context, exec bob.Executor, retrieved AnimalVideosLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAnimalVideos(ctx, exec, mods...)
			},
		),
		Colors: thenLoadBuilder[Q](
			"Colors",
			func(ctx context.Context, exec bob.Executor, retrieved ColorsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadColors(ctx, exec, mods...)
			},
		),
		Contacts: thenLoadBuilder[Q](
			"Contacts",
			func(ctx context.Context, exec bob.Executor, retrieved ContactsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadContacts(ctx, exec, mods...)
			},
		),
		Microchip: thenLoadBuilder[Q](
			"Microchip",
			func(ctx context.Context, exec bob.Executor, retrieved MicrochipLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMicrochip(ctx, exec, mods...)
			},
		),
		Tags: thenLoadBuilder[Q](
			"Tags",
			func(ctx context.Context, exec bob.Executor, retrieved TagsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTags(ctx, exec, mods...)
			},
		),
		UserAnimalLikes: thenLoadBuilder[Q](
			"UserAnimalLikes",
			func(ctx context.Context, exec bob.Executor, retrieved UserAnimalLikesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUserAnimalLikes(ctx, exec, mods...)
			},
		),
	}
}

// LoadAdoptions loads the animal's Adoptions into the .R struct
func (o *Animal) LoadAdoptions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Adoptions = nil

	related, err := o.Adoptions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Animal = o
	}

	o.R.Adoptions = related
	return nil
}

// LoadAdoptions loads the animal's Adoptions into the .R struct
func (os AnimalSlice) LoadAdoptions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	adoptions, err := os.Adoptions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.Adoptions = nil
	}

	for _, o := range os {
		for _, rel := range adoptions {

			if !rel.AnimalID.IsValue() {
				continue
			}
			if o.ID != rel.AnimalID.MustGet() {
				continue
			}

			rel.R.Animal = o

			o.R.Adoptions = append(o.R.Adoptions, rel)
		}
	}

	return nil
}

// LoadOrganization loads the animal's Organization into the .R struct
func (o *Animal) LoadOrganization(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Organization = nil

	related, err := o.Organization(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Animals = AnimalSlice{o}

	o.R.Organization = related
	return nil
}

// LoadOrganization loads the animal's Organization into the .R struct
func (os AnimalSlice) LoadOrganization(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizations, err := os.Organization(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range organizations {
			if !o.OrganizationID.IsValue() {
				continue
			}

			if o.OrganizationID.MustGet() != rel.ID {
				continue
			}

			rel.R.Animals = append(rel.R.Animals, o)

			o.R.Organization = rel
			break
		}
	}

	return nil
}

// LoadUser loads the animal's User into the .R struct
func (o *Animal) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Animals = AnimalSlice{o}

	o.R.User = related
	return nil
}

// LoadUser loads the animal's User into the .R struct
func (os AnimalSlice) LoadUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range users {
			if !o.UserID.IsValue() {
				continue
			}

			if o.UserID.MustGet() != rel.ID {
				continue
			}

			rel.R.Animals = append(rel.R.Animals, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

// LoadAnimalBreeds loads the animal's AnimalBreeds into the .R struct
func (o *Animal) LoadAnimalBreeds(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.AnimalBreeds = nil

	related, err := o.AnimalBreeds(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Animal = o
	}

	o.R.AnimalBreeds = related
	return nil
}

// LoadAnimalBreeds loads the animal's AnimalBreeds into the .R struct
func (os AnimalSlice) LoadAnimalBreeds(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	animalBreeds, err := os.AnimalBreeds(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.AnimalBreeds = nil
	}

	for _, o := range os {
		for _, rel := range animalBreeds {

			if o.ID != rel.AnimalID {
				continue
			}

			rel.R.Animal = o

			o.R.AnimalBreeds = append(o.R.AnimalBreeds, rel)
		}
	}

	return nil
}

// LoadAnimalPhotos loads the animal's AnimalPhotos into the .R struct
func (o *Animal) LoadAnimalPhotos(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.AnimalPhotos = nil

	related, err := o.AnimalPhotos(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Animal = o
	}

	o.R.AnimalPhotos = related
	return nil
}

// LoadAnimalPhotos loads the animal's AnimalPhotos into the .R struct
func (os AnimalSlice) LoadAnimalPhotos(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	animalPhotos, err := os.AnimalPhotos(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.AnimalPhotos = nil
	}

	for _, o := range os {
		for _, rel := range animalPhotos {

			if !rel.AnimalID.IsValue() {
				continue
			}
			if o.ID != rel.AnimalID.MustGet() {
				continue
			}

			rel.R.Animal = o

			o.R.AnimalPhotos = append(o.R.AnimalPhotos, rel)
		}
	}

	return nil
}

// LoadAnimalVideos loads the animal's AnimalVideos into the .R struct
func (o *Animal) LoadAnimalVideos(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.AnimalVideos = nil

	related, err := o.AnimalVideos(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Animal = o
	}

	o.R.AnimalVideos = related
	return nil
}

// LoadAnimalVideos loads the animal's AnimalVideos into the .R struct
func (os AnimalSlice) LoadAnimalVideos(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	animalVideos, err := os.AnimalVideos(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.AnimalVideos = nil
	}

	for _, o := range os {
		for _, rel := range animalVideos {

			if !rel.AnimalID.IsValue() {
				continue
			}
			if o.ID != rel.AnimalID.MustGet() {
				continue
			}

			rel.R.Animal = o

			o.R.AnimalVideos = append(o.R.AnimalVideos, rel)
		}
	}

	return nil
}

// LoadColors loads the animal's Colors into the .R struct
func (o *Animal) LoadColors(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Colors = nil

	related, err := o.Colors(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Animal = o
	}

	o.R.Colors = related
	return nil
}

// LoadColors loads the animal's Colors into the .R struct
func (os AnimalSlice) LoadColors(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	colors, err := os.Colors(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.Colors = nil
	}

	for _, o := range os {
		for _, rel := range colors {

			if !rel.AnimalID.IsValue() {
				continue
			}
			if o.ID != rel.AnimalID.MustGet() {
				continue
			}

			rel.R.Animal = o

			o.R.Colors = append(o.R.Colors, rel)
		}
	}

	return nil
}

// LoadContacts loads the animal's Contacts into the .R struct
func (o *Animal) LoadContacts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Contacts = nil

	related, err := o.Contacts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Animal = o
	}

	o.R.Contacts = related
	return nil
}

// LoadContacts loads the animal's Contacts into the .R struct
func (os AnimalSlice) LoadContacts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	contacts, err := os.Contacts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.Contacts = nil
	}

	for _, o := range os {
		for _, rel := range contacts {

			if !rel.AnimalID.IsValue() {
				continue
			}
			if o.ID != rel.AnimalID.MustGet() {
				continue
			}

			rel.R.Animal = o

			o.R.Contacts = append(o.R.Contacts, rel)
		}
	}

	return nil
}

// LoadMicrochip loads the animal's Microchip into the .R struct
func (o *Animal) LoadMicrochip(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Microchip = nil

	related, err := o.Microchip(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Animal = o

	o.R.Microchip = related
	return nil
}

// LoadMicrochip loads the animal's Microchip into the .R struct
func (os AnimalSlice) LoadMicrochip(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	microchips, err := os.Microchip(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range microchips {

			if !rel.AnimalID.IsValue() {
				continue
			}
			if o.ID != rel.AnimalID.MustGet() {
				continue
			}

			rel.R.Animal = o

			o.R.Microchip = rel
			break
		}
	}

	return nil
}

// LoadTags loads the animal's Tags into the .R struct
func (o *Animal) LoadTags(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Tags = nil

	related, err := o.Tags(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Animal = o
	}

	o.R.Tags = related
	return nil
}

// LoadTags loads the animal's Tags into the .R struct
func (os AnimalSlice) LoadTags(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	tags, err := os.Tags(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.Tags = nil
	}

	for _, o := range os {
		for _, rel := range tags {

			if !rel.AnimalID.IsValue() {
				continue
			}
			if o.ID != rel.AnimalID.MustGet() {
				continue
			}

			rel.R.Animal = o

			o.R.Tags = append(o.R.Tags, rel)
		}
	}

	return nil
}

// LoadUserAnimalLikes loads the animal's UserAnimalLikes into the .R struct
func (o *Animal) LoadUserAnimalLikes(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UserAnimalLikes = nil

	related, err := o.UserAnimalLikes(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Animal = o
	}

	o.R.UserAnimalLikes = related
	return nil
}

// LoadUserAnimalLikes loads the animal's UserAnimalLikes into the .R struct
func (os AnimalSlice) LoadUserAnimalLikes(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	userAnimalLikes, err := os.UserAnimalLikes(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.UserAnimalLikes = nil
	}

	for _, o := range os {
		for _, rel := range userAnimalLikes {

			if o.ID != rel.AnimalID {
				continue
			}

			rel.R.Animal = o

			o.R.UserAnimalLikes = append(o.R.UserAnimalLikes, rel)
		}
	}

	return nil
}

func insertAnimalAdoptions0(ctx context.Context, exec bob.Executor, adoptions1 []*AdoptionSetter, animal0 *Animal) (AdoptionSlice, error) {
	for i := range adoptions1 {
		adoptions1[i].AnimalID = omitnull.From(animal0.ID)
	}

	ret, err := Adoptions.Insert(bob.ToMods(adoptions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAnimalAdoptions0: %w", err)
	}

	return ret, nil
}

func attachAnimalAdoptions0(ctx context.Context, exec bob.Executor, count int, adoptions1 AdoptionSlice, animal0 *Animal) (AdoptionSlice, error) {
	setter := &AdoptionSetter{
		AnimalID: omitnull.From(animal0.ID),
	}

	err := adoptions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAnimalAdoptions0: %w", err)
	}

	return adoptions1, nil
}

func (animal0 *Animal) InsertAdoptions(ctx context.Context, exec bob.Executor, related ...*AdoptionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	adoptions1, err := insertAnimalAdoptions0(ctx, exec, related, animal0)
	if err != nil {
		return err
	}

	animal0.R.Adoptions = append(animal0.R.Adoptions, adoptions1...)

	for _, rel := range adoptions1 {
		rel.R.Animal = animal0
	}
	return nil
}

func (animal0 *Animal) AttachAdoptions(ctx context.Context, exec bob.Executor, related ...*Adoption) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	adoptions1 := AdoptionSlice(related)

	_, err = attachAnimalAdoptions0(ctx, exec, len(related), adoptions1, animal0)
	if err != nil {
		return err
	}

	animal0.R.Adoptions = append(animal0.R.Adoptions, adoptions1...)

	for _, rel := range related {
		rel.R.Animal = animal0
	}

	return nil
}

func attachAnimalOrganization0(ctx context.Context, exec bob.Executor, count int, animal0 *Animal, organization1 *Organization) (*Animal, error) {
	setter := &AnimalSetter{
		OrganizationID: omitnull.From(organization1.ID),
	}

	err := animal0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAnimalOrganization0: %w", err)
	}

	return animal0, nil
}

func (animal0 *Animal) InsertOrganization(ctx context.Context, exec bob.Executor, related *OrganizationSetter) error {
	organization1, err := Organizations.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachAnimalOrganization0(ctx, exec, 1, animal0, organization1)
	if err != nil {
		return err
	}

	animal0.R.Organization = organization1

	organization1.R.Animals = append(organization1.R.Animals, animal0)

	return nil
}

func (animal0 *Animal) AttachOrganization(ctx context.Context, exec bob.Executor, organization1 *Organization) error {
	var err error

	_, err = attachAnimalOrganization0(ctx, exec, 1, animal0, organization1)
	if err != nil {
		return err
	}

	animal0.R.Organization = organization1

	organization1.R.Animals = append(organization1.R.Animals, animal0)

	return nil
}

func attachAnimalUser0(ctx context.Context, exec bob.Executor, count int, animal0 *Animal, user1 *User) (*Animal, error) {
	setter := &AnimalSetter{
		UserID: omitnull.From(user1.ID),
	}

	err := animal0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAnimalUser0: %w", err)
	}

	return animal0, nil
}

func (animal0 *Animal) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachAnimalUser0(ctx, exec, 1, animal0, user1)
	if err != nil {
		return err
	}

	animal0.R.User = user1

	user1.R.Animals = append(user1.R.Animals, animal0)

	return nil
}

func (animal0 *Animal) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachAnimalUser0(ctx, exec, 1, animal0, user1)
	if err != nil {
		return err
	}

	animal0.R.User = user1

	user1.R.Animals = append(user1.R.Animals, animal0)

	return nil
}

func insertAnimalAnimalBreeds0(ctx context.Context, exec bob.Executor, animalBreeds1 []*AnimalBreedSetter, animal0 *Animal) (AnimalBreedSlice, error) {
	for i := range animalBreeds1 {
		animalBreeds1[i].AnimalID = omit.From(animal0.ID)
	}

	ret, err := AnimalBreeds.Insert(bob.ToMods(animalBreeds1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAnimalAnimalBreeds0: %w", err)
	}

	return ret, nil
}

func attachAnimalAnimalBreeds0(ctx context.Context, exec bob.Executor, count int, animalBreeds1 AnimalBreedSlice, animal0 *Animal) (AnimalBreedSlice, error) {
	setter := &AnimalBreedSetter{
		AnimalID: omit.From(animal0.ID),
	}

	err := animalBreeds1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAnimalAnimalBreeds0: %w", err)
	}

	return animalBreeds1, nil
}

func (animal0 *Animal) InsertAnimalBreeds(ctx context.Context, exec bob.Executor, related ...*AnimalBreedSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	animalBreeds1, err := insertAnimalAnimalBreeds0(ctx, exec, related, animal0)
	if err != nil {
		return err
	}

	animal0.R.AnimalBreeds = append(animal0.R.AnimalBreeds, animalBreeds1...)

	for _, rel := range animalBreeds1 {
		rel.R.Animal = animal0
	}
	return nil
}

func (animal0 *Animal) AttachAnimalBreeds(ctx context.Context, exec bob.Executor, related ...*AnimalBreed) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	animalBreeds1 := AnimalBreedSlice(related)

	_, err = attachAnimalAnimalBreeds0(ctx, exec, len(related), animalBreeds1, animal0)
	if err != nil {
		return err
	}

	animal0.R.AnimalBreeds = append(animal0.R.AnimalBreeds, animalBreeds1...)

	for _, rel := range related {
		rel.R.Animal = animal0
	}

	return nil
}

func insertAnimalAnimalPhotos0(ctx context.Context, exec bob.Executor, animalPhotos1 []*AnimalPhotoSetter, animal0 *Animal) (AnimalPhotoSlice, error) {
	for i := range animalPhotos1 {
		animalPhotos1[i].AnimalID = omitnull.From(animal0.ID)
	}

	ret, err := AnimalPhotos.Insert(bob.ToMods(animalPhotos1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAnimalAnimalPhotos0: %w", err)
	}

	return ret, nil
}

func attachAnimalAnimalPhotos0(ctx context.Context, exec bob.Executor, count int, animalPhotos1 AnimalPhotoSlice, animal0 *Animal) (AnimalPhotoSlice, error) {
	setter := &AnimalPhotoSetter{
		AnimalID: omitnull.From(animal0.ID),
	}

	err := animalPhotos1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAnimalAnimalPhotos0: %w", err)
	}

	return animalPhotos1, nil
}

func (animal0 *Animal) InsertAnimalPhotos(ctx context.Context, exec bob.Executor, related ...*AnimalPhotoSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	animalPhotos1, err := insertAnimalAnimalPhotos0(ctx, exec, related, animal0)
	if err != nil {
		return err
	}

	animal0.R.AnimalPhotos = append(animal0.R.AnimalPhotos, animalPhotos1...)

	for _, rel := range animalPhotos1 {
		rel.R.Animal = animal0
	}
	return nil
}

func (animal0 *Animal) AttachAnimalPhotos(ctx context.Context, exec bob.Executor, related ...*AnimalPhoto) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	animalPhotos1 := AnimalPhotoSlice(related)

	_, err = attachAnimalAnimalPhotos0(ctx, exec, len(related), animalPhotos1, animal0)
	if err != nil {
		return err
	}

	animal0.R.AnimalPhotos = append(animal0.R.AnimalPhotos, animalPhotos1...)

	for _, rel := range related {
		rel.R.Animal = animal0
	}

	return nil
}

func insertAnimalAnimalVideos0(ctx context.Context, exec bob.Executor, animalVideos1 []*AnimalVideoSetter, animal0 *Animal) (AnimalVideoSlice, error) {
	for i := range animalVideos1 {
		animalVideos1[i].AnimalID = omitnull.From(animal0.ID)
	}

	ret, err := AnimalVideos.Insert(bob.ToMods(animalVideos1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAnimalAnimalVideos0: %w", err)
	}

	return ret, nil
}

func attachAnimalAnimalVideos0(ctx context.Context, exec bob.Executor, count int, animalVideos1 AnimalVideoSlice, animal0 *Animal) (AnimalVideoSlice, error) {
	setter := &AnimalVideoSetter{
		AnimalID: omitnull.From(animal0.ID),
	}

	err := animalVideos1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAnimalAnimalVideos0: %w", err)
	}

	return animalVideos1, nil
}

func (animal0 *Animal) InsertAnimalVideos(ctx context.Context, exec bob.Executor, related ...*AnimalVideoSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	animalVideos1, err := insertAnimalAnimalVideos0(ctx, exec, related, animal0)
	if err != nil {
		return err
	}

	animal0.R.AnimalVideos = append(animal0.R.AnimalVideos, animalVideos1...)

	for _, rel := range animalVideos1 {
		rel.R.Animal = animal0
	}
	return nil
}

func (animal0 *Animal) AttachAnimalVideos(ctx context.Context, exec bob.Executor, related ...*AnimalVideo) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	animalVideos1 := AnimalVideoSlice(related)

	_, err = attachAnimalAnimalVideos0(ctx, exec, len(related), animalVideos1, animal0)
	if err != nil {
		return err
	}

	animal0.R.AnimalVideos = append(animal0.R.AnimalVideos, animalVideos1...)

	for _, rel := range related {
		rel.R.Animal = animal0
	}

	return nil
}

func insertAnimalColors0(ctx context.Context, exec bob.Executor, colors1 []*ColorSetter, animal0 *Animal) (ColorSlice, error) {
	for i := range colors1 {
		colors1[i].AnimalID = omitnull.From(animal0.ID)
	}

	ret, err := Colors.Insert(bob.ToMods(colors1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAnimalColors0: %w", err)
	}

	return ret, nil
}

func attachAnimalColors0(ctx context.Context, exec bob.Executor, count int, colors1 ColorSlice, animal0 *Animal) (ColorSlice, error) {
	setter := &ColorSetter{
		AnimalID: omitnull.From(animal0.ID),
	}

	err := colors1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAnimalColors0: %w", err)
	}

	return colors1, nil
}

func (animal0 *Animal) InsertColors(ctx context.Context, exec bob.Executor, related ...*ColorSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	colors1, err := insertAnimalColors0(ctx, exec, related, animal0)
	if err != nil {
		return err
	}

	animal0.R.Colors = append(animal0.R.Colors, colors1...)

	for _, rel := range colors1 {
		rel.R.Animal = animal0
	}
	return nil
}

func (animal0 *Animal) AttachColors(ctx context.Context, exec bob.Executor, related ...*Color) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	colors1 := ColorSlice(related)

	_, err = attachAnimalColors0(ctx, exec, len(related), colors1, animal0)
	if err != nil {
		return err
	}

	animal0.R.Colors = append(animal0.R.Colors, colors1...)

	for _, rel := range related {
		rel.R.Animal = animal0
	}

	return nil
}

func insertAnimalContacts0(ctx context.Context, exec bob.Executor, contacts1 []*ContactSetter, animal0 *Animal) (ContactSlice, error) {
	for i := range contacts1 {
		contacts1[i].AnimalID = omitnull.From(animal0.ID)
	}

	ret, err := Contacts.Insert(bob.ToMods(contacts1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAnimalContacts0: %w", err)
	}

	return ret, nil
}

func attachAnimalContacts0(ctx context.Context, exec bob.Executor, count int, contacts1 ContactSlice, animal0 *Animal) (ContactSlice, error) {
	setter := &ContactSetter{
		AnimalID: omitnull.From(animal0.ID),
	}

	err := contacts1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAnimalContacts0: %w", err)
	}

	return contacts1, nil
}

func (animal0 *Animal) InsertContacts(ctx context.Context, exec bob.Executor, related ...*ContactSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	contacts1, err := insertAnimalContacts0(ctx, exec, related, animal0)
	if err != nil {
		return err
	}

	animal0.R.Contacts = append(animal0.R.Contacts, contacts1...)

	for _, rel := range contacts1 {
		rel.R.Animal = animal0
	}
	return nil
}

func (animal0 *Animal) AttachContacts(ctx context.Context, exec bob.Executor, related ...*Contact) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	contacts1 := ContactSlice(related)

	_, err = attachAnimalContacts0(ctx, exec, len(related), contacts1, animal0)
	if err != nil {
		return err
	}

	animal0.R.Contacts = append(animal0.R.Contacts, contacts1...)

	for _, rel := range related {
		rel.R.Animal = animal0
	}

	return nil
}

func insertAnimalMicrochip0(ctx context.Context, exec bob.Executor, microchip1 *MicrochipSetter, animal0 *Animal) (*Microchip, error) {
	microchip1.AnimalID = omitnull.From(animal0.ID)

	ret, err := Microchips.Insert(microchip1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAnimalMicrochip0: %w", err)
	}

	return ret, nil
}

func attachAnimalMicrochip0(ctx context.Context, exec bob.Executor, count int, microchip1 *Microchip, animal0 *Animal) (*Microchip, error) {
	setter := &MicrochipSetter{
		AnimalID: omitnull.From(animal0.ID),
	}

	err := microchip1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAnimalMicrochip0: %w", err)
	}

	return microchip1, nil
}

func (animal0 *Animal) InsertMicrochip(ctx context.Context, exec bob.Executor, related *MicrochipSetter) error {
	microchip1, err := insertAnimalMicrochip0(ctx, exec, related, animal0)
	if err != nil {
		return err
	}

	animal0.R.Microchip = microchip1

	microchip1.R.Animal = animal0

	return nil
}

func (animal0 *Animal) AttachMicrochip(ctx context.Context, exec bob.Executor, microchip1 *Microchip) error {
	var err error

	_, err = attachAnimalMicrochip0(ctx, exec, 1, microchip1, animal0)
	if err != nil {
		return err
	}

	animal0.R.Microchip = microchip1

	microchip1.R.Animal = animal0

	return nil
}

func insertAnimalTags0(ctx context.Context, exec bob.Executor, tags1 []*TagSetter, animal0 *Animal) (TagSlice, error) {
	for i := range tags1 {
		tags1[i].AnimalID = omitnull.From(animal0.ID)
	}

	ret, err := Tags.Insert(bob.ToMods(tags1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAnimalTags0: %w", err)
	}

	return ret, nil
}

func attachAnimalTags0(ctx context.Context, exec bob.Executor, count int, tags1 TagSlice, animal0 *Animal) (TagSlice, error) {
	setter := &TagSetter{
		AnimalID: omitnull.From(animal0.ID),
	}

	err := tags1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAnimalTags0: %w", err)
	}

	return tags1, nil
}

func (animal0 *Animal) InsertTags(ctx context.Context, exec bob.Executor, related ...*TagSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	tags1, err := insertAnimalTags0(ctx, exec, related, animal0)
	if err != nil {
		return err
	}

	animal0.R.Tags = append(animal0.R.Tags, tags1...)

	for _, rel := range tags1 {
		rel.R.Animal = animal0
	}
	return nil
}

func (animal0 *Animal) AttachTags(ctx context.Context, exec bob.Executor, related ...*Tag) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	tags1 := TagSlice(related)

	_, err = attachAnimalTags0(ctx, exec, len(related), tags1, animal0)
	if err != nil {
		return err
	}

	animal0.R.Tags = append(animal0.R.Tags, tags1...)

	for _, rel := range related {
		rel.R.Animal = animal0
	}

	return nil
}

func insertAnimalUserAnimalLikes0(ctx context.Context, exec bob.Executor, userAnimalLikes1 []*UserAnimalLikeSetter, animal0 *Animal) (UserAnimalLikeSlice, error) {
	for i := range userAnimalLikes1 {
		userAnimalLikes1[i].AnimalID = omit.From(animal0.ID)
	}

	ret, err := UserAnimalLikes.Insert(bob.ToMods(userAnimalLikes1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAnimalUserAnimalLikes0: %w", err)
	}

	return ret, nil
}

func attachAnimalUserAnimalLikes0(ctx context.Context, exec bob.Executor, count int, userAnimalLikes1 UserAnimalLikeSlice, animal0 *Animal) (UserAnimalLikeSlice, error) {
	setter := &UserAnimalLikeSetter{
		AnimalID: omit.From(animal0.ID),
	}

	err := userAnimalLikes1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAnimalUserAnimalLikes0: %w", err)
	}

	return userAnimalLikes1, nil
}

func (animal0 *Animal) InsertUserAnimalLikes(ctx context.Context, exec bob.Executor, related ...*UserAnimalLikeSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	userAnimalLikes1, err := insertAnimalUserAnimalLikes0(ctx, exec, related, animal0)
	if err != nil {
		return err
	}

	animal0.R.UserAnimalLikes = append(animal0.R.UserAnimalLikes, userAnimalLikes1...)

	for _, rel := range userAnimalLikes1 {
		rel.R.Animal = animal0
	}
	return nil
}

func (animal0 *Animal) AttachUserAnimalLikes(ctx context.Context, exec bob.Executor, related ...*UserAnimalLike) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	userAnimalLikes1 := UserAnimalLikeSlice(related)

	_, err = attachAnimalUserAnimalLikes0(ctx, exec, len(related), userAnimalLikes1, animal0)
	if err != nil {
		return err
	}

	animal0.R.UserAnimalLikes = append(animal0.R.UserAnimalLikes, userAnimalLikes1...)

	for _, rel := range related {
		rel.R.Animal = animal0
	}

	return nil
}
