// Code generated by BobGen psql v0.38.1-0.20250722094724-08202428a120. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// AnimalPhoto is an object representing the database table.
type AnimalPhoto struct {
	ID        int64            `db:"id,pk,generated" `
	AnimalID  null.Val[int64]  `db:"animal_id" `
	Small     null.Val[string] `db:"small" `
	Medium    null.Val[string] `db:"medium" `
	Large     null.Val[string] `db:"large" `
	Full      null.Val[string] `db:"full" `
	CreatedAt time.Time        `db:"created_at" `
	UpdatedAt time.Time        `db:"updated_at" `

	R animalPhotoR `db:"-" `
}

// AnimalPhotoSlice is an alias for a slice of pointers to AnimalPhoto.
// This should almost always be used instead of []*AnimalPhoto.
type AnimalPhotoSlice []*AnimalPhoto

// AnimalPhotos contains methods to work with the animal_photo table
var AnimalPhotos = psql.NewTablex[*AnimalPhoto, AnimalPhotoSlice, *AnimalPhotoSetter]("", "animal_photo")

// AnimalPhotosQuery is a query on the animal_photo table
type AnimalPhotosQuery = *psql.ViewQuery[*AnimalPhoto, AnimalPhotoSlice]

// animalPhotoR is where relationships are stored.
type animalPhotoR struct {
	Animal *Animal // animal_photo.fk_animal_photo_animal_id_animal
}

type animalPhotoColumnNames struct {
	ID        string
	AnimalID  string
	Small     string
	Medium    string
	Large     string
	Full      string
	CreatedAt string
	UpdatedAt string
}

var AnimalPhotoColumns = buildAnimalPhotoColumns("animal_photo")

type animalPhotoColumns struct {
	tableAlias string
	ID         psql.Expression
	AnimalID   psql.Expression
	Small      psql.Expression
	Medium     psql.Expression
	Large      psql.Expression
	Full       psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c animalPhotoColumns) Alias() string {
	return c.tableAlias
}

func (animalPhotoColumns) AliasedAs(alias string) animalPhotoColumns {
	return buildAnimalPhotoColumns(alias)
}

func buildAnimalPhotoColumns(alias string) animalPhotoColumns {
	return animalPhotoColumns{
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		AnimalID:   psql.Quote(alias, "animal_id"),
		Small:      psql.Quote(alias, "small"),
		Medium:     psql.Quote(alias, "medium"),
		Large:      psql.Quote(alias, "large"),
		Full:       psql.Quote(alias, "full"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type animalPhotoWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, int64]
	AnimalID  psql.WhereNullMod[Q, int64]
	Small     psql.WhereNullMod[Q, string]
	Medium    psql.WhereNullMod[Q, string]
	Large     psql.WhereNullMod[Q, string]
	Full      psql.WhereNullMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (animalPhotoWhere[Q]) AliasedAs(alias string) animalPhotoWhere[Q] {
	return buildAnimalPhotoWhere[Q](buildAnimalPhotoColumns(alias))
}

func buildAnimalPhotoWhere[Q psql.Filterable](cols animalPhotoColumns) animalPhotoWhere[Q] {
	return animalPhotoWhere[Q]{
		ID:        psql.Where[Q, int64](cols.ID),
		AnimalID:  psql.WhereNull[Q, int64](cols.AnimalID),
		Small:     psql.WhereNull[Q, string](cols.Small),
		Medium:    psql.WhereNull[Q, string](cols.Medium),
		Large:     psql.WhereNull[Q, string](cols.Large),
		Full:      psql.WhereNull[Q, string](cols.Full),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

var AnimalPhotoErrors = &animalPhotoErrors{
	ErrUniqueAnimalPhotoPkey: &UniqueConstraintError{
		schema:  "",
		table:   "animal_photo",
		columns: []string{"id"},
		s:       "animal_photo_pkey",
	},
}

type animalPhotoErrors struct {
	ErrUniqueAnimalPhotoPkey *UniqueConstraintError
}

// AnimalPhotoSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type AnimalPhotoSetter struct {
	AnimalID  omitnull.Val[int64]  `db:"animal_id" `
	Small     omitnull.Val[string] `db:"small" `
	Medium    omitnull.Val[string] `db:"medium" `
	Large     omitnull.Val[string] `db:"large" `
	Full      omitnull.Val[string] `db:"full" `
	CreatedAt omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt omit.Val[time.Time]  `db:"updated_at" `
}

func (s AnimalPhotoSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if !s.AnimalID.IsUnset() {
		vals = append(vals, "animal_id")
	}
	if !s.Small.IsUnset() {
		vals = append(vals, "small")
	}
	if !s.Medium.IsUnset() {
		vals = append(vals, "medium")
	}
	if !s.Large.IsUnset() {
		vals = append(vals, "large")
	}
	if !s.Full.IsUnset() {
		vals = append(vals, "full")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s AnimalPhotoSetter) Overwrite(t *AnimalPhoto) {
	if !s.AnimalID.IsUnset() {
		t.AnimalID = s.AnimalID.MustGetNull()
	}
	if !s.Small.IsUnset() {
		t.Small = s.Small.MustGetNull()
	}
	if !s.Medium.IsUnset() {
		t.Medium = s.Medium.MustGetNull()
	}
	if !s.Large.IsUnset() {
		t.Large = s.Large.MustGetNull()
	}
	if !s.Full.IsUnset() {
		t.Full = s.Full.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *AnimalPhotoSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return AnimalPhotos.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 7)
		if !s.AnimalID.IsUnset() {
			vals[0] = psql.Arg(s.AnimalID.MustGetNull())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if !s.Small.IsUnset() {
			vals[1] = psql.Arg(s.Small.MustGetNull())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if !s.Medium.IsUnset() {
			vals[2] = psql.Arg(s.Medium.MustGetNull())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.Large.IsUnset() {
			vals[3] = psql.Arg(s.Large.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.Full.IsUnset() {
			vals[4] = psql.Arg(s.Full.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[5] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[6] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s AnimalPhotoSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s AnimalPhotoSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if !s.AnimalID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "animal_id")...),
			psql.Arg(s.AnimalID),
		}})
	}

	if !s.Small.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "small")...),
			psql.Arg(s.Small),
		}})
	}

	if !s.Medium.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "medium")...),
			psql.Arg(s.Medium),
		}})
	}

	if !s.Large.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "large")...),
			psql.Arg(s.Large),
		}})
	}

	if !s.Full.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "full")...),
			psql.Arg(s.Full),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindAnimalPhoto retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAnimalPhoto(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*AnimalPhoto, error) {
	if len(cols) == 0 {
		return AnimalPhotos.Query(
			SelectWhere.AnimalPhotos.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return AnimalPhotos.Query(
		SelectWhere.AnimalPhotos.ID.EQ(IDPK),
		sm.Columns(AnimalPhotos.Columns().Only(cols...)),
	).One(ctx, exec)
}

// AnimalPhotoExists checks the presence of a single record by primary key
func AnimalPhotoExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return AnimalPhotos.Query(
		SelectWhere.AnimalPhotos.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after AnimalPhoto is retrieved from the database
func (o *AnimalPhoto) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = AnimalPhotos.AfterSelectHooks.RunHooks(ctx, exec, AnimalPhotoSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = AnimalPhotos.AfterInsertHooks.RunHooks(ctx, exec, AnimalPhotoSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = AnimalPhotos.AfterUpdateHooks.RunHooks(ctx, exec, AnimalPhotoSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = AnimalPhotos.AfterDeleteHooks.RunHooks(ctx, exec, AnimalPhotoSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the AnimalPhoto
func (o *AnimalPhoto) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *AnimalPhoto) pkEQ() dialect.Expression {
	return psql.Quote("animal_photo", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the AnimalPhoto
func (o *AnimalPhoto) Update(ctx context.Context, exec bob.Executor, s *AnimalPhotoSetter) error {
	v, err := AnimalPhotos.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single AnimalPhoto record with an executor
func (o *AnimalPhoto) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := AnimalPhotos.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the AnimalPhoto using the executor
func (o *AnimalPhoto) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := AnimalPhotos.Query(
		SelectWhere.AnimalPhotos.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after AnimalPhotoSlice is retrieved from the database
func (o AnimalPhotoSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = AnimalPhotos.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = AnimalPhotos.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = AnimalPhotos.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = AnimalPhotos.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o AnimalPhotoSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("animal_photo", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o AnimalPhotoSlice) copyMatchingRows(from ...*AnimalPhoto) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o AnimalPhotoSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return AnimalPhotos.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *AnimalPhoto:
				o.copyMatchingRows(retrieved)
			case []*AnimalPhoto:
				o.copyMatchingRows(retrieved...)
			case AnimalPhotoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a AnimalPhoto or a slice of AnimalPhoto
				// then run the AfterUpdateHooks on the slice
				_, err = AnimalPhotos.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o AnimalPhotoSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return AnimalPhotos.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *AnimalPhoto:
				o.copyMatchingRows(retrieved)
			case []*AnimalPhoto:
				o.copyMatchingRows(retrieved...)
			case AnimalPhotoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a AnimalPhoto or a slice of AnimalPhoto
				// then run the AfterDeleteHooks on the slice
				_, err = AnimalPhotos.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o AnimalPhotoSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals AnimalPhotoSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := AnimalPhotos.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o AnimalPhotoSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := AnimalPhotos.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o AnimalPhotoSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := AnimalPhotos.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type animalPhotoJoins[Q dialect.Joinable] struct {
	typ    string
	Animal modAs[Q, animalColumns]
}

func (j animalPhotoJoins[Q]) aliasedAs(alias string) animalPhotoJoins[Q] {
	return buildAnimalPhotoJoins[Q](buildAnimalPhotoColumns(alias), j.typ)
}

func buildAnimalPhotoJoins[Q dialect.Joinable](cols animalPhotoColumns, typ string) animalPhotoJoins[Q] {
	return animalPhotoJoins[Q]{
		typ: typ,
		Animal: modAs[Q, animalColumns]{
			c: AnimalColumns,
			f: func(to animalColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Animals.Name().As(to.Alias())).On(
						to.ID.EQ(cols.AnimalID),
					))
				}

				return mods
			},
		},
	}
}

// Animal starts a query for related objects on animal
func (o *AnimalPhoto) Animal(mods ...bob.Mod[*dialect.SelectQuery]) AnimalsQuery {
	return Animals.Query(append(mods,
		sm.Where(AnimalColumns.ID.EQ(psql.Arg(o.AnimalID))),
	)...)
}

func (os AnimalPhotoSlice) Animal(mods ...bob.Mod[*dialect.SelectQuery]) AnimalsQuery {
	pkAnimalID := make(pgtypes.Array[null.Val[int64]], len(os))
	for i, o := range os {
		pkAnimalID[i] = o.AnimalID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkAnimalID), "bigint[]")),
	))

	return Animals.Query(append(mods,
		sm.Where(psql.Group(AnimalColumns.ID).OP("IN", PKArgExpr)),
	)...)
}

func (o *AnimalPhoto) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Animal":
		rel, ok := retrieved.(*Animal)
		if !ok {
			return fmt.Errorf("animalPhoto cannot load %T as %q", retrieved, name)
		}

		o.R.Animal = rel

		if rel != nil {
			rel.R.AnimalPhotos = AnimalPhotoSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("animalPhoto has no relationship %q", name)
	}
}

type animalPhotoPreloader struct {
	Animal func(...psql.PreloadOption) psql.Preloader
}

func buildAnimalPhotoPreloader() animalPhotoPreloader {
	return animalPhotoPreloader{
		Animal: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Animal, AnimalSlice](orm.Relationship{
				Name: "Animal",
				Sides: []orm.RelSide{
					{
						From: TableNames.AnimalPhotos,
						To:   TableNames.Animals,
						FromColumns: []string{
							ColumnNames.AnimalPhotos.AnimalID,
						},
						ToColumns: []string{
							ColumnNames.Animals.ID,
						},
					},
				},
			}, Animals.Columns().Names(), opts...)
		},
	}
}

type animalPhotoThenLoader[Q orm.Loadable] struct {
	Animal func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildAnimalPhotoThenLoader[Q orm.Loadable]() animalPhotoThenLoader[Q] {
	type AnimalLoadInterface interface {
		LoadAnimal(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return animalPhotoThenLoader[Q]{
		Animal: thenLoadBuilder[Q](
			"Animal",
			func(ctx context.Context, exec bob.Executor, retrieved AnimalLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAnimal(ctx, exec, mods...)
			},
		),
	}
}

// LoadAnimal loads the animalPhoto's Animal into the .R struct
func (o *AnimalPhoto) LoadAnimal(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Animal = nil

	related, err := o.Animal(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.AnimalPhotos = AnimalPhotoSlice{o}

	o.R.Animal = related
	return nil
}

// LoadAnimal loads the animalPhoto's Animal into the .R struct
func (os AnimalPhotoSlice) LoadAnimal(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	animals, err := os.Animal(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range animals {
			if !o.AnimalID.IsValue() {
				continue
			}

			if o.AnimalID.MustGet() != rel.ID {
				continue
			}

			rel.R.AnimalPhotos = append(rel.R.AnimalPhotos, o)

			o.R.Animal = rel
			break
		}
	}

	return nil
}

func attachAnimalPhotoAnimal0(ctx context.Context, exec bob.Executor, count int, animalPhoto0 *AnimalPhoto, animal1 *Animal) (*AnimalPhoto, error) {
	setter := &AnimalPhotoSetter{
		AnimalID: omitnull.From(animal1.ID),
	}

	err := animalPhoto0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAnimalPhotoAnimal0: %w", err)
	}

	return animalPhoto0, nil
}

func (animalPhoto0 *AnimalPhoto) InsertAnimal(ctx context.Context, exec bob.Executor, related *AnimalSetter) error {
	animal1, err := Animals.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachAnimalPhotoAnimal0(ctx, exec, 1, animalPhoto0, animal1)
	if err != nil {
		return err
	}

	animalPhoto0.R.Animal = animal1

	animal1.R.AnimalPhotos = append(animal1.R.AnimalPhotos, animalPhoto0)

	return nil
}

func (animalPhoto0 *AnimalPhoto) AttachAnimal(ctx context.Context, exec bob.Executor, animal1 *Animal) error {
	var err error

	_, err = attachAnimalPhotoAnimal0(ctx, exec, 1, animalPhoto0, animal1)
	if err != nil {
		return err
	}

	animalPhoto0.R.Animal = animal1

	animal1.R.AnimalPhotos = append(animal1.R.AnimalPhotos, animalPhoto0)

	return nil
}
