// Code generated by BobGen psql v0.38.1-0.20250722094724-08202428a120. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// AnimalVideo is an object representing the database table.
type AnimalVideo struct {
	ID       int64            `db:"id,pk,generated" `
	AnimalID null.Val[int64]  `db:"animal_id" `
	URL      null.Val[string] `db:"url" `

	R animalVideoR `db:"-" `
}

// AnimalVideoSlice is an alias for a slice of pointers to AnimalVideo.
// This should almost always be used instead of []*AnimalVideo.
type AnimalVideoSlice []*AnimalVideo

// AnimalVideos contains methods to work with the animal_video table
var AnimalVideos = psql.NewTablex[*AnimalVideo, AnimalVideoSlice, *AnimalVideoSetter]("", "animal_video")

// AnimalVideosQuery is a query on the animal_video table
type AnimalVideosQuery = *psql.ViewQuery[*AnimalVideo, AnimalVideoSlice]

// animalVideoR is where relationships are stored.
type animalVideoR struct {
	Animal *Animal // animal_video.fk_animal_video_animal_id_animal
}

type animalVideoColumnNames struct {
	ID       string
	AnimalID string
	URL      string
}

var AnimalVideoColumns = buildAnimalVideoColumns("animal_video")

type animalVideoColumns struct {
	tableAlias string
	ID         psql.Expression
	AnimalID   psql.Expression
	URL        psql.Expression
}

func (c animalVideoColumns) Alias() string {
	return c.tableAlias
}

func (animalVideoColumns) AliasedAs(alias string) animalVideoColumns {
	return buildAnimalVideoColumns(alias)
}

func buildAnimalVideoColumns(alias string) animalVideoColumns {
	return animalVideoColumns{
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		AnimalID:   psql.Quote(alias, "animal_id"),
		URL:        psql.Quote(alias, "url"),
	}
}

type animalVideoWhere[Q psql.Filterable] struct {
	ID       psql.WhereMod[Q, int64]
	AnimalID psql.WhereNullMod[Q, int64]
	URL      psql.WhereNullMod[Q, string]
}

func (animalVideoWhere[Q]) AliasedAs(alias string) animalVideoWhere[Q] {
	return buildAnimalVideoWhere[Q](buildAnimalVideoColumns(alias))
}

func buildAnimalVideoWhere[Q psql.Filterable](cols animalVideoColumns) animalVideoWhere[Q] {
	return animalVideoWhere[Q]{
		ID:       psql.Where[Q, int64](cols.ID),
		AnimalID: psql.WhereNull[Q, int64](cols.AnimalID),
		URL:      psql.WhereNull[Q, string](cols.URL),
	}
}

var AnimalVideoErrors = &animalVideoErrors{
	ErrUniqueAnimalVideoPkey: &UniqueConstraintError{
		schema:  "",
		table:   "animal_video",
		columns: []string{"id"},
		s:       "animal_video_pkey",
	},
}

type animalVideoErrors struct {
	ErrUniqueAnimalVideoPkey *UniqueConstraintError
}

// AnimalVideoSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type AnimalVideoSetter struct {
	AnimalID omitnull.Val[int64]  `db:"animal_id" `
	URL      omitnull.Val[string] `db:"url" `
}

func (s AnimalVideoSetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if !s.AnimalID.IsUnset() {
		vals = append(vals, "animal_id")
	}
	if !s.URL.IsUnset() {
		vals = append(vals, "url")
	}
	return vals
}

func (s AnimalVideoSetter) Overwrite(t *AnimalVideo) {
	if !s.AnimalID.IsUnset() {
		t.AnimalID = s.AnimalID.MustGetNull()
	}
	if !s.URL.IsUnset() {
		t.URL = s.URL.MustGetNull()
	}
}

func (s *AnimalVideoSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return AnimalVideos.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 2)
		if !s.AnimalID.IsUnset() {
			vals[0] = psql.Arg(s.AnimalID.MustGetNull())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if !s.URL.IsUnset() {
			vals[1] = psql.Arg(s.URL.MustGetNull())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s AnimalVideoSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s AnimalVideoSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if !s.AnimalID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "animal_id")...),
			psql.Arg(s.AnimalID),
		}})
	}

	if !s.URL.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "url")...),
			psql.Arg(s.URL),
		}})
	}

	return exprs
}

// FindAnimalVideo retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAnimalVideo(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*AnimalVideo, error) {
	if len(cols) == 0 {
		return AnimalVideos.Query(
			SelectWhere.AnimalVideos.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return AnimalVideos.Query(
		SelectWhere.AnimalVideos.ID.EQ(IDPK),
		sm.Columns(AnimalVideos.Columns().Only(cols...)),
	).One(ctx, exec)
}

// AnimalVideoExists checks the presence of a single record by primary key
func AnimalVideoExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return AnimalVideos.Query(
		SelectWhere.AnimalVideos.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after AnimalVideo is retrieved from the database
func (o *AnimalVideo) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = AnimalVideos.AfterSelectHooks.RunHooks(ctx, exec, AnimalVideoSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = AnimalVideos.AfterInsertHooks.RunHooks(ctx, exec, AnimalVideoSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = AnimalVideos.AfterUpdateHooks.RunHooks(ctx, exec, AnimalVideoSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = AnimalVideos.AfterDeleteHooks.RunHooks(ctx, exec, AnimalVideoSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the AnimalVideo
func (o *AnimalVideo) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *AnimalVideo) pkEQ() dialect.Expression {
	return psql.Quote("animal_video", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the AnimalVideo
func (o *AnimalVideo) Update(ctx context.Context, exec bob.Executor, s *AnimalVideoSetter) error {
	v, err := AnimalVideos.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single AnimalVideo record with an executor
func (o *AnimalVideo) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := AnimalVideos.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the AnimalVideo using the executor
func (o *AnimalVideo) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := AnimalVideos.Query(
		SelectWhere.AnimalVideos.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after AnimalVideoSlice is retrieved from the database
func (o AnimalVideoSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = AnimalVideos.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = AnimalVideos.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = AnimalVideos.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = AnimalVideos.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o AnimalVideoSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("animal_video", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o AnimalVideoSlice) copyMatchingRows(from ...*AnimalVideo) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o AnimalVideoSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return AnimalVideos.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *AnimalVideo:
				o.copyMatchingRows(retrieved)
			case []*AnimalVideo:
				o.copyMatchingRows(retrieved...)
			case AnimalVideoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a AnimalVideo or a slice of AnimalVideo
				// then run the AfterUpdateHooks on the slice
				_, err = AnimalVideos.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o AnimalVideoSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return AnimalVideos.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *AnimalVideo:
				o.copyMatchingRows(retrieved)
			case []*AnimalVideo:
				o.copyMatchingRows(retrieved...)
			case AnimalVideoSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a AnimalVideo or a slice of AnimalVideo
				// then run the AfterDeleteHooks on the slice
				_, err = AnimalVideos.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o AnimalVideoSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals AnimalVideoSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := AnimalVideos.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o AnimalVideoSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := AnimalVideos.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o AnimalVideoSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := AnimalVideos.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type animalVideoJoins[Q dialect.Joinable] struct {
	typ    string
	Animal modAs[Q, animalColumns]
}

func (j animalVideoJoins[Q]) aliasedAs(alias string) animalVideoJoins[Q] {
	return buildAnimalVideoJoins[Q](buildAnimalVideoColumns(alias), j.typ)
}

func buildAnimalVideoJoins[Q dialect.Joinable](cols animalVideoColumns, typ string) animalVideoJoins[Q] {
	return animalVideoJoins[Q]{
		typ: typ,
		Animal: modAs[Q, animalColumns]{
			c: AnimalColumns,
			f: func(to animalColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Animals.Name().As(to.Alias())).On(
						to.ID.EQ(cols.AnimalID),
					))
				}

				return mods
			},
		},
	}
}

// Animal starts a query for related objects on animal
func (o *AnimalVideo) Animal(mods ...bob.Mod[*dialect.SelectQuery]) AnimalsQuery {
	return Animals.Query(append(mods,
		sm.Where(AnimalColumns.ID.EQ(psql.Arg(o.AnimalID))),
	)...)
}

func (os AnimalVideoSlice) Animal(mods ...bob.Mod[*dialect.SelectQuery]) AnimalsQuery {
	pkAnimalID := make(pgtypes.Array[null.Val[int64]], len(os))
	for i, o := range os {
		pkAnimalID[i] = o.AnimalID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkAnimalID), "bigint[]")),
	))

	return Animals.Query(append(mods,
		sm.Where(psql.Group(AnimalColumns.ID).OP("IN", PKArgExpr)),
	)...)
}

func (o *AnimalVideo) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Animal":
		rel, ok := retrieved.(*Animal)
		if !ok {
			return fmt.Errorf("animalVideo cannot load %T as %q", retrieved, name)
		}

		o.R.Animal = rel

		if rel != nil {
			rel.R.AnimalVideos = AnimalVideoSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("animalVideo has no relationship %q", name)
	}
}

type animalVideoPreloader struct {
	Animal func(...psql.PreloadOption) psql.Preloader
}

func buildAnimalVideoPreloader() animalVideoPreloader {
	return animalVideoPreloader{
		Animal: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Animal, AnimalSlice](orm.Relationship{
				Name: "Animal",
				Sides: []orm.RelSide{
					{
						From: TableNames.AnimalVideos,
						To:   TableNames.Animals,
						FromColumns: []string{
							ColumnNames.AnimalVideos.AnimalID,
						},
						ToColumns: []string{
							ColumnNames.Animals.ID,
						},
					},
				},
			}, Animals.Columns().Names(), opts...)
		},
	}
}

type animalVideoThenLoader[Q orm.Loadable] struct {
	Animal func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildAnimalVideoThenLoader[Q orm.Loadable]() animalVideoThenLoader[Q] {
	type AnimalLoadInterface interface {
		LoadAnimal(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return animalVideoThenLoader[Q]{
		Animal: thenLoadBuilder[Q](
			"Animal",
			func(ctx context.Context, exec bob.Executor, retrieved AnimalLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAnimal(ctx, exec, mods...)
			},
		),
	}
}

// LoadAnimal loads the animalVideo's Animal into the .R struct
func (o *AnimalVideo) LoadAnimal(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Animal = nil

	related, err := o.Animal(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.AnimalVideos = AnimalVideoSlice{o}

	o.R.Animal = related
	return nil
}

// LoadAnimal loads the animalVideo's Animal into the .R struct
func (os AnimalVideoSlice) LoadAnimal(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	animals, err := os.Animal(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range animals {
			if !o.AnimalID.IsValue() {
				continue
			}

			if o.AnimalID.MustGet() != rel.ID {
				continue
			}

			rel.R.AnimalVideos = append(rel.R.AnimalVideos, o)

			o.R.Animal = rel
			break
		}
	}

	return nil
}

func attachAnimalVideoAnimal0(ctx context.Context, exec bob.Executor, count int, animalVideo0 *AnimalVideo, animal1 *Animal) (*AnimalVideo, error) {
	setter := &AnimalVideoSetter{
		AnimalID: omitnull.From(animal1.ID),
	}

	err := animalVideo0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAnimalVideoAnimal0: %w", err)
	}

	return animalVideo0, nil
}

func (animalVideo0 *AnimalVideo) InsertAnimal(ctx context.Context, exec bob.Executor, related *AnimalSetter) error {
	animal1, err := Animals.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachAnimalVideoAnimal0(ctx, exec, 1, animalVideo0, animal1)
	if err != nil {
		return err
	}

	animalVideo0.R.Animal = animal1

	animal1.R.AnimalVideos = append(animal1.R.AnimalVideos, animalVideo0)

	return nil
}

func (animalVideo0 *AnimalVideo) AttachAnimal(ctx context.Context, exec bob.Executor, animal1 *Animal) error {
	var err error

	_, err = attachAnimalVideoAnimal0(ctx, exec, 1, animalVideo0, animal1)
	if err != nil {
		return err
	}

	animalVideo0.R.Animal = animal1

	animal1.R.AnimalVideos = append(animal1.R.AnimalVideos, animalVideo0)

	return nil
}
