// Code generated by BobGen psql v0.38.1-0.20250722094724-08202428a120. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model_test

import (
	"context"
	"errors"
	"testing"

	models "github.com/dankobg/fluffly/db/model"
	factory "github.com/dankobg/fluffly/db/model/factory"
	"github.com/stephenafamo/bob"
)

func TestMicrochipUniqueConstraintErrors(t *testing.T) {
	if testDB == nil {
		t.Skip("No database connection provided")
	}

	f := factory.New()
	tests := []struct {
		name         string
		expectedErr  *models.UniqueConstraintError
		conflictMods func(context.Context, bob.Executor, *models.Microchip) factory.MicrochipModSlice
	}{
		{
			name:        "ErrUniqueMicrochipPkey",
			expectedErr: models.MicrochipErrors.ErrUniqueMicrochipPkey,
			conflictMods: func(ctx context.Context, exec bob.Executor, obj *models.Microchip) factory.MicrochipModSlice {
				shouldUpdate := false
				updateMods := make(factory.MicrochipModSlice, 0, 1)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewMicrochipWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.MicrochipModSlice{
					factory.MicrochipMods.ID(obj.ID),
				}
			},
		},
		{
			name:        "ErrUniqueUqMicrochipAnimal",
			expectedErr: models.MicrochipErrors.ErrUniqueUqMicrochipAnimal,
			conflictMods: func(ctx context.Context, exec bob.Executor, obj *models.Microchip) factory.MicrochipModSlice {
				shouldUpdate := false
				updateMods := make(factory.MicrochipModSlice, 0, 1)

				if !obj.AnimalID.IsValue() {
					shouldUpdate = true
					updateMods = append(updateMods, factory.MicrochipMods.RandomAnimalIDNotNull(nil))
				}

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewMicrochipWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.MicrochipModSlice{
					factory.MicrochipMods.AnimalID(obj.AnimalID),
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancel := context.WithCancel(t.Context())
			t.Cleanup(cancel)

			tx, err := testDB.Begin(ctx)
			if err != nil {
				t.Fatalf("Couldn't start database transaction: %v", err)
			}

			defer func() {
				if err := tx.Rollback(ctx); err != nil {
					t.Fatalf("Error rolling back transaction: %v", err)
				}
			}()

			var exec bob.Executor = tx

			obj, err := f.NewMicrochipWithContext(ctx, factory.MicrochipMods.WithParentsCascading()).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			obj2, err := f.NewMicrochipWithContext(ctx).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			err = obj2.Update(ctx, exec, f.NewMicrochipWithContext(ctx, tt.conflictMods(ctx, exec, obj)...).BuildSetter())
			if !errors.Is(models.ErrUniqueConstraint, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !errors.Is(tt.expectedErr, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
			if !models.ErrUniqueConstraint.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !tt.expectedErr.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
		})
	}
}
