// Code generated by BobGen psql v0.38.1-0.20250722094724-08202428a120. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Organization is an object representing the database table.
type Organization struct {
	ID               int64            `db:"id,pk,generated" `
	Name             string           `db:"name" `
	Email            string           `db:"email" `
	Phone            string           `db:"phone" `
	Address1         null.Val[string] `db:"address1" `
	Address2         null.Val[string] `db:"address2" `
	City             null.Val[string] `db:"city" `
	State            null.Val[string] `db:"state" `
	Postcode         null.Val[string] `db:"postcode" `
	Country          null.Val[string] `db:"country" `
	URL              null.Val[string] `db:"url" `
	Website          null.Val[string] `db:"website" `
	MissionStatement null.Val[string] `db:"mission_statement" `
	AdoptionPolicy   null.Val[string] `db:"adoption_policy" `
	AdoptionURL      null.Val[string] `db:"adoption_url" `
	Distance         null.Val[string] `db:"distance" `
	Facebook         null.Val[string] `db:"facebook" `
	Twitter          null.Val[string] `db:"twitter" `
	Youtube          null.Val[string] `db:"youtube" `
	Instagram        null.Val[string] `db:"instagram" `
	Pinterest        null.Val[string] `db:"pinterest" `

	R organizationR `db:"-" `
}

// OrganizationSlice is an alias for a slice of pointers to Organization.
// This should almost always be used instead of []*Organization.
type OrganizationSlice []*Organization

// Organizations contains methods to work with the organization table
var Organizations = psql.NewTablex[*Organization, OrganizationSlice, *OrganizationSetter]("", "organization")

// OrganizationsQuery is a query on the organization table
type OrganizationsQuery = *psql.ViewQuery[*Organization, OrganizationSlice]

// organizationR is where relationships are stored.
type organizationR struct {
	Animals            AnimalSlice            // animal.fk_animal_organization_id_user
	OrganizationHours  OrganizationHourSlice  // organization_hour.fk_organization_hour_organization_id_organization
	OrganizationPhotos OrganizationPhotoSlice // organization_photo.fk_organization_photo_organization_id_animal
}

type organizationColumnNames struct {
	ID               string
	Name             string
	Email            string
	Phone            string
	Address1         string
	Address2         string
	City             string
	State            string
	Postcode         string
	Country          string
	URL              string
	Website          string
	MissionStatement string
	AdoptionPolicy   string
	AdoptionURL      string
	Distance         string
	Facebook         string
	Twitter          string
	Youtube          string
	Instagram        string
	Pinterest        string
}

var OrganizationColumns = buildOrganizationColumns("organization")

type organizationColumns struct {
	tableAlias       string
	ID               psql.Expression
	Name             psql.Expression
	Email            psql.Expression
	Phone            psql.Expression
	Address1         psql.Expression
	Address2         psql.Expression
	City             psql.Expression
	State            psql.Expression
	Postcode         psql.Expression
	Country          psql.Expression
	URL              psql.Expression
	Website          psql.Expression
	MissionStatement psql.Expression
	AdoptionPolicy   psql.Expression
	AdoptionURL      psql.Expression
	Distance         psql.Expression
	Facebook         psql.Expression
	Twitter          psql.Expression
	Youtube          psql.Expression
	Instagram        psql.Expression
	Pinterest        psql.Expression
}

func (c organizationColumns) Alias() string {
	return c.tableAlias
}

func (organizationColumns) AliasedAs(alias string) organizationColumns {
	return buildOrganizationColumns(alias)
}

func buildOrganizationColumns(alias string) organizationColumns {
	return organizationColumns{
		tableAlias:       alias,
		ID:               psql.Quote(alias, "id"),
		Name:             psql.Quote(alias, "name"),
		Email:            psql.Quote(alias, "email"),
		Phone:            psql.Quote(alias, "phone"),
		Address1:         psql.Quote(alias, "address1"),
		Address2:         psql.Quote(alias, "address2"),
		City:             psql.Quote(alias, "city"),
		State:            psql.Quote(alias, "state"),
		Postcode:         psql.Quote(alias, "postcode"),
		Country:          psql.Quote(alias, "country"),
		URL:              psql.Quote(alias, "url"),
		Website:          psql.Quote(alias, "website"),
		MissionStatement: psql.Quote(alias, "mission_statement"),
		AdoptionPolicy:   psql.Quote(alias, "adoption_policy"),
		AdoptionURL:      psql.Quote(alias, "adoption_url"),
		Distance:         psql.Quote(alias, "distance"),
		Facebook:         psql.Quote(alias, "facebook"),
		Twitter:          psql.Quote(alias, "twitter"),
		Youtube:          psql.Quote(alias, "youtube"),
		Instagram:        psql.Quote(alias, "instagram"),
		Pinterest:        psql.Quote(alias, "pinterest"),
	}
}

type organizationWhere[Q psql.Filterable] struct {
	ID               psql.WhereMod[Q, int64]
	Name             psql.WhereMod[Q, string]
	Email            psql.WhereMod[Q, string]
	Phone            psql.WhereMod[Q, string]
	Address1         psql.WhereNullMod[Q, string]
	Address2         psql.WhereNullMod[Q, string]
	City             psql.WhereNullMod[Q, string]
	State            psql.WhereNullMod[Q, string]
	Postcode         psql.WhereNullMod[Q, string]
	Country          psql.WhereNullMod[Q, string]
	URL              psql.WhereNullMod[Q, string]
	Website          psql.WhereNullMod[Q, string]
	MissionStatement psql.WhereNullMod[Q, string]
	AdoptionPolicy   psql.WhereNullMod[Q, string]
	AdoptionURL      psql.WhereNullMod[Q, string]
	Distance         psql.WhereNullMod[Q, string]
	Facebook         psql.WhereNullMod[Q, string]
	Twitter          psql.WhereNullMod[Q, string]
	Youtube          psql.WhereNullMod[Q, string]
	Instagram        psql.WhereNullMod[Q, string]
	Pinterest        psql.WhereNullMod[Q, string]
}

func (organizationWhere[Q]) AliasedAs(alias string) organizationWhere[Q] {
	return buildOrganizationWhere[Q](buildOrganizationColumns(alias))
}

func buildOrganizationWhere[Q psql.Filterable](cols organizationColumns) organizationWhere[Q] {
	return organizationWhere[Q]{
		ID:               psql.Where[Q, int64](cols.ID),
		Name:             psql.Where[Q, string](cols.Name),
		Email:            psql.Where[Q, string](cols.Email),
		Phone:            psql.Where[Q, string](cols.Phone),
		Address1:         psql.WhereNull[Q, string](cols.Address1),
		Address2:         psql.WhereNull[Q, string](cols.Address2),
		City:             psql.WhereNull[Q, string](cols.City),
		State:            psql.WhereNull[Q, string](cols.State),
		Postcode:         psql.WhereNull[Q, string](cols.Postcode),
		Country:          psql.WhereNull[Q, string](cols.Country),
		URL:              psql.WhereNull[Q, string](cols.URL),
		Website:          psql.WhereNull[Q, string](cols.Website),
		MissionStatement: psql.WhereNull[Q, string](cols.MissionStatement),
		AdoptionPolicy:   psql.WhereNull[Q, string](cols.AdoptionPolicy),
		AdoptionURL:      psql.WhereNull[Q, string](cols.AdoptionURL),
		Distance:         psql.WhereNull[Q, string](cols.Distance),
		Facebook:         psql.WhereNull[Q, string](cols.Facebook),
		Twitter:          psql.WhereNull[Q, string](cols.Twitter),
		Youtube:          psql.WhereNull[Q, string](cols.Youtube),
		Instagram:        psql.WhereNull[Q, string](cols.Instagram),
		Pinterest:        psql.WhereNull[Q, string](cols.Pinterest),
	}
}

var OrganizationErrors = &organizationErrors{
	ErrUniqueOrganizationPkey: &UniqueConstraintError{
		schema:  "",
		table:   "organization",
		columns: []string{"id"},
		s:       "organization_pkey",
	},
}

type organizationErrors struct {
	ErrUniqueOrganizationPkey *UniqueConstraintError
}

// OrganizationSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type OrganizationSetter struct {
	Name             omit.Val[string]     `db:"name" `
	Email            omit.Val[string]     `db:"email" `
	Phone            omit.Val[string]     `db:"phone" `
	Address1         omitnull.Val[string] `db:"address1" `
	Address2         omitnull.Val[string] `db:"address2" `
	City             omitnull.Val[string] `db:"city" `
	State            omitnull.Val[string] `db:"state" `
	Postcode         omitnull.Val[string] `db:"postcode" `
	Country          omitnull.Val[string] `db:"country" `
	URL              omitnull.Val[string] `db:"url" `
	Website          omitnull.Val[string] `db:"website" `
	MissionStatement omitnull.Val[string] `db:"mission_statement" `
	AdoptionPolicy   omitnull.Val[string] `db:"adoption_policy" `
	AdoptionURL      omitnull.Val[string] `db:"adoption_url" `
	Distance         omitnull.Val[string] `db:"distance" `
	Facebook         omitnull.Val[string] `db:"facebook" `
	Twitter          omitnull.Val[string] `db:"twitter" `
	Youtube          omitnull.Val[string] `db:"youtube" `
	Instagram        omitnull.Val[string] `db:"instagram" `
	Pinterest        omitnull.Val[string] `db:"pinterest" `
}

func (s OrganizationSetter) SetColumns() []string {
	vals := make([]string, 0, 20)
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Email.IsValue() {
		vals = append(vals, "email")
	}
	if s.Phone.IsValue() {
		vals = append(vals, "phone")
	}
	if !s.Address1.IsUnset() {
		vals = append(vals, "address1")
	}
	if !s.Address2.IsUnset() {
		vals = append(vals, "address2")
	}
	if !s.City.IsUnset() {
		vals = append(vals, "city")
	}
	if !s.State.IsUnset() {
		vals = append(vals, "state")
	}
	if !s.Postcode.IsUnset() {
		vals = append(vals, "postcode")
	}
	if !s.Country.IsUnset() {
		vals = append(vals, "country")
	}
	if !s.URL.IsUnset() {
		vals = append(vals, "url")
	}
	if !s.Website.IsUnset() {
		vals = append(vals, "website")
	}
	if !s.MissionStatement.IsUnset() {
		vals = append(vals, "mission_statement")
	}
	if !s.AdoptionPolicy.IsUnset() {
		vals = append(vals, "adoption_policy")
	}
	if !s.AdoptionURL.IsUnset() {
		vals = append(vals, "adoption_url")
	}
	if !s.Distance.IsUnset() {
		vals = append(vals, "distance")
	}
	if !s.Facebook.IsUnset() {
		vals = append(vals, "facebook")
	}
	if !s.Twitter.IsUnset() {
		vals = append(vals, "twitter")
	}
	if !s.Youtube.IsUnset() {
		vals = append(vals, "youtube")
	}
	if !s.Instagram.IsUnset() {
		vals = append(vals, "instagram")
	}
	if !s.Pinterest.IsUnset() {
		vals = append(vals, "pinterest")
	}
	return vals
}

func (s OrganizationSetter) Overwrite(t *Organization) {
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Email.IsValue() {
		t.Email = s.Email.MustGet()
	}
	if s.Phone.IsValue() {
		t.Phone = s.Phone.MustGet()
	}
	if !s.Address1.IsUnset() {
		t.Address1 = s.Address1.MustGetNull()
	}
	if !s.Address2.IsUnset() {
		t.Address2 = s.Address2.MustGetNull()
	}
	if !s.City.IsUnset() {
		t.City = s.City.MustGetNull()
	}
	if !s.State.IsUnset() {
		t.State = s.State.MustGetNull()
	}
	if !s.Postcode.IsUnset() {
		t.Postcode = s.Postcode.MustGetNull()
	}
	if !s.Country.IsUnset() {
		t.Country = s.Country.MustGetNull()
	}
	if !s.URL.IsUnset() {
		t.URL = s.URL.MustGetNull()
	}
	if !s.Website.IsUnset() {
		t.Website = s.Website.MustGetNull()
	}
	if !s.MissionStatement.IsUnset() {
		t.MissionStatement = s.MissionStatement.MustGetNull()
	}
	if !s.AdoptionPolicy.IsUnset() {
		t.AdoptionPolicy = s.AdoptionPolicy.MustGetNull()
	}
	if !s.AdoptionURL.IsUnset() {
		t.AdoptionURL = s.AdoptionURL.MustGetNull()
	}
	if !s.Distance.IsUnset() {
		t.Distance = s.Distance.MustGetNull()
	}
	if !s.Facebook.IsUnset() {
		t.Facebook = s.Facebook.MustGetNull()
	}
	if !s.Twitter.IsUnset() {
		t.Twitter = s.Twitter.MustGetNull()
	}
	if !s.Youtube.IsUnset() {
		t.Youtube = s.Youtube.MustGetNull()
	}
	if !s.Instagram.IsUnset() {
		t.Instagram = s.Instagram.MustGetNull()
	}
	if !s.Pinterest.IsUnset() {
		t.Pinterest = s.Pinterest.MustGetNull()
	}
}

func (s *OrganizationSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Organizations.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 20)
		if s.Name.IsValue() {
			vals[0] = psql.Arg(s.Name.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Email.IsValue() {
			vals[1] = psql.Arg(s.Email.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Phone.IsValue() {
			vals[2] = psql.Arg(s.Phone.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.Address1.IsUnset() {
			vals[3] = psql.Arg(s.Address1.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.Address2.IsUnset() {
			vals[4] = psql.Arg(s.Address2.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.City.IsUnset() {
			vals[5] = psql.Arg(s.City.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.State.IsUnset() {
			vals[6] = psql.Arg(s.State.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.Postcode.IsUnset() {
			vals[7] = psql.Arg(s.Postcode.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.Country.IsUnset() {
			vals[8] = psql.Arg(s.Country.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.URL.IsUnset() {
			vals[9] = psql.Arg(s.URL.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if !s.Website.IsUnset() {
			vals[10] = psql.Arg(s.Website.MustGetNull())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if !s.MissionStatement.IsUnset() {
			vals[11] = psql.Arg(s.MissionStatement.MustGetNull())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		if !s.AdoptionPolicy.IsUnset() {
			vals[12] = psql.Arg(s.AdoptionPolicy.MustGetNull())
		} else {
			vals[12] = psql.Raw("DEFAULT")
		}

		if !s.AdoptionURL.IsUnset() {
			vals[13] = psql.Arg(s.AdoptionURL.MustGetNull())
		} else {
			vals[13] = psql.Raw("DEFAULT")
		}

		if !s.Distance.IsUnset() {
			vals[14] = psql.Arg(s.Distance.MustGetNull())
		} else {
			vals[14] = psql.Raw("DEFAULT")
		}

		if !s.Facebook.IsUnset() {
			vals[15] = psql.Arg(s.Facebook.MustGetNull())
		} else {
			vals[15] = psql.Raw("DEFAULT")
		}

		if !s.Twitter.IsUnset() {
			vals[16] = psql.Arg(s.Twitter.MustGetNull())
		} else {
			vals[16] = psql.Raw("DEFAULT")
		}

		if !s.Youtube.IsUnset() {
			vals[17] = psql.Arg(s.Youtube.MustGetNull())
		} else {
			vals[17] = psql.Raw("DEFAULT")
		}

		if !s.Instagram.IsUnset() {
			vals[18] = psql.Arg(s.Instagram.MustGetNull())
		} else {
			vals[18] = psql.Raw("DEFAULT")
		}

		if !s.Pinterest.IsUnset() {
			vals[19] = psql.Arg(s.Pinterest.MustGetNull())
		} else {
			vals[19] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s OrganizationSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s OrganizationSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 20)

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Email.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if s.Phone.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "phone")...),
			psql.Arg(s.Phone),
		}})
	}

	if !s.Address1.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "address1")...),
			psql.Arg(s.Address1),
		}})
	}

	if !s.Address2.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "address2")...),
			psql.Arg(s.Address2),
		}})
	}

	if !s.City.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "city")...),
			psql.Arg(s.City),
		}})
	}

	if !s.State.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "state")...),
			psql.Arg(s.State),
		}})
	}

	if !s.Postcode.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "postcode")...),
			psql.Arg(s.Postcode),
		}})
	}

	if !s.Country.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "country")...),
			psql.Arg(s.Country),
		}})
	}

	if !s.URL.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "url")...),
			psql.Arg(s.URL),
		}})
	}

	if !s.Website.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "website")...),
			psql.Arg(s.Website),
		}})
	}

	if !s.MissionStatement.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "mission_statement")...),
			psql.Arg(s.MissionStatement),
		}})
	}

	if !s.AdoptionPolicy.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "adoption_policy")...),
			psql.Arg(s.AdoptionPolicy),
		}})
	}

	if !s.AdoptionURL.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "adoption_url")...),
			psql.Arg(s.AdoptionURL),
		}})
	}

	if !s.Distance.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "distance")...),
			psql.Arg(s.Distance),
		}})
	}

	if !s.Facebook.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "facebook")...),
			psql.Arg(s.Facebook),
		}})
	}

	if !s.Twitter.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "twitter")...),
			psql.Arg(s.Twitter),
		}})
	}

	if !s.Youtube.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "youtube")...),
			psql.Arg(s.Youtube),
		}})
	}

	if !s.Instagram.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "instagram")...),
			psql.Arg(s.Instagram),
		}})
	}

	if !s.Pinterest.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "pinterest")...),
			psql.Arg(s.Pinterest),
		}})
	}

	return exprs
}

// FindOrganization retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindOrganization(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Organization, error) {
	if len(cols) == 0 {
		return Organizations.Query(
			SelectWhere.Organizations.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Organizations.Query(
		SelectWhere.Organizations.ID.EQ(IDPK),
		sm.Columns(Organizations.Columns().Only(cols...)),
	).One(ctx, exec)
}

// OrganizationExists checks the presence of a single record by primary key
func OrganizationExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Organizations.Query(
		SelectWhere.Organizations.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Organization is retrieved from the database
func (o *Organization) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Organizations.AfterSelectHooks.RunHooks(ctx, exec, OrganizationSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Organizations.AfterInsertHooks.RunHooks(ctx, exec, OrganizationSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Organizations.AfterUpdateHooks.RunHooks(ctx, exec, OrganizationSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Organizations.AfterDeleteHooks.RunHooks(ctx, exec, OrganizationSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Organization
func (o *Organization) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Organization) pkEQ() dialect.Expression {
	return psql.Quote("organization", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Organization
func (o *Organization) Update(ctx context.Context, exec bob.Executor, s *OrganizationSetter) error {
	v, err := Organizations.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Organization record with an executor
func (o *Organization) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Organizations.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Organization using the executor
func (o *Organization) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Organizations.Query(
		SelectWhere.Organizations.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after OrganizationSlice is retrieved from the database
func (o OrganizationSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Organizations.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Organizations.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Organizations.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Organizations.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o OrganizationSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("organization", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o OrganizationSlice) copyMatchingRows(from ...*Organization) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o OrganizationSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Organizations.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Organization:
				o.copyMatchingRows(retrieved)
			case []*Organization:
				o.copyMatchingRows(retrieved...)
			case OrganizationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Organization or a slice of Organization
				// then run the AfterUpdateHooks on the slice
				_, err = Organizations.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o OrganizationSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Organizations.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Organization:
				o.copyMatchingRows(retrieved)
			case []*Organization:
				o.copyMatchingRows(retrieved...)
			case OrganizationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Organization or a slice of Organization
				// then run the AfterDeleteHooks on the slice
				_, err = Organizations.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o OrganizationSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals OrganizationSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Organizations.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o OrganizationSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Organizations.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o OrganizationSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Organizations.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type organizationJoins[Q dialect.Joinable] struct {
	typ                string
	Animals            modAs[Q, animalColumns]
	OrganizationHours  modAs[Q, organizationHourColumns]
	OrganizationPhotos modAs[Q, organizationPhotoColumns]
}

func (j organizationJoins[Q]) aliasedAs(alias string) organizationJoins[Q] {
	return buildOrganizationJoins[Q](buildOrganizationColumns(alias), j.typ)
}

func buildOrganizationJoins[Q dialect.Joinable](cols organizationColumns, typ string) organizationJoins[Q] {
	return organizationJoins[Q]{
		typ: typ,
		Animals: modAs[Q, animalColumns]{
			c: AnimalColumns,
			f: func(to animalColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Animals.Name().As(to.Alias())).On(
						to.OrganizationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		OrganizationHours: modAs[Q, organizationHourColumns]{
			c: OrganizationHourColumns,
			f: func(to organizationHourColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, OrganizationHours.Name().As(to.Alias())).On(
						to.OrganizationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		OrganizationPhotos: modAs[Q, organizationPhotoColumns]{
			c: OrganizationPhotoColumns,
			f: func(to organizationPhotoColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, OrganizationPhotos.Name().As(to.Alias())).On(
						to.OrganizationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}

// Animals starts a query for related objects on animal
func (o *Organization) Animals(mods ...bob.Mod[*dialect.SelectQuery]) AnimalsQuery {
	return Animals.Query(append(mods,
		sm.Where(AnimalColumns.OrganizationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os OrganizationSlice) Animals(mods ...bob.Mod[*dialect.SelectQuery]) AnimalsQuery {
	pkID := make(pgtypes.Array[int64], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Animals.Query(append(mods,
		sm.Where(psql.Group(AnimalColumns.OrganizationID).OP("IN", PKArgExpr)),
	)...)
}

// OrganizationHours starts a query for related objects on organization_hour
func (o *Organization) OrganizationHours(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationHoursQuery {
	return OrganizationHours.Query(append(mods,
		sm.Where(OrganizationHourColumns.OrganizationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os OrganizationSlice) OrganizationHours(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationHoursQuery {
	pkID := make(pgtypes.Array[int64], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return OrganizationHours.Query(append(mods,
		sm.Where(psql.Group(OrganizationHourColumns.OrganizationID).OP("IN", PKArgExpr)),
	)...)
}

// OrganizationPhotos starts a query for related objects on organization_photo
func (o *Organization) OrganizationPhotos(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationPhotosQuery {
	return OrganizationPhotos.Query(append(mods,
		sm.Where(OrganizationPhotoColumns.OrganizationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os OrganizationSlice) OrganizationPhotos(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationPhotosQuery {
	pkID := make(pgtypes.Array[int64], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return OrganizationPhotos.Query(append(mods,
		sm.Where(psql.Group(OrganizationPhotoColumns.OrganizationID).OP("IN", PKArgExpr)),
	)...)
}

func (o *Organization) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Animals":
		rels, ok := retrieved.(AnimalSlice)
		if !ok {
			return fmt.Errorf("organization cannot load %T as %q", retrieved, name)
		}

		o.R.Animals = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Organization = o
			}
		}
		return nil
	case "OrganizationHours":
		rels, ok := retrieved.(OrganizationHourSlice)
		if !ok {
			return fmt.Errorf("organization cannot load %T as %q", retrieved, name)
		}

		o.R.OrganizationHours = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Organization = o
			}
		}
		return nil
	case "OrganizationPhotos":
		rels, ok := retrieved.(OrganizationPhotoSlice)
		if !ok {
			return fmt.Errorf("organization cannot load %T as %q", retrieved, name)
		}

		o.R.OrganizationPhotos = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Organization = o
			}
		}
		return nil
	default:
		return fmt.Errorf("organization has no relationship %q", name)
	}
}

type organizationPreloader struct{}

func buildOrganizationPreloader() organizationPreloader {
	return organizationPreloader{}
}

type organizationThenLoader[Q orm.Loadable] struct {
	Animals            func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	OrganizationHours  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	OrganizationPhotos func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildOrganizationThenLoader[Q orm.Loadable]() organizationThenLoader[Q] {
	type AnimalsLoadInterface interface {
		LoadAnimals(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrganizationHoursLoadInterface interface {
		LoadOrganizationHours(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrganizationPhotosLoadInterface interface {
		LoadOrganizationPhotos(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return organizationThenLoader[Q]{
		Animals: thenLoadBuilder[Q](
			"Animals",
			func(ctx context.Context, exec bob.Executor, retrieved AnimalsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAnimals(ctx, exec, mods...)
			},
		),
		OrganizationHours: thenLoadBuilder[Q](
			"OrganizationHours",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationHoursLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganizationHours(ctx, exec, mods...)
			},
		),
		OrganizationPhotos: thenLoadBuilder[Q](
			"OrganizationPhotos",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationPhotosLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganizationPhotos(ctx, exec, mods...)
			},
		),
	}
}

// LoadAnimals loads the organization's Animals into the .R struct
func (o *Organization) LoadAnimals(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Animals = nil

	related, err := o.Animals(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Organization = o
	}

	o.R.Animals = related
	return nil
}

// LoadAnimals loads the organization's Animals into the .R struct
func (os OrganizationSlice) LoadAnimals(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	animals, err := os.Animals(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.Animals = nil
	}

	for _, o := range os {
		for _, rel := range animals {

			if !rel.OrganizationID.IsValue() {
				continue
			}
			if o.ID != rel.OrganizationID.MustGet() {
				continue
			}

			rel.R.Organization = o

			o.R.Animals = append(o.R.Animals, rel)
		}
	}

	return nil
}

// LoadOrganizationHours loads the organization's OrganizationHours into the .R struct
func (o *Organization) LoadOrganizationHours(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OrganizationHours = nil

	related, err := o.OrganizationHours(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Organization = o
	}

	o.R.OrganizationHours = related
	return nil
}

// LoadOrganizationHours loads the organization's OrganizationHours into the .R struct
func (os OrganizationSlice) LoadOrganizationHours(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizationHours, err := os.OrganizationHours(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.OrganizationHours = nil
	}

	for _, o := range os {
		for _, rel := range organizationHours {

			if !rel.OrganizationID.IsValue() {
				continue
			}
			if o.ID != rel.OrganizationID.MustGet() {
				continue
			}

			rel.R.Organization = o

			o.R.OrganizationHours = append(o.R.OrganizationHours, rel)
		}
	}

	return nil
}

// LoadOrganizationPhotos loads the organization's OrganizationPhotos into the .R struct
func (o *Organization) LoadOrganizationPhotos(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OrganizationPhotos = nil

	related, err := o.OrganizationPhotos(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Organization = o
	}

	o.R.OrganizationPhotos = related
	return nil
}

// LoadOrganizationPhotos loads the organization's OrganizationPhotos into the .R struct
func (os OrganizationSlice) LoadOrganizationPhotos(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizationPhotos, err := os.OrganizationPhotos(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.OrganizationPhotos = nil
	}

	for _, o := range os {
		for _, rel := range organizationPhotos {

			if !rel.OrganizationID.IsValue() {
				continue
			}
			if o.ID != rel.OrganizationID.MustGet() {
				continue
			}

			rel.R.Organization = o

			o.R.OrganizationPhotos = append(o.R.OrganizationPhotos, rel)
		}
	}

	return nil
}

func insertOrganizationAnimals0(ctx context.Context, exec bob.Executor, animals1 []*AnimalSetter, organization0 *Organization) (AnimalSlice, error) {
	for i := range animals1 {
		animals1[i].OrganizationID = omitnull.From(organization0.ID)
	}

	ret, err := Animals.Insert(bob.ToMods(animals1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertOrganizationAnimals0: %w", err)
	}

	return ret, nil
}

func attachOrganizationAnimals0(ctx context.Context, exec bob.Executor, count int, animals1 AnimalSlice, organization0 *Organization) (AnimalSlice, error) {
	setter := &AnimalSetter{
		OrganizationID: omitnull.From(organization0.ID),
	}

	err := animals1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrganizationAnimals0: %w", err)
	}

	return animals1, nil
}

func (organization0 *Organization) InsertAnimals(ctx context.Context, exec bob.Executor, related ...*AnimalSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	animals1, err := insertOrganizationAnimals0(ctx, exec, related, organization0)
	if err != nil {
		return err
	}

	organization0.R.Animals = append(organization0.R.Animals, animals1...)

	for _, rel := range animals1 {
		rel.R.Organization = organization0
	}
	return nil
}

func (organization0 *Organization) AttachAnimals(ctx context.Context, exec bob.Executor, related ...*Animal) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	animals1 := AnimalSlice(related)

	_, err = attachOrganizationAnimals0(ctx, exec, len(related), animals1, organization0)
	if err != nil {
		return err
	}

	organization0.R.Animals = append(organization0.R.Animals, animals1...)

	for _, rel := range related {
		rel.R.Organization = organization0
	}

	return nil
}

func insertOrganizationOrganizationHours0(ctx context.Context, exec bob.Executor, organizationHours1 []*OrganizationHourSetter, organization0 *Organization) (OrganizationHourSlice, error) {
	for i := range organizationHours1 {
		organizationHours1[i].OrganizationID = omitnull.From(organization0.ID)
	}

	ret, err := OrganizationHours.Insert(bob.ToMods(organizationHours1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertOrganizationOrganizationHours0: %w", err)
	}

	return ret, nil
}

func attachOrganizationOrganizationHours0(ctx context.Context, exec bob.Executor, count int, organizationHours1 OrganizationHourSlice, organization0 *Organization) (OrganizationHourSlice, error) {
	setter := &OrganizationHourSetter{
		OrganizationID: omitnull.From(organization0.ID),
	}

	err := organizationHours1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrganizationOrganizationHours0: %w", err)
	}

	return organizationHours1, nil
}

func (organization0 *Organization) InsertOrganizationHours(ctx context.Context, exec bob.Executor, related ...*OrganizationHourSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	organizationHours1, err := insertOrganizationOrganizationHours0(ctx, exec, related, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationHours = append(organization0.R.OrganizationHours, organizationHours1...)

	for _, rel := range organizationHours1 {
		rel.R.Organization = organization0
	}
	return nil
}

func (organization0 *Organization) AttachOrganizationHours(ctx context.Context, exec bob.Executor, related ...*OrganizationHour) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	organizationHours1 := OrganizationHourSlice(related)

	_, err = attachOrganizationOrganizationHours0(ctx, exec, len(related), organizationHours1, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationHours = append(organization0.R.OrganizationHours, organizationHours1...)

	for _, rel := range related {
		rel.R.Organization = organization0
	}

	return nil
}

func insertOrganizationOrganizationPhotos0(ctx context.Context, exec bob.Executor, organizationPhotos1 []*OrganizationPhotoSetter, organization0 *Organization) (OrganizationPhotoSlice, error) {
	for i := range organizationPhotos1 {
		organizationPhotos1[i].OrganizationID = omitnull.From(organization0.ID)
	}

	ret, err := OrganizationPhotos.Insert(bob.ToMods(organizationPhotos1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertOrganizationOrganizationPhotos0: %w", err)
	}

	return ret, nil
}

func attachOrganizationOrganizationPhotos0(ctx context.Context, exec bob.Executor, count int, organizationPhotos1 OrganizationPhotoSlice, organization0 *Organization) (OrganizationPhotoSlice, error) {
	setter := &OrganizationPhotoSetter{
		OrganizationID: omitnull.From(organization0.ID),
	}

	err := organizationPhotos1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrganizationOrganizationPhotos0: %w", err)
	}

	return organizationPhotos1, nil
}

func (organization0 *Organization) InsertOrganizationPhotos(ctx context.Context, exec bob.Executor, related ...*OrganizationPhotoSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	organizationPhotos1, err := insertOrganizationOrganizationPhotos0(ctx, exec, related, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationPhotos = append(organization0.R.OrganizationPhotos, organizationPhotos1...)

	for _, rel := range organizationPhotos1 {
		rel.R.Organization = organization0
	}
	return nil
}

func (organization0 *Organization) AttachOrganizationPhotos(ctx context.Context, exec bob.Executor, related ...*OrganizationPhoto) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	organizationPhotos1 := OrganizationPhotoSlice(related)

	_, err = attachOrganizationOrganizationPhotos0(ctx, exec, len(related), organizationPhotos1, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationPhotos = append(organization0.R.OrganizationPhotos, organizationPhotos1...)

	for _, rel := range related {
		rel.R.Organization = organization0
	}

	return nil
}
