// Code generated by BobGen psql v0.38.1-0.20250722094724-08202428a120. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// User is an object representing the database table.
type User struct {
	ID        uuid.UUID `db:"id,pk" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `

	R userR `db:"-" `
}

// UserSlice is an alias for a slice of pointers to User.
// This should almost always be used instead of []*User.
type UserSlice []*User

// Users contains methods to work with the user table
var Users = psql.NewTablex[*User, UserSlice, *UserSetter]("", "user")

// UsersQuery is a query on the user table
type UsersQuery = *psql.ViewQuery[*User, UserSlice]

// userR is where relationships are stored.
type userR struct {
	Adoptions       AdoptionSlice       // adoption.fk_adoption_user_id_animal
	UserAnimalLikes UserAnimalLikeSlice // user_animal_like.fk_user_animal_like_user_id_user
}

type userColumnNames struct {
	ID        string
	CreatedAt string
	UpdatedAt string
}

var UserColumns = buildUserColumns("user")

type userColumns struct {
	tableAlias string
	ID         psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c userColumns) Alias() string {
	return c.tableAlias
}

func (userColumns) AliasedAs(alias string) userColumns {
	return buildUserColumns(alias)
}

func buildUserColumns(alias string) userColumns {
	return userColumns{
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type userWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, uuid.UUID]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (userWhere[Q]) AliasedAs(alias string) userWhere[Q] {
	return buildUserWhere[Q](buildUserColumns(alias))
}

func buildUserWhere[Q psql.Filterable](cols userColumns) userWhere[Q] {
	return userWhere[Q]{
		ID:        psql.Where[Q, uuid.UUID](cols.ID),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

var UserErrors = &userErrors{
	ErrUniqueUserPkey: &UniqueConstraintError{
		schema:  "",
		table:   "user",
		columns: []string{"id"},
		s:       "user_pkey",
	},
}

type userErrors struct {
	ErrUniqueUserPkey *UniqueConstraintError
}

// UserSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSetter struct {
	ID        omit.Val[uuid.UUID] `db:"id,pk" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s UserSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s UserSetter) Overwrite(t *User) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *UserSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Users.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 3)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[1] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[2] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindUser retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUser(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*User, error) {
	if len(cols) == 0 {
		return Users.Query(
			SelectWhere.Users.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return Users.Query(
		SelectWhere.Users.ID.EQ(IDPK),
		sm.Columns(Users.Columns().Only(cols...)),
	).One(ctx, exec)
}

// UserExists checks the presence of a single record by primary key
func UserExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Users.Query(
		SelectWhere.Users.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after User is retrieved from the database
func (o *User) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, UserSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, UserSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the User
func (o *User) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *User) pkEQ() dialect.Expression {
	return psql.Quote("user", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the User
func (o *User) Update(ctx context.Context, exec bob.Executor, s *UserSetter) error {
	v, err := Users.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single User record with an executor
func (o *User) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Users.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the User using the executor
func (o *User) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Users.Query(
		SelectWhere.Users.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSlice is retrieved from the database
func (o UserSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Users.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Users.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("user", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSlice) copyMatchingRows(from ...*User) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterUpdateHooks on the slice
				_, err = Users.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Users.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *User:
				o.copyMatchingRows(retrieved)
			case []*User:
				o.copyMatchingRows(retrieved...)
			case UserSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a User or a slice of User
				// then run the AfterDeleteHooks on the slice
				_, err = Users.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Users.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Users.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type userJoins[Q dialect.Joinable] struct {
	typ             string
	Adoptions       modAs[Q, adoptionColumns]
	UserAnimalLikes modAs[Q, userAnimalLikeColumns]
}

func (j userJoins[Q]) aliasedAs(alias string) userJoins[Q] {
	return buildUserJoins[Q](buildUserColumns(alias), j.typ)
}

func buildUserJoins[Q dialect.Joinable](cols userColumns, typ string) userJoins[Q] {
	return userJoins[Q]{
		typ: typ,
		Adoptions: modAs[Q, adoptionColumns]{
			c: AdoptionColumns,
			f: func(to adoptionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Adoptions.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		UserAnimalLikes: modAs[Q, userAnimalLikeColumns]{
			c: UserAnimalLikeColumns,
			f: func(to userAnimalLikeColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, UserAnimalLikes.Name().As(to.Alias())).On(
						to.UserID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}

// Adoptions starts a query for related objects on adoption
func (o *User) Adoptions(mods ...bob.Mod[*dialect.SelectQuery]) AdoptionsQuery {
	return Adoptions.Query(append(mods,
		sm.Where(AdoptionColumns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) Adoptions(mods ...bob.Mod[*dialect.SelectQuery]) AdoptionsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Adoptions.Query(append(mods,
		sm.Where(psql.Group(AdoptionColumns.UserID).OP("IN", PKArgExpr)),
	)...)
}

// UserAnimalLikes starts a query for related objects on user_animal_like
func (o *User) UserAnimalLikes(mods ...bob.Mod[*dialect.SelectQuery]) UserAnimalLikesQuery {
	return UserAnimalLikes.Query(append(mods,
		sm.Where(UserAnimalLikeColumns.UserID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os UserSlice) UserAnimalLikes(mods ...bob.Mod[*dialect.SelectQuery]) UserAnimalLikesQuery {
	pkID := make(pgtypes.Array[uuid.UUID], len(os))
	for i, o := range os {
		pkID[i] = o.ID
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return UserAnimalLikes.Query(append(mods,
		sm.Where(psql.Group(UserAnimalLikeColumns.UserID).OP("IN", PKArgExpr)),
	)...)
}

func (o *User) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Adoptions":
		rels, ok := retrieved.(AdoptionSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.Adoptions = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	case "UserAnimalLikes":
		rels, ok := retrieved.(UserAnimalLikeSlice)
		if !ok {
			return fmt.Errorf("user cannot load %T as %q", retrieved, name)
		}

		o.R.UserAnimalLikes = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.User = o
			}
		}
		return nil
	default:
		return fmt.Errorf("user has no relationship %q", name)
	}
}

type userPreloader struct{}

func buildUserPreloader() userPreloader {
	return userPreloader{}
}

type userThenLoader[Q orm.Loadable] struct {
	Adoptions       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UserAnimalLikes func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUserThenLoader[Q orm.Loadable]() userThenLoader[Q] {
	type AdoptionsLoadInterface interface {
		LoadAdoptions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserAnimalLikesLoadInterface interface {
		LoadUserAnimalLikes(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return userThenLoader[Q]{
		Adoptions: thenLoadBuilder[Q](
			"Adoptions",
			func(ctx context.Context, exec bob.Executor, retrieved AdoptionsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAdoptions(ctx, exec, mods...)
			},
		),
		UserAnimalLikes: thenLoadBuilder[Q](
			"UserAnimalLikes",
			func(ctx context.Context, exec bob.Executor, retrieved UserAnimalLikesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUserAnimalLikes(ctx, exec, mods...)
			},
		),
	}
}

// LoadAdoptions loads the user's Adoptions into the .R struct
func (o *User) LoadAdoptions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Adoptions = nil

	related, err := o.Adoptions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.Adoptions = related
	return nil
}

// LoadAdoptions loads the user's Adoptions into the .R struct
func (os UserSlice) LoadAdoptions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	adoptions, err := os.Adoptions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.Adoptions = nil
	}

	for _, o := range os {
		for _, rel := range adoptions {

			if !rel.UserID.IsValue() {
				continue
			}
			if o.ID != rel.UserID.MustGet() {
				continue
			}

			rel.R.User = o

			o.R.Adoptions = append(o.R.Adoptions, rel)
		}
	}

	return nil
}

// LoadUserAnimalLikes loads the user's UserAnimalLikes into the .R struct
func (o *User) LoadUserAnimalLikes(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UserAnimalLikes = nil

	related, err := o.UserAnimalLikes(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.User = o
	}

	o.R.UserAnimalLikes = related
	return nil
}

// LoadUserAnimalLikes loads the user's UserAnimalLikes into the .R struct
func (os UserSlice) LoadUserAnimalLikes(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	userAnimalLikes, err := os.UserAnimalLikes(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		o.R.UserAnimalLikes = nil
	}

	for _, o := range os {
		for _, rel := range userAnimalLikes {

			if o.ID != rel.UserID {
				continue
			}

			rel.R.User = o

			o.R.UserAnimalLikes = append(o.R.UserAnimalLikes, rel)
		}
	}

	return nil
}

func insertUserAdoptions0(ctx context.Context, exec bob.Executor, adoptions1 []*AdoptionSetter, user0 *User) (AdoptionSlice, error) {
	for i := range adoptions1 {
		adoptions1[i].UserID = omitnull.From(user0.ID)
	}

	ret, err := Adoptions.Insert(bob.ToMods(adoptions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserAdoptions0: %w", err)
	}

	return ret, nil
}

func attachUserAdoptions0(ctx context.Context, exec bob.Executor, count int, adoptions1 AdoptionSlice, user0 *User) (AdoptionSlice, error) {
	setter := &AdoptionSetter{
		UserID: omitnull.From(user0.ID),
	}

	err := adoptions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserAdoptions0: %w", err)
	}

	return adoptions1, nil
}

func (user0 *User) InsertAdoptions(ctx context.Context, exec bob.Executor, related ...*AdoptionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	adoptions1, err := insertUserAdoptions0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.Adoptions = append(user0.R.Adoptions, adoptions1...)

	for _, rel := range adoptions1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachAdoptions(ctx context.Context, exec bob.Executor, related ...*Adoption) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	adoptions1 := AdoptionSlice(related)

	_, err = attachUserAdoptions0(ctx, exec, len(related), adoptions1, user0)
	if err != nil {
		return err
	}

	user0.R.Adoptions = append(user0.R.Adoptions, adoptions1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}

func insertUserUserAnimalLikes0(ctx context.Context, exec bob.Executor, userAnimalLikes1 []*UserAnimalLikeSetter, user0 *User) (UserAnimalLikeSlice, error) {
	for i := range userAnimalLikes1 {
		userAnimalLikes1[i].UserID = omit.From(user0.ID)
	}

	ret, err := UserAnimalLikes.Insert(bob.ToMods(userAnimalLikes1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertUserUserAnimalLikes0: %w", err)
	}

	return ret, nil
}

func attachUserUserAnimalLikes0(ctx context.Context, exec bob.Executor, count int, userAnimalLikes1 UserAnimalLikeSlice, user0 *User) (UserAnimalLikeSlice, error) {
	setter := &UserAnimalLikeSetter{
		UserID: omit.From(user0.ID),
	}

	err := userAnimalLikes1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserUserAnimalLikes0: %w", err)
	}

	return userAnimalLikes1, nil
}

func (user0 *User) InsertUserAnimalLikes(ctx context.Context, exec bob.Executor, related ...*UserAnimalLikeSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	userAnimalLikes1, err := insertUserUserAnimalLikes0(ctx, exec, related, user0)
	if err != nil {
		return err
	}

	user0.R.UserAnimalLikes = append(user0.R.UserAnimalLikes, userAnimalLikes1...)

	for _, rel := range userAnimalLikes1 {
		rel.R.User = user0
	}
	return nil
}

func (user0 *User) AttachUserAnimalLikes(ctx context.Context, exec bob.Executor, related ...*UserAnimalLike) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	userAnimalLikes1 := UserAnimalLikeSlice(related)

	_, err = attachUserUserAnimalLikes0(ctx, exec, len(related), userAnimalLikes1, user0)
	if err != nil {
		return err
	}

	user0.R.UserAnimalLikes = append(user0.R.UserAnimalLikes, userAnimalLikes1...)

	for _, rel := range related {
		rel.R.User = user0
	}

	return nil
}
