-- +goose Up
-- +goose StatementBegin
create extension if not exists postgis;

create type "gender" as enum ('m', 'f');

create table "user" (
  "id" uuid not null,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_user_id" primary key ("id")
);

create table "country" (
  "id" bigint not null generated by default as identity,
  "name" text not null,
  "iso_alpha2" varchar(2) not null,
  "iso_alpha3" varchar(3) not null,
  "iso_numeric" varchar(3) not null,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_country_id" primary key ("id"),
  constraint "uq_country_name" unique ("name"),
  constraint "uq_country_iso_alpha2" unique ("iso_alpha2"),
  constraint "uq_country_iso_alpha3" unique ("iso_alpha3"),
  constraint "uq_country_iso_numeric" unique ("iso_numeric")
);

create table "address" (
  "id" bigint not null generated by default as identity,
  "country_id" bigint not null,
  "unit_number" varchar(255),
  "street_number" varchar(255),
  "street_address" varchar(255) not null,
  "city" varchar(255) not null,
  "region" varchar(255),
  "postal_code" varchar(50),
  "coords" geography(Point, 4326),
  "note" text,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_address_id" primary key ("id"),
  constraint "fk_address_country_id" foreign key ("country_id") references "country" ("id") on delete cascade
);

create index "idx_address_coords" on "address" using gist ("coords");

create table "user_contact" (
  "id" bigint not null generated by default as identity,
  "user_id" uuid not null,
  "address_id" bigint not null,
  "phone" varchar(30) not null,
  "email" text not null,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_user_contact_id" primary key ("id"),
  constraint "fk_user_contact_user_id" foreign key ("user_id") references "user" ("id") on delete cascade,
  constraint "fk_user_contact_address_id" foreign key ("address_id") references "address" ("id") on delete cascade,
  constraint "uq_user_contact_user_id" unique ("user_id")
);

create table "animal_type" (
  "id" bigint not null generated by default as identity,
  "name" varchar(100) not null,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_animal_type_id" primary key ("id"),
  constraint "uq_animal_type_name" unique ("name")
);

create table "animal_specie" (
  "id" bigint not null generated by default as identity,
  "animal_type_id" bigint not null,
  "name" varchar(255) not null,
  "properties_schema" jsonb,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_animal_specie_id" primary key ("id"),
  constraint "uq_animal_specie_animal_type_id" unique ("animal_type_id", "name"),
  constraint "fk_animal_specie_animal_type_id" foreign key ("animal_type_id") references "animal_type" ("id") on delete cascade
);

create table "breed" (
  "id" bigint not null generated by default as identity,
  "animal_specie_id" bigint not null,
  "name" varchar(255) not null,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_breed_id" primary key ("id"),
  constraint "uq_breed_animal_specie_id" unique ("animal_specie_id", "name"),
  constraint "fk_breed_animal_specie_id" foreign key ("animal_specie_id") references "animal_specie" ("id") on delete cascade
);

create table "organization" (
  "id" bigint not null generated by default as identity,
  "name" varchar(255) not null,
  "website" text,
  "mission_statement" text,
  "adoption_policy" text,
  "adoption_url" text,
  "distance" varchar(20),
  "status" varchar(30) not null default 'pending',
  "original_id" text,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_organization_id" primary key ("id"),
  constraint "uq_organization_name" unique ("name"),
  constraint "ck_organization_status_valid" check ("status" in ('pending', 'approved', 'rejected'))
);

create table "organization_contact" (
  "id" bigint not null generated by default as identity,
  "organization_id" bigint not null,
  "address_id" bigint not null,
  "phone" varchar(255) not null,
  "email" text not null,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_organization_contact_id" primary key ("id"),
  constraint "fk_organization_contact_organization_id" foreign key ("organization_id") references "organization" ("id") on delete cascade,
  constraint "fk_organization_contact_address_id" foreign key ("address_id") references "address" ("id") on delete cascade,
  constraint "uq_organizataion_contact_organization_id" unique ("organization_id")
);

create table "organization_social" (
  "id" bigint not null generated by default as identity,
  "organization_id" bigint not null,
  "platform" varchar(30) not null,
  "url" text not null,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_organization_social_id" primary key ("id"),
  constraint "uq_organization_social_organization_id_platform" unique ("organization_id", "platform"),
  constraint "fk_organization_social_organization_id" foreign key ("organization_id") references "organization" ("id") on delete cascade
);

create table "organization_work_hour" (
  "id" bigint not null generated by default as identity,
  "organization_id" bigint,
  "monday" varchar(255),
  "tuesday" varchar(255),
  "wednesday" varchar(255),
  "thursday" varchar(255),
  "friday" varchar(255),
  "saturday" varchar(255),
  "sunday" varchar(255),
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_organization_work_hour_id" primary key ("id"),
  constraint "uq_organization_work_hour_organization_id" unique ("organization_id"),
  constraint "fk_organization_work_hour_organization_id" foreign key ("organization_id") references "organization" ("id") on delete cascade,
  constraint "ck_organization_work_hour_provided" check (
    coalesce(
      nullif(trim(monday), ''), nullif(trim(tuesday), ''), nullif(trim(wednesday), ''),
      nullif(trim(thursday), ''), nullif(trim(friday), ''), nullif(trim(saturday), ''), nullif(trim(sunday), '')
    ) is not null
  )
);

create table "organization_photo" (
  "id" bigint not null generated by default as identity,
  "organization_id" bigint,
  "object_kind" varchar(30) not null default 'external',
  "object_ref_small" text,
  "object_ref_medium" text,
  "object_ref_large" text,
  "object_ref_full" text,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_organization_photo_id" primary key ("id"),
  constraint "fk_organization_photo_organization_id" foreign key ("organization_id") references "organization" ("id") on delete cascade
);

create table "organization_video" (
  "id" bigint not null generated by default as identity,
  "organization_id" bigint,
  "object_kind" varchar(30) not null default 'external',
  "object_ref" text not null,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_organization_video_id" primary key ("id"),
  constraint "fk_organization_video_organization_id" foreign key ("organization_id") references "organization" ("id") on delete cascade
);

create table "organization_membership" (
  "organization_id" bigint not null,
  "user_id" uuid not null,
  "role" varchar(30) not null default 'member',
  "status" varchar(30) not null default 'pending',
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_organization_membership_organization_id_user_id" primary key ("organization_id", "user_id"),
  constraint "fk_organization_membership_organization_id" foreign key ("organization_id") references "organization" ("id") on delete cascade,
  constraint "fk_organization_membership_user_id" foreign key ("user_id") references "user" ("id") on delete cascade,
  constraint "ck_organization_membership_role_valid" check ("role" in ('owner', 'admin', 'member', 'volunteer')),
  constraint "ck_organization_membership_status_valid" check ("status" in ('pending', 'approved', 'rejected'))
);

create table "organization_invitation" (
  "id" bigint not null generated by default as identity,
  "organization_id" bigint not null,
  "invited_by" uuid not null,
  "email" varchar(255) not null,
  "role" varchar(30) not null default 'member',
  "token" varchar(255) not null,
  "expires_at" timestamptz not null,
  "accepted_at" timestamptz,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_organization_invitation_id" primary key ("id"),
  constraint "fk_organization_invitation_organization_id" foreign key ("organization_id") references "organization" ("id") on delete cascade,
  constraint "fk_organization_invitation_invited_by" foreign key ("invited_by") references "user" ("id") on delete cascade,
  constraint "uq_organization_invitation_token" unique ("token"),
  constraint "ck_organization_invitation_role_valid" check ("role" in ('owner', 'admin', 'member', 'volunteer'))
);

create table "animal" (
  "id" bigint not null generated by default as identity,
  "user_id" uuid not null,
  "organization_id" bigint,
  "type_id" bigint not null,
  "specie_id" bigint not null,
  "name" varchar(255) not null,
  "gender" gender,
  "hermaphrodite" boolean not null default false,
  "age" varchar(20) not null,
  "size" varchar(20) not null,
  "image_object_kind" varchar(30) not null default 'external',
  "image_object_ref_small" text not null,
  "image_object_ref_medium" text not null,
  "image_object_ref_large" text not null,
  "image_object_ref_full" text not null,
  "description" text,
  "distance" varchar,
  "properties" jsonb,
  "status" varchar(30) not null default 'pending',
  "original_organization_id" text,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_animal_id" primary key ("id"),
  constraint "fk_animal_user_id" foreign key ("user_id") references "user" ("id") on delete set null,
  constraint "fk_animal_organization_id" foreign key ("organization_id") references "organization" ("id") on delete set null,
  constraint "ck_animal_age_valid" check ("age" in ('baby', 'young', 'adult', 'senior')),
  constraint "ck_animal_size_valid" check ("size" in ('small', 'medium', 'large')),
  constraint "ck_animal_status_valid" check ("status" in ('pending', 'rejected', 'adoptable', 'reserved', 'adopted'))
);

create table "animal_breed" (
  "animal_id" bigint,
  "breed_id" bigint,
  "primary" boolean not null default false,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_animal_breed_animal_id_breed_id" primary key ("animal_id", "breed_id"),
  constraint "fk_animal_breed_animal_id" foreign key ("animal_id") references "animal" ("id") on delete cascade,
  constraint "fk_animal_breed_breed_id" foreign key ("breed_id") references "breed" ("id") on delete cascade
);

create table user_animal_like (
  "user_id" uuid not null,
  "animal_id" bigint not null,
  "liked_at" timestamptz not null default current_timestamp,
  constraint "pk_user_animal_like_user_id_animal_id" primary key ("user_id", "animal_id"),
  constraint "fk_user_animal_like_user_id" foreign key ("user_id") references "user" ("id") on delete cascade,
  constraint "fk_user_animal_like_animal_id" foreign key ("animal_id") references "animal" ("id") on delete cascade
);

create table "animal_tag" (
  "id" bigint not null generated by default as identity,
  "animal_id" bigint,
  "name" varchar(255) not null,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_tag_id" primary key ("id"),
  constraint "fk_tag_animal_id" foreign key ("animal_id") references "animal" ("id") on delete cascade,
  constraint "uq_tag_animal_id_name" unique ("animal_id", "name")
);

create table "color" (
  "id" bigint not null generated by default as identity,
  "animal_id" bigint,
  "color" varchar(255) not null,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_color_id" primary key ("id"),
  constraint "fk_color_animal_id" foreign key ("animal_id") references "animal" ("id") on delete cascade
);

create table "microchip" (
  "id" bigint not null generated by default as identity,
  "animal_id" bigint,
  "number" varchar(30) not null,
  "brand" varchar(255),
  "description" text,
  "location" varchar(100),
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_microchip_id" primary key ("id"),
  constraint "uq_microchip_animal_id" unique ("animal_id"),
  constraint "fk_microchip_animal_id" foreign key ("animal_id") references "animal" ("id") on delete cascade
);

create table "animal_photo" (
  "id" bigint not null generated by default as identity,
  "animal_id" bigint,
  "object_kind" varchar(30) not null default 'external',
  "object_ref_small" text ,
  "object_ref_medium" text,
  "object_ref_large" text,
  "object_ref_full" text,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_animal_photo_id" primary key ("id"),
  constraint "fk_animal_photo_id_animal_id" foreign key ("animal_id") references "animal" ("id") on delete cascade
);

create table "animal_video" (
  "id" bigint not null generated by default as identity,
  "animal_id" bigint,
  "object_kind" varchar(30) not null default 'external',
  "object_ref" text not null,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_animal_video_id" primary key ("id"),
  constraint "fk_animal_video_animal_id" foreign key ("animal_id") references "animal" ("id") on delete cascade
);

create table "adoption" (
  "id" bigint not null generated by default as identity,
  "animal_id" bigint not null,
  "user_id" uuid not null,
  "organization_id" bigint,
  "status" varchar(30) not null default 'pending',
  "is_permanent" boolean not null default false,
  "adopted_at" timestamptz not null default current_timestamp,
  "returned_at" timestamptz,
  "note" text,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_adoption_id" primary key ("id"),
  constraint "fk_adoption_animal_id" foreign key ("animal_id") references "animal" ("id") on delete cascade,
  constraint "fk_adoption_user_id" foreign key ("user_id") references "user" ("id") on delete cascade,
  constraint "fk_adoption_organization_id" foreign key ("organization_id") references "organization" ("id") on delete cascade,
  constraint "ck_adoption_status_valid" check ("status" in ('pending', 'approved', 'rejected'))
);

create table "geocoding_result" (
  "id" bigint not null generated by default as identity,
  "query" text not null,
  "coords" geography(Point, 4326) not null,
  "created_at" timestamptz not null default current_timestamp,
  "updated_at" timestamptz not null default current_timestamp,
  constraint "pk_geocoding_result_id" primary key ("id")
);

create index "idx_geocoding_result_coords" on "geocoding_result" using gist ("coords");
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table if exists "user" cascade;
drop table if exists "country" cascade;
drop table if exists "address" cascade;
drop table if exists "user_contact" cascade;
drop table if exists "organization_contact" cascade;
drop table if exists "animal_type" cascade;
drop table if exists "breed" cascade;
drop table if exists "animal_specie" cascade;
drop table if exists "organization" cascade;
drop table if exists "organization_social" cascade;
drop table if exists "organization_work_hour" cascade;
drop table if exists "organization_photo" cascade;
drop table if exists "organization_video" cascade;
drop table if exists "animal" cascade;
drop table if exists "animal_breed" cascade;
drop table if exists "user_animal_like" cascade;
drop table if exists "animal_tag" cascade;
drop table if exists "color" cascade;
drop table if exists "microchip" cascade;
drop table if exists "animal_photo" cascade;
drop table if exists "animal_video" cascade;
drop table if exists "adoption" cascade;
drop table if exists "geocoding_result" cascade;
drop table if exists "organization_membership" cascade;
drop table if exists "organization_invitation" cascade;
drop type if exists "gender";
-- +goose StatementEnd
