version: "2"

linters:
  default: all
  disable:
    - dupl
  settings:
    funlen:
      # Checks the number of lines in a function.
      # If lower than 0, disable the check.
      # Default: 60
      lines: 120
      # Checks the number of statements in a function.
      # If lower than 0, disable the check.
      # Default: 40
      statements: -1
      # Ignore comments when counting lines.
      # Default: true
      ignore-comments: true
