// Code generated by BobGen psql v0.38.1-0.20250722094724-08202428a120. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omitnull"
	models "github.com/dankobg/fluffly/db/model"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type AnimalVideoMod interface {
	Apply(context.Context, *AnimalVideoTemplate)
}

type AnimalVideoModFunc func(context.Context, *AnimalVideoTemplate)

func (f AnimalVideoModFunc) Apply(ctx context.Context, n *AnimalVideoTemplate) {
	f(ctx, n)
}

type AnimalVideoModSlice []AnimalVideoMod

func (mods AnimalVideoModSlice) Apply(ctx context.Context, n *AnimalVideoTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// AnimalVideoTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type AnimalVideoTemplate struct {
	ID       func() int64
	AnimalID func() null.Val[int64]
	URL      func() null.Val[string]

	r animalVideoR
	f *Factory

	alreadyPersisted bool
}

type animalVideoR struct {
	Animal *animalVideoRAnimalR
}

type animalVideoRAnimalR struct {
	o *AnimalTemplate
}

// Apply mods to the AnimalVideoTemplate
func (o *AnimalVideoTemplate) Apply(ctx context.Context, mods ...AnimalVideoMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.AnimalVideo
// according to the relationships in the template. Nothing is inserted into the db
func (t AnimalVideoTemplate) setModelRels(o *models.AnimalVideo) {
	if t.r.Animal != nil {
		rel := t.r.Animal.o.Build()
		rel.R.AnimalVideos = append(rel.R.AnimalVideos, o)
		o.AnimalID = null.From(rel.ID) // h2
		o.R.Animal = rel
	}
}

// BuildSetter returns an *models.AnimalVideoSetter
// this does nothing with the relationship templates
func (o AnimalVideoTemplate) BuildSetter() *models.AnimalVideoSetter {
	m := &models.AnimalVideoSetter{}

	if o.AnimalID != nil {
		val := o.AnimalID()
		m.AnimalID = omitnull.FromNull(val)
	}
	if o.URL != nil {
		val := o.URL()
		m.URL = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.AnimalVideoSetter
// this does nothing with the relationship templates
func (o AnimalVideoTemplate) BuildManySetter(number int) []*models.AnimalVideoSetter {
	m := make([]*models.AnimalVideoSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.AnimalVideo
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AnimalVideoTemplate.Create
func (o AnimalVideoTemplate) Build() *models.AnimalVideo {
	m := &models.AnimalVideo{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.AnimalID != nil {
		m.AnimalID = o.AnimalID()
	}
	if o.URL != nil {
		m.URL = o.URL()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.AnimalVideoSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AnimalVideoTemplate.CreateMany
func (o AnimalVideoTemplate) BuildMany(number int) models.AnimalVideoSlice {
	m := make(models.AnimalVideoSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableAnimalVideo(m *models.AnimalVideoSetter) {
}

// insertOptRels creates and inserts any optional the relationships on *models.AnimalVideo
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *AnimalVideoTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.AnimalVideo) error {
	var err error

	isAnimalDone, _ := animalVideoRelAnimalCtx.Value(ctx)
	if !isAnimalDone && o.r.Animal != nil {
		ctx = animalVideoRelAnimalCtx.WithValue(ctx, true)
		if o.r.Animal.o.alreadyPersisted {
			m.R.Animal = o.r.Animal.o.Build()
		} else {
			var rel0 *models.Animal
			rel0, err = o.r.Animal.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachAnimal(ctx, exec, rel0)
			if err != nil {
				return err
			}
		}

	}

	return err
}

// Create builds a animalVideo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *AnimalVideoTemplate) Create(ctx context.Context, exec bob.Executor) (*models.AnimalVideo, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableAnimalVideo(opt)

	m, err := models.AnimalVideos.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a animalVideo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *AnimalVideoTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.AnimalVideo {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a animalVideo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *AnimalVideoTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.AnimalVideo {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple animalVideos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o AnimalVideoTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.AnimalVideoSlice, error) {
	var err error
	m := make(models.AnimalVideoSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple animalVideos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o AnimalVideoTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.AnimalVideoSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple animalVideos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o AnimalVideoTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.AnimalVideoSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// AnimalVideo has methods that act as mods for the AnimalVideoTemplate
var AnimalVideoMods animalVideoMods

type animalVideoMods struct{}

func (m animalVideoMods) RandomizeAllColumns(f *faker.Faker) AnimalVideoMod {
	return AnimalVideoModSlice{
		AnimalVideoMods.RandomID(f),
		AnimalVideoMods.RandomAnimalID(f),
		AnimalVideoMods.RandomURL(f),
	}
}

// Set the model columns to this value
func (m animalVideoMods) ID(val int64) AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m animalVideoMods) IDFunc(f func() int64) AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m animalVideoMods) UnsetID() AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m animalVideoMods) RandomID(f *faker.Faker) AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m animalVideoMods) AnimalID(val null.Val[int64]) AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.AnimalID = func() null.Val[int64] { return val }
	})
}

// Set the Column from the function
func (m animalVideoMods) AnimalIDFunc(f func() null.Val[int64]) AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.AnimalID = f
	})
}

// Clear any values for the column
func (m animalVideoMods) UnsetAnimalID() AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.AnimalID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m animalVideoMods) RandomAnimalID(f *faker.Faker) AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.AnimalID = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m animalVideoMods) RandomAnimalIDNotNull(f *faker.Faker) AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.AnimalID = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m animalVideoMods) URL(val null.Val[string]) AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.URL = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m animalVideoMods) URLFunc(f func() null.Val[string]) AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.URL = f
	})
}

// Clear any values for the column
func (m animalVideoMods) UnsetURL() AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.URL = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m animalVideoMods) RandomURL(f *faker.Faker) AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.URL = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m animalVideoMods) RandomURLNotNull(f *faker.Faker) AnimalVideoMod {
	return AnimalVideoModFunc(func(_ context.Context, o *AnimalVideoTemplate) {
		o.URL = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

func (m animalVideoMods) WithParentsCascading() AnimalVideoMod {
	return AnimalVideoModFunc(func(ctx context.Context, o *AnimalVideoTemplate) {
		if isDone, _ := animalVideoWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = animalVideoWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewAnimalWithContext(ctx, AnimalMods.WithParentsCascading())
			m.WithAnimal(related).Apply(ctx, o)
		}
	})
}

func (m animalVideoMods) WithAnimal(rel *AnimalTemplate) AnimalVideoMod {
	return AnimalVideoModFunc(func(ctx context.Context, o *AnimalVideoTemplate) {
		o.r.Animal = &animalVideoRAnimalR{
			o: rel,
		}
	})
}

func (m animalVideoMods) WithNewAnimal(mods ...AnimalMod) AnimalVideoMod {
	return AnimalVideoModFunc(func(ctx context.Context, o *AnimalVideoTemplate) {
		related := o.f.NewAnimalWithContext(ctx, mods...)

		m.WithAnimal(related).Apply(ctx, o)
	})
}

func (m animalVideoMods) WithExistingAnimal(em *models.Animal) AnimalVideoMod {
	return AnimalVideoModFunc(func(ctx context.Context, o *AnimalVideoTemplate) {
		o.r.Animal = &animalVideoRAnimalR{
			o: o.f.FromExistingAnimal(em),
		}
	})
}

func (m animalVideoMods) WithoutAnimal() AnimalVideoMod {
	return AnimalVideoModFunc(func(ctx context.Context, o *AnimalVideoTemplate) {
		o.r.Animal = nil
	})
}
