// Code generated by BobGen psql v0.38.1-0.20250722094724-08202428a120. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	models "github.com/dankobg/fluffly/db/model"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type AnimalBreedMod interface {
	Apply(context.Context, *AnimalBreedTemplate)
}

type AnimalBreedModFunc func(context.Context, *AnimalBreedTemplate)

func (f AnimalBreedModFunc) Apply(ctx context.Context, n *AnimalBreedTemplate) {
	f(ctx, n)
}

type AnimalBreedModSlice []AnimalBreedMod

func (mods AnimalBreedModSlice) Apply(ctx context.Context, n *AnimalBreedTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// AnimalBreedTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type AnimalBreedTemplate struct {
	AnimalID  func() int64
	BreedID   func() int64
	Primary   func() bool
	CreatedAt func() time.Time
	UpdatedAt func() time.Time

	r animalBreedR
	f *Factory

	alreadyPersisted bool
}

type animalBreedR struct {
	Animal *animalBreedRAnimalR
	Breed  *animalBreedRBreedR
}

type animalBreedRAnimalR struct {
	o *AnimalTemplate
}
type animalBreedRBreedR struct {
	o *BreedTemplate
}

// Apply mods to the AnimalBreedTemplate
func (o *AnimalBreedTemplate) Apply(ctx context.Context, mods ...AnimalBreedMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.AnimalBreed
// according to the relationships in the template. Nothing is inserted into the db
func (t AnimalBreedTemplate) setModelRels(o *models.AnimalBreed) {
	if t.r.Animal != nil {
		rel := t.r.Animal.o.Build()
		rel.R.AnimalBreeds = append(rel.R.AnimalBreeds, o)
		o.AnimalID = rel.ID // h2
		o.R.Animal = rel
	}

	if t.r.Breed != nil {
		rel := t.r.Breed.o.Build()
		rel.R.AnimalBreeds = append(rel.R.AnimalBreeds, o)
		o.BreedID = rel.ID // h2
		o.R.Breed = rel
	}
}

// BuildSetter returns an *models.AnimalBreedSetter
// this does nothing with the relationship templates
func (o AnimalBreedTemplate) BuildSetter() *models.AnimalBreedSetter {
	m := &models.AnimalBreedSetter{}

	if o.AnimalID != nil {
		val := o.AnimalID()
		m.AnimalID = omit.From(val)
	}
	if o.BreedID != nil {
		val := o.BreedID()
		m.BreedID = omit.From(val)
	}
	if o.Primary != nil {
		val := o.Primary()
		m.Primary = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.AnimalBreedSetter
// this does nothing with the relationship templates
func (o AnimalBreedTemplate) BuildManySetter(number int) []*models.AnimalBreedSetter {
	m := make([]*models.AnimalBreedSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.AnimalBreed
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AnimalBreedTemplate.Create
func (o AnimalBreedTemplate) Build() *models.AnimalBreed {
	m := &models.AnimalBreed{}

	if o.AnimalID != nil {
		m.AnimalID = o.AnimalID()
	}
	if o.BreedID != nil {
		m.BreedID = o.BreedID()
	}
	if o.Primary != nil {
		m.Primary = o.Primary()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.AnimalBreedSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use AnimalBreedTemplate.CreateMany
func (o AnimalBreedTemplate) BuildMany(number int) models.AnimalBreedSlice {
	m := make(models.AnimalBreedSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableAnimalBreed(m *models.AnimalBreedSetter) {
	if !(m.AnimalID.IsValue()) {
		val := random_int64(nil)
		m.AnimalID = omit.From(val)
	}
	if !(m.BreedID.IsValue()) {
		val := random_int64(nil)
		m.BreedID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.AnimalBreed
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *AnimalBreedTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.AnimalBreed) error {
	var err error

	return err
}

// Create builds a animalBreed and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *AnimalBreedTemplate) Create(ctx context.Context, exec bob.Executor) (*models.AnimalBreed, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableAnimalBreed(opt)

	if o.r.Animal == nil {
		AnimalBreedMods.WithNewAnimal().Apply(ctx, o)
	}

	var rel0 *models.Animal

	if o.r.Animal.o.alreadyPersisted {
		rel0 = o.r.Animal.o.Build()
	} else {
		rel0, err = o.r.Animal.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.AnimalID = omit.From(rel0.ID)

	if o.r.Breed == nil {
		AnimalBreedMods.WithNewBreed().Apply(ctx, o)
	}

	var rel1 *models.Breed

	if o.r.Breed.o.alreadyPersisted {
		rel1 = o.r.Breed.o.Build()
	} else {
		rel1, err = o.r.Breed.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.BreedID = omit.From(rel1.ID)

	m, err := models.AnimalBreeds.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Animal = rel0
	m.R.Breed = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a animalBreed and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *AnimalBreedTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.AnimalBreed {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a animalBreed and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *AnimalBreedTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.AnimalBreed {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple animalBreeds and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o AnimalBreedTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.AnimalBreedSlice, error) {
	var err error
	m := make(models.AnimalBreedSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple animalBreeds and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o AnimalBreedTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.AnimalBreedSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple animalBreeds and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o AnimalBreedTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.AnimalBreedSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// AnimalBreed has methods that act as mods for the AnimalBreedTemplate
var AnimalBreedMods animalBreedMods

type animalBreedMods struct{}

func (m animalBreedMods) RandomizeAllColumns(f *faker.Faker) AnimalBreedMod {
	return AnimalBreedModSlice{
		AnimalBreedMods.RandomAnimalID(f),
		AnimalBreedMods.RandomBreedID(f),
		AnimalBreedMods.RandomPrimary(f),
		AnimalBreedMods.RandomCreatedAt(f),
		AnimalBreedMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m animalBreedMods) AnimalID(val int64) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.AnimalID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m animalBreedMods) AnimalIDFunc(f func() int64) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.AnimalID = f
	})
}

// Clear any values for the column
func (m animalBreedMods) UnsetAnimalID() AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.AnimalID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m animalBreedMods) RandomAnimalID(f *faker.Faker) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.AnimalID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m animalBreedMods) BreedID(val int64) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.BreedID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m animalBreedMods) BreedIDFunc(f func() int64) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.BreedID = f
	})
}

// Clear any values for the column
func (m animalBreedMods) UnsetBreedID() AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.BreedID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m animalBreedMods) RandomBreedID(f *faker.Faker) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.BreedID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m animalBreedMods) Primary(val bool) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.Primary = func() bool { return val }
	})
}

// Set the Column from the function
func (m animalBreedMods) PrimaryFunc(f func() bool) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.Primary = f
	})
}

// Clear any values for the column
func (m animalBreedMods) UnsetPrimary() AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.Primary = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m animalBreedMods) RandomPrimary(f *faker.Faker) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.Primary = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m animalBreedMods) CreatedAt(val time.Time) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m animalBreedMods) CreatedAtFunc(f func() time.Time) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m animalBreedMods) UnsetCreatedAt() AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m animalBreedMods) RandomCreatedAt(f *faker.Faker) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m animalBreedMods) UpdatedAt(val time.Time) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m animalBreedMods) UpdatedAtFunc(f func() time.Time) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m animalBreedMods) UnsetUpdatedAt() AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m animalBreedMods) RandomUpdatedAt(f *faker.Faker) AnimalBreedMod {
	return AnimalBreedModFunc(func(_ context.Context, o *AnimalBreedTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m animalBreedMods) WithParentsCascading() AnimalBreedMod {
	return AnimalBreedModFunc(func(ctx context.Context, o *AnimalBreedTemplate) {
		if isDone, _ := animalBreedWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = animalBreedWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewAnimalWithContext(ctx, AnimalMods.WithParentsCascading())
			m.WithAnimal(related).Apply(ctx, o)
		}
		{

			related := o.f.NewBreedWithContext(ctx, BreedMods.WithParentsCascading())
			m.WithBreed(related).Apply(ctx, o)
		}
	})
}

func (m animalBreedMods) WithAnimal(rel *AnimalTemplate) AnimalBreedMod {
	return AnimalBreedModFunc(func(ctx context.Context, o *AnimalBreedTemplate) {
		o.r.Animal = &animalBreedRAnimalR{
			o: rel,
		}
	})
}

func (m animalBreedMods) WithNewAnimal(mods ...AnimalMod) AnimalBreedMod {
	return AnimalBreedModFunc(func(ctx context.Context, o *AnimalBreedTemplate) {
		related := o.f.NewAnimalWithContext(ctx, mods...)

		m.WithAnimal(related).Apply(ctx, o)
	})
}

func (m animalBreedMods) WithExistingAnimal(em *models.Animal) AnimalBreedMod {
	return AnimalBreedModFunc(func(ctx context.Context, o *AnimalBreedTemplate) {
		o.r.Animal = &animalBreedRAnimalR{
			o: o.f.FromExistingAnimal(em),
		}
	})
}

func (m animalBreedMods) WithoutAnimal() AnimalBreedMod {
	return AnimalBreedModFunc(func(ctx context.Context, o *AnimalBreedTemplate) {
		o.r.Animal = nil
	})
}

func (m animalBreedMods) WithBreed(rel *BreedTemplate) AnimalBreedMod {
	return AnimalBreedModFunc(func(ctx context.Context, o *AnimalBreedTemplate) {
		o.r.Breed = &animalBreedRBreedR{
			o: rel,
		}
	})
}

func (m animalBreedMods) WithNewBreed(mods ...BreedMod) AnimalBreedMod {
	return AnimalBreedModFunc(func(ctx context.Context, o *AnimalBreedTemplate) {
		related := o.f.NewBreedWithContext(ctx, mods...)

		m.WithBreed(related).Apply(ctx, o)
	})
}

func (m animalBreedMods) WithExistingBreed(em *models.Breed) AnimalBreedMod {
	return AnimalBreedModFunc(func(ctx context.Context, o *AnimalBreedTemplate) {
		o.r.Breed = &animalBreedRBreedR{
			o: o.f.FromExistingBreed(em),
		}
	})
}

func (m animalBreedMods) WithoutBreed() AnimalBreedMod {
	return AnimalBreedModFunc(func(ctx context.Context, o *AnimalBreedTemplate) {
		o.r.Breed = nil
	})
}
