// Code generated by BobGen psql v0.38.1-0.20250722094724-08202428a120. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import models "github.com/dankobg/fluffly/db/model"

type (
	Gender = models.Gender
)

func allGender() []Gender {
	return models.AllGender()
}
