// Code generated by BobGen psql v0.38.1-0.20250722094724-08202428a120. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/dankobg/fluffly/db/model"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type OrganizationPhotoMod interface {
	Apply(context.Context, *OrganizationPhotoTemplate)
}

type OrganizationPhotoModFunc func(context.Context, *OrganizationPhotoTemplate)

func (f OrganizationPhotoModFunc) Apply(ctx context.Context, n *OrganizationPhotoTemplate) {
	f(ctx, n)
}

type OrganizationPhotoModSlice []OrganizationPhotoMod

func (mods OrganizationPhotoModSlice) Apply(ctx context.Context, n *OrganizationPhotoTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// OrganizationPhotoTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type OrganizationPhotoTemplate struct {
	ID             func() int64
	OrganizationID func() null.Val[int64]
	Small          func() null.Val[string]
	Medium         func() null.Val[string]
	Large          func() null.Val[string]
	Full           func() null.Val[string]
	CreatedAt      func() time.Time
	UpdatedAt      func() time.Time

	r organizationPhotoR
	f *Factory

	alreadyPersisted bool
}

type organizationPhotoR struct {
	Organization *organizationPhotoROrganizationR
}

type organizationPhotoROrganizationR struct {
	o *OrganizationTemplate
}

// Apply mods to the OrganizationPhotoTemplate
func (o *OrganizationPhotoTemplate) Apply(ctx context.Context, mods ...OrganizationPhotoMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.OrganizationPhoto
// according to the relationships in the template. Nothing is inserted into the db
func (t OrganizationPhotoTemplate) setModelRels(o *models.OrganizationPhoto) {
	if t.r.Organization != nil {
		rel := t.r.Organization.o.Build()
		rel.R.OrganizationPhotos = append(rel.R.OrganizationPhotos, o)
		o.OrganizationID = null.From(rel.ID) // h2
		o.R.Organization = rel
	}
}

// BuildSetter returns an *models.OrganizationPhotoSetter
// this does nothing with the relationship templates
func (o OrganizationPhotoTemplate) BuildSetter() *models.OrganizationPhotoSetter {
	m := &models.OrganizationPhotoSetter{}

	if o.OrganizationID != nil {
		val := o.OrganizationID()
		m.OrganizationID = omitnull.FromNull(val)
	}
	if o.Small != nil {
		val := o.Small()
		m.Small = omitnull.FromNull(val)
	}
	if o.Medium != nil {
		val := o.Medium()
		m.Medium = omitnull.FromNull(val)
	}
	if o.Large != nil {
		val := o.Large()
		m.Large = omitnull.FromNull(val)
	}
	if o.Full != nil {
		val := o.Full()
		m.Full = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.OrganizationPhotoSetter
// this does nothing with the relationship templates
func (o OrganizationPhotoTemplate) BuildManySetter(number int) []*models.OrganizationPhotoSetter {
	m := make([]*models.OrganizationPhotoSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.OrganizationPhoto
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrganizationPhotoTemplate.Create
func (o OrganizationPhotoTemplate) Build() *models.OrganizationPhoto {
	m := &models.OrganizationPhoto{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.OrganizationID != nil {
		m.OrganizationID = o.OrganizationID()
	}
	if o.Small != nil {
		m.Small = o.Small()
	}
	if o.Medium != nil {
		m.Medium = o.Medium()
	}
	if o.Large != nil {
		m.Large = o.Large()
	}
	if o.Full != nil {
		m.Full = o.Full()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.OrganizationPhotoSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrganizationPhotoTemplate.CreateMany
func (o OrganizationPhotoTemplate) BuildMany(number int) models.OrganizationPhotoSlice {
	m := make(models.OrganizationPhotoSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableOrganizationPhoto(m *models.OrganizationPhotoSetter) {
}

// insertOptRels creates and inserts any optional the relationships on *models.OrganizationPhoto
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *OrganizationPhotoTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.OrganizationPhoto) error {
	var err error

	isOrganizationDone, _ := organizationPhotoRelOrganizationCtx.Value(ctx)
	if !isOrganizationDone && o.r.Organization != nil {
		ctx = organizationPhotoRelOrganizationCtx.WithValue(ctx, true)
		if o.r.Organization.o.alreadyPersisted {
			m.R.Organization = o.r.Organization.o.Build()
		} else {
			var rel0 *models.Organization
			rel0, err = o.r.Organization.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachOrganization(ctx, exec, rel0)
			if err != nil {
				return err
			}
		}

	}

	return err
}

// Create builds a organizationPhoto and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *OrganizationPhotoTemplate) Create(ctx context.Context, exec bob.Executor) (*models.OrganizationPhoto, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableOrganizationPhoto(opt)

	m, err := models.OrganizationPhotos.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a organizationPhoto and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *OrganizationPhotoTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.OrganizationPhoto {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a organizationPhoto and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *OrganizationPhotoTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.OrganizationPhoto {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple organizationPhotos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o OrganizationPhotoTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.OrganizationPhotoSlice, error) {
	var err error
	m := make(models.OrganizationPhotoSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple organizationPhotos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o OrganizationPhotoTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.OrganizationPhotoSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple organizationPhotos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o OrganizationPhotoTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.OrganizationPhotoSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// OrganizationPhoto has methods that act as mods for the OrganizationPhotoTemplate
var OrganizationPhotoMods organizationPhotoMods

type organizationPhotoMods struct{}

func (m organizationPhotoMods) RandomizeAllColumns(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModSlice{
		OrganizationPhotoMods.RandomID(f),
		OrganizationPhotoMods.RandomOrganizationID(f),
		OrganizationPhotoMods.RandomSmall(f),
		OrganizationPhotoMods.RandomMedium(f),
		OrganizationPhotoMods.RandomLarge(f),
		OrganizationPhotoMods.RandomFull(f),
		OrganizationPhotoMods.RandomCreatedAt(f),
		OrganizationPhotoMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m organizationPhotoMods) ID(val int64) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m organizationPhotoMods) IDFunc(f func() int64) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m organizationPhotoMods) UnsetID() OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPhotoMods) RandomID(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m organizationPhotoMods) OrganizationID(val null.Val[int64]) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.OrganizationID = func() null.Val[int64] { return val }
	})
}

// Set the Column from the function
func (m organizationPhotoMods) OrganizationIDFunc(f func() null.Val[int64]) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.OrganizationID = f
	})
}

// Clear any values for the column
func (m organizationPhotoMods) UnsetOrganizationID() OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.OrganizationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationPhotoMods) RandomOrganizationID(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.OrganizationID = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationPhotoMods) RandomOrganizationIDNotNull(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.OrganizationID = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationPhotoMods) Small(val null.Val[string]) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Small = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationPhotoMods) SmallFunc(f func() null.Val[string]) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Small = f
	})
}

// Clear any values for the column
func (m organizationPhotoMods) UnsetSmall() OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Small = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationPhotoMods) RandomSmall(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Small = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationPhotoMods) RandomSmallNotNull(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Small = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationPhotoMods) Medium(val null.Val[string]) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Medium = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationPhotoMods) MediumFunc(f func() null.Val[string]) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Medium = f
	})
}

// Clear any values for the column
func (m organizationPhotoMods) UnsetMedium() OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Medium = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationPhotoMods) RandomMedium(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Medium = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationPhotoMods) RandomMediumNotNull(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Medium = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationPhotoMods) Large(val null.Val[string]) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Large = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationPhotoMods) LargeFunc(f func() null.Val[string]) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Large = f
	})
}

// Clear any values for the column
func (m organizationPhotoMods) UnsetLarge() OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Large = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationPhotoMods) RandomLarge(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Large = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationPhotoMods) RandomLargeNotNull(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Large = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationPhotoMods) Full(val null.Val[string]) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Full = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationPhotoMods) FullFunc(f func() null.Val[string]) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Full = f
	})
}

// Clear any values for the column
func (m organizationPhotoMods) UnsetFull() OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Full = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationPhotoMods) RandomFull(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Full = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationPhotoMods) RandomFullNotNull(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.Full = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationPhotoMods) CreatedAt(val time.Time) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m organizationPhotoMods) CreatedAtFunc(f func() time.Time) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m organizationPhotoMods) UnsetCreatedAt() OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPhotoMods) RandomCreatedAt(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m organizationPhotoMods) UpdatedAt(val time.Time) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m organizationPhotoMods) UpdatedAtFunc(f func() time.Time) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m organizationPhotoMods) UnsetUpdatedAt() OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationPhotoMods) RandomUpdatedAt(f *faker.Faker) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(_ context.Context, o *OrganizationPhotoTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m organizationPhotoMods) WithParentsCascading() OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(ctx context.Context, o *OrganizationPhotoTemplate) {
		if isDone, _ := organizationPhotoWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = organizationPhotoWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewOrganizationWithContext(ctx, OrganizationMods.WithParentsCascading())
			m.WithOrganization(related).Apply(ctx, o)
		}
	})
}

func (m organizationPhotoMods) WithOrganization(rel *OrganizationTemplate) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(ctx context.Context, o *OrganizationPhotoTemplate) {
		o.r.Organization = &organizationPhotoROrganizationR{
			o: rel,
		}
	})
}

func (m organizationPhotoMods) WithNewOrganization(mods ...OrganizationMod) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(ctx context.Context, o *OrganizationPhotoTemplate) {
		related := o.f.NewOrganizationWithContext(ctx, mods...)

		m.WithOrganization(related).Apply(ctx, o)
	})
}

func (m organizationPhotoMods) WithExistingOrganization(em *models.Organization) OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(ctx context.Context, o *OrganizationPhotoTemplate) {
		o.r.Organization = &organizationPhotoROrganizationR{
			o: o.f.FromExistingOrganization(em),
		}
	})
}

func (m organizationPhotoMods) WithoutOrganization() OrganizationPhotoMod {
	return OrganizationPhotoModFunc(func(ctx context.Context, o *OrganizationPhotoTemplate) {
		o.r.Organization = nil
	})
}
