// Code generated by BobGen psql v0.38.1-0.20250722094724-08202428a120. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/dankobg/fluffly/db/model"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type OrganizationMod interface {
	Apply(context.Context, *OrganizationTemplate)
}

type OrganizationModFunc func(context.Context, *OrganizationTemplate)

func (f OrganizationModFunc) Apply(ctx context.Context, n *OrganizationTemplate) {
	f(ctx, n)
}

type OrganizationModSlice []OrganizationMod

func (mods OrganizationModSlice) Apply(ctx context.Context, n *OrganizationTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// OrganizationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type OrganizationTemplate struct {
	ID               func() int64
	Name             func() string
	Email            func() string
	Phone            func() string
	Address1         func() null.Val[string]
	Address2         func() null.Val[string]
	City             func() null.Val[string]
	State            func() null.Val[string]
	Postcode         func() null.Val[string]
	Country          func() null.Val[string]
	URL              func() null.Val[string]
	Website          func() null.Val[string]
	MissionStatement func() null.Val[string]
	AdoptionPolicy   func() null.Val[string]
	AdoptionURL      func() null.Val[string]
	Distance         func() null.Val[string]
	Facebook         func() null.Val[string]
	Twitter          func() null.Val[string]
	Youtube          func() null.Val[string]
	Instagram        func() null.Val[string]
	Pinterest        func() null.Val[string]

	r organizationR
	f *Factory

	alreadyPersisted bool
}

type organizationR struct {
	Animals            []*organizationRAnimalsR
	OrganizationHours  []*organizationROrganizationHoursR
	OrganizationPhotos []*organizationROrganizationPhotosR
}

type organizationRAnimalsR struct {
	number int
	o      *AnimalTemplate
}
type organizationROrganizationHoursR struct {
	number int
	o      *OrganizationHourTemplate
}
type organizationROrganizationPhotosR struct {
	number int
	o      *OrganizationPhotoTemplate
}

// Apply mods to the OrganizationTemplate
func (o *OrganizationTemplate) Apply(ctx context.Context, mods ...OrganizationMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Organization
// according to the relationships in the template. Nothing is inserted into the db
func (t OrganizationTemplate) setModelRels(o *models.Organization) {
	if t.r.Animals != nil {
		rel := models.AnimalSlice{}
		for _, r := range t.r.Animals {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.OrganizationID = null.From(o.ID) // h2
				rel.R.Organization = o
			}
			rel = append(rel, related...)
		}
		o.R.Animals = rel
	}

	if t.r.OrganizationHours != nil {
		rel := models.OrganizationHourSlice{}
		for _, r := range t.r.OrganizationHours {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.OrganizationID = null.From(o.ID) // h2
				rel.R.Organization = o
			}
			rel = append(rel, related...)
		}
		o.R.OrganizationHours = rel
	}

	if t.r.OrganizationPhotos != nil {
		rel := models.OrganizationPhotoSlice{}
		for _, r := range t.r.OrganizationPhotos {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.OrganizationID = null.From(o.ID) // h2
				rel.R.Organization = o
			}
			rel = append(rel, related...)
		}
		o.R.OrganizationPhotos = rel
	}
}

// BuildSetter returns an *models.OrganizationSetter
// this does nothing with the relationship templates
func (o OrganizationTemplate) BuildSetter() *models.OrganizationSetter {
	m := &models.OrganizationSetter{}

	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.Email != nil {
		val := o.Email()
		m.Email = omit.From(val)
	}
	if o.Phone != nil {
		val := o.Phone()
		m.Phone = omit.From(val)
	}
	if o.Address1 != nil {
		val := o.Address1()
		m.Address1 = omitnull.FromNull(val)
	}
	if o.Address2 != nil {
		val := o.Address2()
		m.Address2 = omitnull.FromNull(val)
	}
	if o.City != nil {
		val := o.City()
		m.City = omitnull.FromNull(val)
	}
	if o.State != nil {
		val := o.State()
		m.State = omitnull.FromNull(val)
	}
	if o.Postcode != nil {
		val := o.Postcode()
		m.Postcode = omitnull.FromNull(val)
	}
	if o.Country != nil {
		val := o.Country()
		m.Country = omitnull.FromNull(val)
	}
	if o.URL != nil {
		val := o.URL()
		m.URL = omitnull.FromNull(val)
	}
	if o.Website != nil {
		val := o.Website()
		m.Website = omitnull.FromNull(val)
	}
	if o.MissionStatement != nil {
		val := o.MissionStatement()
		m.MissionStatement = omitnull.FromNull(val)
	}
	if o.AdoptionPolicy != nil {
		val := o.AdoptionPolicy()
		m.AdoptionPolicy = omitnull.FromNull(val)
	}
	if o.AdoptionURL != nil {
		val := o.AdoptionURL()
		m.AdoptionURL = omitnull.FromNull(val)
	}
	if o.Distance != nil {
		val := o.Distance()
		m.Distance = omitnull.FromNull(val)
	}
	if o.Facebook != nil {
		val := o.Facebook()
		m.Facebook = omitnull.FromNull(val)
	}
	if o.Twitter != nil {
		val := o.Twitter()
		m.Twitter = omitnull.FromNull(val)
	}
	if o.Youtube != nil {
		val := o.Youtube()
		m.Youtube = omitnull.FromNull(val)
	}
	if o.Instagram != nil {
		val := o.Instagram()
		m.Instagram = omitnull.FromNull(val)
	}
	if o.Pinterest != nil {
		val := o.Pinterest()
		m.Pinterest = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.OrganizationSetter
// this does nothing with the relationship templates
func (o OrganizationTemplate) BuildManySetter(number int) []*models.OrganizationSetter {
	m := make([]*models.OrganizationSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Organization
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrganizationTemplate.Create
func (o OrganizationTemplate) Build() *models.Organization {
	m := &models.Organization{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.Phone != nil {
		m.Phone = o.Phone()
	}
	if o.Address1 != nil {
		m.Address1 = o.Address1()
	}
	if o.Address2 != nil {
		m.Address2 = o.Address2()
	}
	if o.City != nil {
		m.City = o.City()
	}
	if o.State != nil {
		m.State = o.State()
	}
	if o.Postcode != nil {
		m.Postcode = o.Postcode()
	}
	if o.Country != nil {
		m.Country = o.Country()
	}
	if o.URL != nil {
		m.URL = o.URL()
	}
	if o.Website != nil {
		m.Website = o.Website()
	}
	if o.MissionStatement != nil {
		m.MissionStatement = o.MissionStatement()
	}
	if o.AdoptionPolicy != nil {
		m.AdoptionPolicy = o.AdoptionPolicy()
	}
	if o.AdoptionURL != nil {
		m.AdoptionURL = o.AdoptionURL()
	}
	if o.Distance != nil {
		m.Distance = o.Distance()
	}
	if o.Facebook != nil {
		m.Facebook = o.Facebook()
	}
	if o.Twitter != nil {
		m.Twitter = o.Twitter()
	}
	if o.Youtube != nil {
		m.Youtube = o.Youtube()
	}
	if o.Instagram != nil {
		m.Instagram = o.Instagram()
	}
	if o.Pinterest != nil {
		m.Pinterest = o.Pinterest()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.OrganizationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrganizationTemplate.CreateMany
func (o OrganizationTemplate) BuildMany(number int) models.OrganizationSlice {
	m := make(models.OrganizationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableOrganization(m *models.OrganizationSetter) {
	if !(m.Name.IsValue()) {
		val := random_string(nil, "255")
		m.Name = omit.From(val)
	}
	if !(m.Email.IsValue()) {
		val := random_string(nil, "255")
		m.Email = omit.From(val)
	}
	if !(m.Phone.IsValue()) {
		val := random_string(nil, "50")
		m.Phone = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Organization
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *OrganizationTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Organization) error {
	var err error

	isAnimalsDone, _ := organizationRelAnimalsCtx.Value(ctx)
	if !isAnimalsDone && o.r.Animals != nil {
		ctx = organizationRelAnimalsCtx.WithValue(ctx, true)
		for _, r := range o.r.Animals {
			if r.o.alreadyPersisted {
				m.R.Animals = append(m.R.Animals, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachAnimals(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isOrganizationHoursDone, _ := organizationRelOrganizationHoursCtx.Value(ctx)
	if !isOrganizationHoursDone && o.r.OrganizationHours != nil {
		ctx = organizationRelOrganizationHoursCtx.WithValue(ctx, true)
		for _, r := range o.r.OrganizationHours {
			if r.o.alreadyPersisted {
				m.R.OrganizationHours = append(m.R.OrganizationHours, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOrganizationHours(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isOrganizationPhotosDone, _ := organizationRelOrganizationPhotosCtx.Value(ctx)
	if !isOrganizationPhotosDone && o.r.OrganizationPhotos != nil {
		ctx = organizationRelOrganizationPhotosCtx.WithValue(ctx, true)
		for _, r := range o.r.OrganizationPhotos {
			if r.o.alreadyPersisted {
				m.R.OrganizationPhotos = append(m.R.OrganizationPhotos, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOrganizationPhotos(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a organization and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *OrganizationTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Organization, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableOrganization(opt)

	m, err := models.Organizations.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a organization and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *OrganizationTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Organization {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a organization and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *OrganizationTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Organization {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple organizations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o OrganizationTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.OrganizationSlice, error) {
	var err error
	m := make(models.OrganizationSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple organizations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o OrganizationTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.OrganizationSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple organizations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o OrganizationTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.OrganizationSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Organization has methods that act as mods for the OrganizationTemplate
var OrganizationMods organizationMods

type organizationMods struct{}

func (m organizationMods) RandomizeAllColumns(f *faker.Faker) OrganizationMod {
	return OrganizationModSlice{
		OrganizationMods.RandomID(f),
		OrganizationMods.RandomName(f),
		OrganizationMods.RandomEmail(f),
		OrganizationMods.RandomPhone(f),
		OrganizationMods.RandomAddress1(f),
		OrganizationMods.RandomAddress2(f),
		OrganizationMods.RandomCity(f),
		OrganizationMods.RandomState(f),
		OrganizationMods.RandomPostcode(f),
		OrganizationMods.RandomCountry(f),
		OrganizationMods.RandomURL(f),
		OrganizationMods.RandomWebsite(f),
		OrganizationMods.RandomMissionStatement(f),
		OrganizationMods.RandomAdoptionPolicy(f),
		OrganizationMods.RandomAdoptionURL(f),
		OrganizationMods.RandomDistance(f),
		OrganizationMods.RandomFacebook(f),
		OrganizationMods.RandomTwitter(f),
		OrganizationMods.RandomYoutube(f),
		OrganizationMods.RandomInstagram(f),
		OrganizationMods.RandomPinterest(f),
	}
}

// Set the model columns to this value
func (m organizationMods) ID(val int64) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m organizationMods) IDFunc(f func() int64) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetID() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationMods) RandomID(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Name(val string) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationMods) NameFunc(f func() string) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetName() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationMods) RandomName(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Name = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Email(val string) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Email = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationMods) EmailFunc(f func() string) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetEmail() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationMods) RandomEmail(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Email = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Phone(val string) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Phone = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationMods) PhoneFunc(f func() string) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Phone = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetPhone() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Phone = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationMods) RandomPhone(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Phone = func() string {
			return random_string(f, "50")
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Address1(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Address1 = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) Address1Func(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Address1 = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetAddress1() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Address1 = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomAddress1(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Address1 = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomAddress1NotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Address1 = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Address2(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Address2 = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) Address2Func(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Address2 = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetAddress2() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Address2 = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomAddress2(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Address2 = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomAddress2NotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Address2 = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) City(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.City = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) CityFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.City = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetCity() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.City = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomCity(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.City = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomCityNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.City = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) State(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.State = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) StateFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.State = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetState() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.State = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomState(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.State = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "10")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomStateNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.State = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "10")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Postcode(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Postcode = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) PostcodeFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Postcode = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetPostcode() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Postcode = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomPostcode(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Postcode = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "20")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomPostcodeNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Postcode = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "20")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Country(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Country = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) CountryFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Country = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetCountry() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Country = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomCountry(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Country = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "10")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomCountryNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Country = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "10")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) URL(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.URL = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) URLFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.URL = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetURL() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.URL = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomURL(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.URL = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomURLNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.URL = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Website(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Website = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) WebsiteFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Website = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetWebsite() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Website = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomWebsite(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Website = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomWebsiteNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Website = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) MissionStatement(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.MissionStatement = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) MissionStatementFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.MissionStatement = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetMissionStatement() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.MissionStatement = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomMissionStatement(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.MissionStatement = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomMissionStatementNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.MissionStatement = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) AdoptionPolicy(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.AdoptionPolicy = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) AdoptionPolicyFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.AdoptionPolicy = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetAdoptionPolicy() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.AdoptionPolicy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomAdoptionPolicy(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.AdoptionPolicy = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomAdoptionPolicyNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.AdoptionPolicy = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) AdoptionURL(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.AdoptionURL = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) AdoptionURLFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.AdoptionURL = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetAdoptionURL() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.AdoptionURL = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomAdoptionURL(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.AdoptionURL = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomAdoptionURLNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.AdoptionURL = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Distance(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Distance = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) DistanceFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Distance = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetDistance() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Distance = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomDistance(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Distance = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "20")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomDistanceNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Distance = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "20")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Facebook(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Facebook = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) FacebookFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Facebook = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetFacebook() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Facebook = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomFacebook(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Facebook = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomFacebookNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Facebook = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Twitter(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Twitter = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) TwitterFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Twitter = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetTwitter() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Twitter = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomTwitter(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Twitter = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomTwitterNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Twitter = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Youtube(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Youtube = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) YoutubeFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Youtube = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetYoutube() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Youtube = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomYoutube(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Youtube = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomYoutubeNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Youtube = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Instagram(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Instagram = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) InstagramFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Instagram = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetInstagram() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Instagram = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomInstagram(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Instagram = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomInstagramNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Instagram = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationMods) Pinterest(val null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Pinterest = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m organizationMods) PinterestFunc(f func() null.Val[string]) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Pinterest = f
	})
}

// Clear any values for the column
func (m organizationMods) UnsetPinterest() OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Pinterest = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationMods) RandomPinterest(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Pinterest = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationMods) RandomPinterestNotNull(f *faker.Faker) OrganizationMod {
	return OrganizationModFunc(func(_ context.Context, o *OrganizationTemplate) {
		o.Pinterest = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return null.From(val)
		}
	})
}

func (m organizationMods) WithParentsCascading() OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		if isDone, _ := organizationWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = organizationWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m organizationMods) WithAnimals(number int, related *AnimalTemplate) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		o.r.Animals = []*organizationRAnimalsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m organizationMods) WithNewAnimals(number int, mods ...AnimalMod) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		related := o.f.NewAnimalWithContext(ctx, mods...)
		m.WithAnimals(number, related).Apply(ctx, o)
	})
}

func (m organizationMods) AddAnimals(number int, related *AnimalTemplate) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		o.r.Animals = append(o.r.Animals, &organizationRAnimalsR{
			number: number,
			o:      related,
		})
	})
}

func (m organizationMods) AddNewAnimals(number int, mods ...AnimalMod) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		related := o.f.NewAnimalWithContext(ctx, mods...)
		m.AddAnimals(number, related).Apply(ctx, o)
	})
}

func (m organizationMods) AddExistingAnimals(existingModels ...*models.Animal) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		for _, em := range existingModels {
			o.r.Animals = append(o.r.Animals, &organizationRAnimalsR{
				o: o.f.FromExistingAnimal(em),
			})
		}
	})
}

func (m organizationMods) WithoutAnimals() OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		o.r.Animals = nil
	})
}

func (m organizationMods) WithOrganizationHours(number int, related *OrganizationHourTemplate) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		o.r.OrganizationHours = []*organizationROrganizationHoursR{{
			number: number,
			o:      related,
		}}
	})
}

func (m organizationMods) WithNewOrganizationHours(number int, mods ...OrganizationHourMod) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		related := o.f.NewOrganizationHourWithContext(ctx, mods...)
		m.WithOrganizationHours(number, related).Apply(ctx, o)
	})
}

func (m organizationMods) AddOrganizationHours(number int, related *OrganizationHourTemplate) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		o.r.OrganizationHours = append(o.r.OrganizationHours, &organizationROrganizationHoursR{
			number: number,
			o:      related,
		})
	})
}

func (m organizationMods) AddNewOrganizationHours(number int, mods ...OrganizationHourMod) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		related := o.f.NewOrganizationHourWithContext(ctx, mods...)
		m.AddOrganizationHours(number, related).Apply(ctx, o)
	})
}

func (m organizationMods) AddExistingOrganizationHours(existingModels ...*models.OrganizationHour) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		for _, em := range existingModels {
			o.r.OrganizationHours = append(o.r.OrganizationHours, &organizationROrganizationHoursR{
				o: o.f.FromExistingOrganizationHour(em),
			})
		}
	})
}

func (m organizationMods) WithoutOrganizationHours() OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		o.r.OrganizationHours = nil
	})
}

func (m organizationMods) WithOrganizationPhotos(number int, related *OrganizationPhotoTemplate) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		o.r.OrganizationPhotos = []*organizationROrganizationPhotosR{{
			number: number,
			o:      related,
		}}
	})
}

func (m organizationMods) WithNewOrganizationPhotos(number int, mods ...OrganizationPhotoMod) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		related := o.f.NewOrganizationPhotoWithContext(ctx, mods...)
		m.WithOrganizationPhotos(number, related).Apply(ctx, o)
	})
}

func (m organizationMods) AddOrganizationPhotos(number int, related *OrganizationPhotoTemplate) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		o.r.OrganizationPhotos = append(o.r.OrganizationPhotos, &organizationROrganizationPhotosR{
			number: number,
			o:      related,
		})
	})
}

func (m organizationMods) AddNewOrganizationPhotos(number int, mods ...OrganizationPhotoMod) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		related := o.f.NewOrganizationPhotoWithContext(ctx, mods...)
		m.AddOrganizationPhotos(number, related).Apply(ctx, o)
	})
}

func (m organizationMods) AddExistingOrganizationPhotos(existingModels ...*models.OrganizationPhoto) OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		for _, em := range existingModels {
			o.r.OrganizationPhotos = append(o.r.OrganizationPhotos, &organizationROrganizationPhotosR{
				o: o.f.FromExistingOrganizationPhoto(em),
			})
		}
	})
}

func (m organizationMods) WithoutOrganizationPhotos() OrganizationMod {
	return OrganizationModFunc(func(ctx context.Context, o *OrganizationTemplate) {
		o.r.OrganizationPhotos = nil
	})
}
