// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Animals = Table[
	animalColumns,
	animalIndexes,
	animalForeignKeys,
	animalUniques,
	animalChecks,
]{
	Schema: "",
	Name:   "animal",
	Columns: animalColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "IDENTITY",
			Comment:   "",
			Nullable:  false,
			Generated: true,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "uuid",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		OrganizationID: column{
			Name:      "organization_id",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		TypeID: column{
			Name:      "type_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		BreedID: column{
			Name:      "breed_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		SpeciesID: column{
			Name:      "species_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Gender: column{
			Name:      "gender",
			DBType:    "public.gender",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Hermaphrodite: column{
			Name:      "hermaphrodite",
			DBType:    "boolean",
			Default:   "false",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Age: column{
			Name:      "age",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CoatLength: column{
			Name:      "coat_length",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Size: column{
			Name:      "size",
			DBType:    "character varying",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ImageURL: column{
			Name:      "image_url",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Distance: column{
			Name:      "distance",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		StatusChangedAt: column{
			Name:      "status_changed_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		AdoptedAt: column{
			Name:      "adopted_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: animalIndexes{
		PKAnimalID: index{
			Type: "btree",
			Name: "pk_animal_id",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_animal_id",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: animalForeignKeys{
		AnimalFKAnimalOrganizationID: foreignKey{
			constraint: constraint{
				Name:    "animal.fk_animal_organization_id",
				Columns: []string{"organization_id"},
				Comment: "",
			},
			ForeignTable:   "organization",
			ForeignColumns: []string{"id"},
		},
		AnimalFKAnimalUserID: foreignKey{
			constraint: constraint{
				Name:    "animal.fk_animal_user_id",
				Columns: []string{"user_id"},
				Comment: "",
			},
			ForeignTable:   "user",
			ForeignColumns: []string{"id"},
		},
	},

	Checks: animalChecks{
		CKAnimalUserOrOrganizationProvided: check{
			constraint: constraint{
				Name:    "ck_animal_user_or_organization_provided",
				Columns: []string{"user_id", "organization_id"},
				Comment: "",
			},
			Expression: "(((user_id IS NOT NULL) AND (organization_id IS NULL)) OR ((user_id IS NULL) AND (organization_id IS NOT NULL)))",
		},
	},
	Comment: "",
}

type animalColumns struct {
	ID              column
	UserID          column
	OrganizationID  column
	TypeID          column
	BreedID         column
	SpeciesID       column
	Name            column
	Gender          column
	Hermaphrodite   column
	Age             column
	CoatLength      column
	Size            column
	ImageURL        column
	Description     column
	Distance        column
	Status          column
	StatusChangedAt column
	AdoptedAt       column
	CreatedAt       column
	UpdatedAt       column
}

func (c animalColumns) AsSlice() []column {
	return []column{
		c.ID, c.UserID, c.OrganizationID, c.TypeID, c.BreedID, c.SpeciesID, c.Name, c.Gender, c.Hermaphrodite, c.Age, c.CoatLength, c.Size, c.ImageURL, c.Description, c.Distance, c.Status, c.StatusChangedAt, c.AdoptedAt, c.CreatedAt, c.UpdatedAt,
	}
}

type animalIndexes struct {
	PKAnimalID index
}

func (i animalIndexes) AsSlice() []index {
	return []index{
		i.PKAnimalID,
	}
}

type animalForeignKeys struct {
	AnimalFKAnimalOrganizationID foreignKey
	AnimalFKAnimalUserID         foreignKey
}

func (f animalForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.AnimalFKAnimalOrganizationID, f.AnimalFKAnimalUserID,
	}
}

type animalUniques struct{}

func (u animalUniques) AsSlice() []constraint {
	return []constraint{}
}

type animalChecks struct {
	CKAnimalUserOrOrganizationProvided check
}

func (c animalChecks) AsSlice() []check {
	return []check{
		c.CKAnimalUserOrOrganizationProvided,
	}
}
