// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var AnimalPhotos = Table[
	animalPhotoColumns,
	animalPhotoIndexes,
	animalPhotoForeignKeys,
	animalPhotoUniques,
	animalPhotoChecks,
]{
	Schema: "",
	Name:   "animal_photo",
	Columns: animalPhotoColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "IDENTITY",
			Comment:   "",
			Nullable:  false,
			Generated: true,
			AutoIncr:  false,
		},
		AnimalID: column{
			Name:      "animal_id",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Small: column{
			Name:      "small",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Medium: column{
			Name:      "medium",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Large: column{
			Name:      "large",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Full: column{
			Name:      "full",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: animalPhotoIndexes{
		PKAnimalPhotoID: index{
			Type: "btree",
			Name: "pk_animal_photo_id",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_animal_photo_id",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: animalPhotoForeignKeys{
		AnimalPhotoFKAnimalPhotoIDAnimalID: foreignKey{
			constraint: constraint{
				Name:    "animal_photo.fk_animal_photo_id_animal_id",
				Columns: []string{"animal_id"},
				Comment: "",
			},
			ForeignTable:   "animal",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type animalPhotoColumns struct {
	ID        column
	AnimalID  column
	Small     column
	Medium    column
	Large     column
	Full      column
	CreatedAt column
	UpdatedAt column
}

func (c animalPhotoColumns) AsSlice() []column {
	return []column{
		c.ID, c.AnimalID, c.Small, c.Medium, c.Large, c.Full, c.CreatedAt, c.UpdatedAt,
	}
}

type animalPhotoIndexes struct {
	PKAnimalPhotoID index
}

func (i animalPhotoIndexes) AsSlice() []index {
	return []index{
		i.PKAnimalPhotoID,
	}
}

type animalPhotoForeignKeys struct {
	AnimalPhotoFKAnimalPhotoIDAnimalID foreignKey
}

func (f animalPhotoForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.AnimalPhotoFKAnimalPhotoIDAnimalID,
	}
}

type animalPhotoUniques struct{}

func (u animalPhotoUniques) AsSlice() []constraint {
	return []constraint{}
}

type animalPhotoChecks struct{}

func (c animalPhotoChecks) AsSlice() []check {
	return []check{}
}
