// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var OrganizationWorkHours = Table[
	organizationWorkHourColumns,
	organizationWorkHourIndexes,
	organizationWorkHourForeignKeys,
	organizationWorkHourUniques,
	organizationWorkHourChecks,
]{
	Schema: "",
	Name:   "organization_work_hour",
	Columns: organizationWorkHourColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "IDENTITY",
			Comment:   "",
			Nullable:  false,
			Generated: true,
			AutoIncr:  false,
		},
		OrganizationID: column{
			Name:      "organization_id",
			DBType:    "bigint",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Monday: column{
			Name:      "monday",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Tuesday: column{
			Name:      "tuesday",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Wednesday: column{
			Name:      "wednesday",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Thursday: column{
			Name:      "thursday",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Friday: column{
			Name:      "friday",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Saturday: column{
			Name:      "saturday",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Sunday: column{
			Name:      "sunday",
			DBType:    "character varying",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: organizationWorkHourIndexes{
		PKOrganizationWorkHourID: index{
			Type: "btree",
			Name: "pk_organization_work_hour_id",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UqOrganizationWorkHourOrganizationID: index{
			Type: "btree",
			Name: "uq_organization_work_hour_organization_id",
			Columns: []indexColumn{
				{
					Name:         "organization_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "pk_organization_work_hour_id",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: organizationWorkHourForeignKeys{
		OrganizationWorkHourFKOrganizationWorkHourOrganizationID: foreignKey{
			constraint: constraint{
				Name:    "organization_work_hour.fk_organization_work_hour_organization_id",
				Columns: []string{"organization_id"},
				Comment: "",
			},
			ForeignTable:   "organization",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: organizationWorkHourUniques{
		UqOrganizationWorkHourOrganizationID: constraint{
			Name:    "uq_organization_work_hour_organization_id",
			Columns: []string{"organization_id"},
			Comment: "",
		},
	},
	Checks: organizationWorkHourChecks{
		CKOrganizationWorkHourProvided: check{
			constraint: constraint{
				Name:    "ck_organization_work_hour_provided",
				Columns: []string{"monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"},
				Comment: "",
			},
			Expression: "(COALESCE(NULLIF(TRIM(BOTH FROM monday), ''::text), NULLIF(TRIM(BOTH FROM tuesday), ''::text), NULLIF(TRIM(BOTH FROM wednesday), ''::text), NULLIF(TRIM(BOTH FROM thursday), ''::text), NULLIF(TRIM(BOTH FROM friday), ''::text), NULLIF(TRIM(BOTH FROM saturday), ''::text), NULLIF(TRIM(BOTH FROM sunday), ''::text)) IS NOT NULL)",
		},
	},
	Comment: "",
}

type organizationWorkHourColumns struct {
	ID             column
	OrganizationID column
	Monday         column
	Tuesday        column
	Wednesday      column
	Thursday       column
	Friday         column
	Saturday       column
	Sunday         column
	CreatedAt      column
	UpdatedAt      column
}

func (c organizationWorkHourColumns) AsSlice() []column {
	return []column{
		c.ID, c.OrganizationID, c.Monday, c.Tuesday, c.Wednesday, c.Thursday, c.Friday, c.Saturday, c.Sunday, c.CreatedAt, c.UpdatedAt,
	}
}

type organizationWorkHourIndexes struct {
	PKOrganizationWorkHourID             index
	UqOrganizationWorkHourOrganizationID index
}

func (i organizationWorkHourIndexes) AsSlice() []index {
	return []index{
		i.PKOrganizationWorkHourID, i.UqOrganizationWorkHourOrganizationID,
	}
}

type organizationWorkHourForeignKeys struct {
	OrganizationWorkHourFKOrganizationWorkHourOrganizationID foreignKey
}

func (f organizationWorkHourForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.OrganizationWorkHourFKOrganizationWorkHourOrganizationID,
	}
}

type organizationWorkHourUniques struct {
	UqOrganizationWorkHourOrganizationID constraint
}

func (u organizationWorkHourUniques) AsSlice() []constraint {
	return []constraint{
		u.UqOrganizationWorkHourOrganizationID,
	}
}

type organizationWorkHourChecks struct {
	CKOrganizationWorkHourProvided check
}

func (c organizationWorkHourChecks) AsSlice() []check {
	return []check{
		c.CKOrganizationWorkHourProvided,
	}
}
