// Code generated by BobGen psql v0.38.1-0.20250722094724-08202428a120. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package queries

import (
	"context"
	_ "embed"
	"io"
	"iter"
	"time"

	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/scan"
)

//go:embed queries.bob.sql
var formattedQueries_queries string

var listUsersSQL = formattedQueries_queries[177:289]

type ListUsersQuery = orm.ModQuery[*dialect.SelectQuery, listUsers, ListUsersRow, []ListUsersRow, listUsersTransformer]

func ListUsers() *ListUsersQuery {
	var expressionTypArgs listUsers

	return &ListUsersQuery{
		Query: orm.Query[listUsers, ListUsersRow, []ListUsersRow, listUsersTransformer]{
			ExecQuery: orm.ExecQuery[listUsers]{
				BaseQuery: bob.BaseQuery[listUsers]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (ListUsersRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t ListUsersRow
						row.ScheduleScanByIndex(0, &t.ID)
						row.ScheduleScanByIndex(1, &t.CreatedAt)
						row.ScheduleScanByIndex(2, &t.UpdatedAt)
						return &t, nil
					}, func(v any) (ListUsersRow, error) {
						return *(v.(*ListUsersRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(7, 100))
			q.SetTable(expressionTypArgs.subExpr(106, 112))
		}),
	}
}

type ListUsersRow = struct {
	ID        uuid.UUID `db:"id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type listUsersTransformer = bob.SliceTransformer[ListUsersRow, []ListUsersRow]

type listUsers struct{}

func (o listUsers) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
	}
}

func (o listUsers) raw(from, to int) string {
	return listUsersSQL[from:to]
}

func (o listUsers) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(listUsersSQL, from, to, o.args())
}

func (o listUsers) WriteSQL(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(listUsersSQL)).WriteSQL(ctx, w, d, start)
}

var getUserByIdSQL = formattedQueries_queries[307:435]

type GetUserByIdQuery = orm.ModQuery[*dialect.SelectQuery, getUserById, GetUserByIdRow, []GetUserByIdRow, getUserByIdTransformer]

func GetUserById(ID uuid.UUID) *GetUserByIdQuery {
	var expressionTypArgs getUserById

	expressionTypArgs.ID = psql.Arg(ID)

	return &GetUserByIdQuery{
		Query: orm.Query[getUserById, GetUserByIdRow, []GetUserByIdRow, getUserByIdTransformer]{
			ExecQuery: orm.ExecQuery[getUserById]{
				BaseQuery: bob.BaseQuery[getUserById]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (GetUserByIdRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t GetUserByIdRow
						row.ScheduleScanByIndex(0, &t.ID)
						row.ScheduleScanByIndex(1, &t.CreatedAt)
						row.ScheduleScanByIndex(2, &t.UpdatedAt)
						return &t, nil
					}, func(v any) (GetUserByIdRow, error) {
						return *(v.(*GetUserByIdRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(7, 100))
			q.SetTable(expressionTypArgs.subExpr(106, 112))
			q.AppendWhere(expressionTypArgs.subExpr(119, 128))
		}),
	}
}

type GetUserByIdRow = struct {
	ID        uuid.UUID `db:"id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type getUserByIdTransformer = bob.SliceTransformer[GetUserByIdRow, []GetUserByIdRow]

type getUserById struct {
	ID bob.Expression
}

func (o getUserById) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "id",
			Start:      126,
			Stop:       128,
			Expression: o.ID,
		}) {
			return
		}
	}
}

func (o getUserById) raw(from, to int) string {
	return getUserByIdSQL[from:to]
}

func (o getUserById) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(getUserByIdSQL, from, to, o.args())
}

func (o getUserById) WriteSQL(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(getUserByIdSQL)).WriteSQL(ctx, w, d, start)
}
