// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package queries

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	testutils "github.com/stephenafamo/bob/test/utils"
)

func TestListCountries(t *testing.T) {
	t.Run("Base", func(t *testing.T) {
		var sb strings.Builder

		query := ListCountries()

		if _, err := query.WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		if diff := cmp.Diff(listCountriesSQL, sb.String()); diff != "" {
			t.Fatalf("unexpected result (-got +want):\n%s", diff)
		}
	})

	t.Run("Mod", func(t *testing.T) {
		var sb strings.Builder

		query := ListCountries()

		if _, err := psql.Select(query).WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		queryDiff, err := testutils.QueryDiff(listCountriesSQL, sb.String(), formatQuery)
		if err != nil {
			t.Fatal(err)
		}
		if queryDiff != "" {
			fmt.Println(sb.String())
			t.Fatalf("unexpected result (-got +want):\n%s", queryDiff)
		}
	})

	t.Run("Scanning", func(t *testing.T) {
		if testDB == nil {
			t.Skip("skipping test, no DSN provided")
		}

		ctxTx, cancel := context.WithCancel(t.Context())
		defer cancel()

		tx, err := testDB.Begin(ctxTx)
		if err != nil {
			t.Fatalf("Error starting transaction: %v", err)
		}

		defer func() {
			if err := tx.Rollback(ctxTx); err != nil {
				t.Fatalf("Error rolling back transaction: %v", err)
			}
		}()

		query, args, err := bob.Build(ctxTx, psql.Select(ListCountries()))
		if err != nil {
			t.Fatal(err)
		}

		rows, err := tx.QueryContext(ctxTx, query, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer rows.Close()

		columns, err := rows.Columns()
		if err != nil {
			t.Fatal(err)
		}

		if len(columns) != 7 {
			t.Fatalf("expected %d columns, got %d", 7, len(columns))
		}

		if columns[0] != "id" {
			t.Fatalf("expected column %d to be %s, got %s", 0, "id", columns[0])
		}

		if columns[1] != "name" {
			t.Fatalf("expected column %d to be %s, got %s", 1, "name", columns[1])
		}

		if columns[2] != "iso_alpha2" {
			t.Fatalf("expected column %d to be %s, got %s", 2, "iso_alpha2", columns[2])
		}

		if columns[3] != "iso_alpha3" {
			t.Fatalf("expected column %d to be %s, got %s", 3, "iso_alpha3", columns[3])
		}

		if columns[4] != "iso_numeric" {
			t.Fatalf("expected column %d to be %s, got %s", 4, "iso_numeric", columns[4])
		}

		if columns[5] != "created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 5, "created_at", columns[5])
		}

		if columns[6] != "updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 6, "updated_at", columns[6])
		}
	})
}

func TestListUsers(t *testing.T) {
	t.Run("Base", func(t *testing.T) {
		var sb strings.Builder

		query := ListUsers()

		if _, err := query.WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		if diff := cmp.Diff(listUsersSQL, sb.String()); diff != "" {
			t.Fatalf("unexpected result (-got +want):\n%s", diff)
		}
	})

	t.Run("Mod", func(t *testing.T) {
		var sb strings.Builder

		query := ListUsers()

		if _, err := psql.Select(query).WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		queryDiff, err := testutils.QueryDiff(listUsersSQL, sb.String(), formatQuery)
		if err != nil {
			t.Fatal(err)
		}
		if queryDiff != "" {
			fmt.Println(sb.String())
			t.Fatalf("unexpected result (-got +want):\n%s", queryDiff)
		}
	})

	t.Run("Scanning", func(t *testing.T) {
		if testDB == nil {
			t.Skip("skipping test, no DSN provided")
		}

		ctxTx, cancel := context.WithCancel(t.Context())
		defer cancel()

		tx, err := testDB.Begin(ctxTx)
		if err != nil {
			t.Fatalf("Error starting transaction: %v", err)
		}

		defer func() {
			if err := tx.Rollback(ctxTx); err != nil {
				t.Fatalf("Error rolling back transaction: %v", err)
			}
		}()

		query, args, err := bob.Build(ctxTx, psql.Select(ListUsers()))
		if err != nil {
			t.Fatal(err)
		}

		rows, err := tx.QueryContext(ctxTx, query, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer rows.Close()

		columns, err := rows.Columns()
		if err != nil {
			t.Fatal(err)
		}

		if len(columns) != 3 {
			t.Fatalf("expected %d columns, got %d", 3, len(columns))
		}

		if columns[0] != "id" {
			t.Fatalf("expected column %d to be %s, got %s", 0, "id", columns[0])
		}

		if columns[1] != "created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 1, "created_at", columns[1])
		}

		if columns[2] != "updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 2, "updated_at", columns[2])
		}
	})
}

func TestGetUserById(t *testing.T) {
	t.Run("Base", func(t *testing.T) {
		var sb strings.Builder

		query := GetUserById(random_uuid_UUID(nil))

		if _, err := query.WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		if diff := cmp.Diff(getUserByIdSQL, sb.String()); diff != "" {
			t.Fatalf("unexpected result (-got +want):\n%s", diff)
		}
	})

	t.Run("Mod", func(t *testing.T) {
		var sb strings.Builder

		query := GetUserById(random_uuid_UUID(nil))

		if _, err := psql.Select(query).WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		queryDiff, err := testutils.QueryDiff(getUserByIdSQL, sb.String(), formatQuery)
		if err != nil {
			t.Fatal(err)
		}
		if queryDiff != "" {
			fmt.Println(sb.String())
			t.Fatalf("unexpected result (-got +want):\n%s", queryDiff)
		}
	})

	t.Run("Scanning", func(t *testing.T) {
		if testDB == nil {
			t.Skip("skipping test, no DSN provided")
		}

		ctxTx, cancel := context.WithCancel(t.Context())
		defer cancel()

		tx, err := testDB.Begin(ctxTx)
		if err != nil {
			t.Fatalf("Error starting transaction: %v", err)
		}

		defer func() {
			if err := tx.Rollback(ctxTx); err != nil {
				t.Fatalf("Error rolling back transaction: %v", err)
			}
		}()

		query, args, err := bob.Build(ctxTx, psql.Select(GetUserById(random_uuid_UUID(nil))))
		if err != nil {
			t.Fatal(err)
		}

		rows, err := tx.QueryContext(ctxTx, query, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer rows.Close()

		columns, err := rows.Columns()
		if err != nil {
			t.Fatal(err)
		}

		if len(columns) != 3 {
			t.Fatalf("expected %d columns, got %d", 3, len(columns))
		}

		if columns[0] != "id" {
			t.Fatalf("expected column %d to be %s, got %s", 0, "id", columns[0])
		}

		if columns[1] != "created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 1, "created_at", columns[1])
		}

		if columns[2] != "updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 2, "updated_at", columns[2])
		}
	})
}

func TestListOrganizations(t *testing.T) {
	t.Run("Base", func(t *testing.T) {
		var sb strings.Builder

		query := ListOrganizations()

		if _, err := query.WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		if diff := cmp.Diff(listOrganizationsSQL, sb.String()); diff != "" {
			t.Fatalf("unexpected result (-got +want):\n%s", diff)
		}
	})

	t.Run("Mod", func(t *testing.T) {
		var sb strings.Builder

		query := ListOrganizations()

		if _, err := psql.Select(query).WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		queryDiff, err := testutils.QueryDiff(listOrganizationsSQL, sb.String(), formatQuery)
		if err != nil {
			t.Fatal(err)
		}
		if queryDiff != "" {
			fmt.Println(sb.String())
			t.Fatalf("unexpected result (-got +want):\n%s", queryDiff)
		}
	})

	t.Run("Scanning", func(t *testing.T) {
		if testDB == nil {
			t.Skip("skipping test, no DSN provided")
		}

		ctxTx, cancel := context.WithCancel(t.Context())
		defer cancel()

		tx, err := testDB.Begin(ctxTx)
		if err != nil {
			t.Fatalf("Error starting transaction: %v", err)
		}

		defer func() {
			if err := tx.Rollback(ctxTx); err != nil {
				t.Fatalf("Error rolling back transaction: %v", err)
			}
		}()

		query, args, err := bob.Build(ctxTx, psql.Select(ListOrganizations()))
		if err != nil {
			t.Fatal(err)
		}

		rows, err := tx.QueryContext(ctxTx, query, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer rows.Close()

		columns, err := rows.Columns()
		if err != nil {
			t.Fatal(err)
		}

		if len(columns) != 49 {
			t.Fatalf("expected %d columns, got %d", 49, len(columns))
		}

		if columns[0] != "id" {
			t.Fatalf("expected column %d to be %s, got %s", 0, "id", columns[0])
		}

		if columns[1] != "name" {
			t.Fatalf("expected column %d to be %s, got %s", 1, "name", columns[1])
		}

		if columns[2] != "website" {
			t.Fatalf("expected column %d to be %s, got %s", 2, "website", columns[2])
		}

		if columns[3] != "mission_statement" {
			t.Fatalf("expected column %d to be %s, got %s", 3, "mission_statement", columns[3])
		}

		if columns[4] != "adoption_policy" {
			t.Fatalf("expected column %d to be %s, got %s", 4, "adoption_policy", columns[4])
		}

		if columns[5] != "adoption_url" {
			t.Fatalf("expected column %d to be %s, got %s", 5, "adoption_url", columns[5])
		}

		if columns[6] != "distance" {
			t.Fatalf("expected column %d to be %s, got %s", 6, "distance", columns[6])
		}

		if columns[7] != "created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 7, "created_at", columns[7])
		}

		if columns[8] != "updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 8, "updated_at", columns[8])
		}

		if columns[9] != "photos" {
			t.Fatalf("expected column %d to be %s, got %s", 9, "photos", columns[9])
		}

		if columns[10] != "socials" {
			t.Fatalf("expected column %d to be %s, got %s", 10, "socials", columns[10])
		}

		if columns[11] != "organization_work_hour__id" {
			t.Fatalf("expected column %d to be %s, got %s", 11, "organization_work_hour__id", columns[11])
		}

		if columns[12] != "organization_work_hour__organization_id" {
			t.Fatalf("expected column %d to be %s, got %s", 12, "organization_work_hour__organization_id", columns[12])
		}

		if columns[13] != "organization_work_hour__monday" {
			t.Fatalf("expected column %d to be %s, got %s", 13, "organization_work_hour__monday", columns[13])
		}

		if columns[14] != "organization_work_hour__tuesday" {
			t.Fatalf("expected column %d to be %s, got %s", 14, "organization_work_hour__tuesday", columns[14])
		}

		if columns[15] != "organization_work_hour__wednesday" {
			t.Fatalf("expected column %d to be %s, got %s", 15, "organization_work_hour__wednesday", columns[15])
		}

		if columns[16] != "organization_work_hour__thursday" {
			t.Fatalf("expected column %d to be %s, got %s", 16, "organization_work_hour__thursday", columns[16])
		}

		if columns[17] != "organization_work_hour__friday" {
			t.Fatalf("expected column %d to be %s, got %s", 17, "organization_work_hour__friday", columns[17])
		}

		if columns[18] != "organization_work_hour__saturday" {
			t.Fatalf("expected column %d to be %s, got %s", 18, "organization_work_hour__saturday", columns[18])
		}

		if columns[19] != "organization_work_hour__sunday" {
			t.Fatalf("expected column %d to be %s, got %s", 19, "organization_work_hour__sunday", columns[19])
		}

		if columns[20] != "organization_work_hour__created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 20, "organization_work_hour__created_at", columns[20])
		}

		if columns[21] != "organization_work_hour__updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 21, "organization_work_hour__updated_at", columns[21])
		}

		if columns[22] != "organization_contact__id" {
			t.Fatalf("expected column %d to be %s, got %s", 22, "organization_contact__id", columns[22])
		}

		if columns[23] != "organization_contact__organization_id" {
			t.Fatalf("expected column %d to be %s, got %s", 23, "organization_contact__organization_id", columns[23])
		}

		if columns[24] != "organization_contact__address_id" {
			t.Fatalf("expected column %d to be %s, got %s", 24, "organization_contact__address_id", columns[24])
		}

		if columns[25] != "organization_contact__phone" {
			t.Fatalf("expected column %d to be %s, got %s", 25, "organization_contact__phone", columns[25])
		}

		if columns[26] != "organization_contact__email" {
			t.Fatalf("expected column %d to be %s, got %s", 26, "organization_contact__email", columns[26])
		}

		if columns[27] != "organization_contact__created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 27, "organization_contact__created_at", columns[27])
		}

		if columns[28] != "organization_contact__updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 28, "organization_contact__updated_at", columns[28])
		}

		if columns[29] != "organization_contact.address__id" {
			t.Fatalf("expected column %d to be %s, got %s", 29, "organization_contact.address__id", columns[29])
		}

		if columns[30] != "organization_contact.address__country_id" {
			t.Fatalf("expected column %d to be %s, got %s", 30, "organization_contact.address__country_id", columns[30])
		}

		if columns[31] != "organization_contact.address__unit_number" {
			t.Fatalf("expected column %d to be %s, got %s", 31, "organization_contact.address__unit_number", columns[31])
		}

		if columns[32] != "organization_contact.address__street_number" {
			t.Fatalf("expected column %d to be %s, got %s", 32, "organization_contact.address__street_number", columns[32])
		}

		if columns[33] != "organization_contact.address__street_address" {
			t.Fatalf("expected column %d to be %s, got %s", 33, "organization_contact.address__street_address", columns[33])
		}

		if columns[34] != "organization_contact.address__city" {
			t.Fatalf("expected column %d to be %s, got %s", 34, "organization_contact.address__city", columns[34])
		}

		if columns[35] != "organization_contact.address__region" {
			t.Fatalf("expected column %d to be %s, got %s", 35, "organization_contact.address__region", columns[35])
		}

		if columns[36] != "organization_contact.address__postal_code" {
			t.Fatalf("expected column %d to be %s, got %s", 36, "organization_contact.address__postal_code", columns[36])
		}

		if columns[37] != "organization_contact.address__lat" {
			t.Fatalf("expected column %d to be %s, got %s", 37, "organization_contact.address__lat", columns[37])
		}

		if columns[38] != "organization_contact.address__lng" {
			t.Fatalf("expected column %d to be %s, got %s", 38, "organization_contact.address__lng", columns[38])
		}

		if columns[39] != "organization_contact.address__note" {
			t.Fatalf("expected column %d to be %s, got %s", 39, "organization_contact.address__note", columns[39])
		}

		if columns[40] != "organization_contact.address__created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 40, "organization_contact.address__created_at", columns[40])
		}

		if columns[41] != "organization_contact.address__updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 41, "organization_contact.address__updated_at", columns[41])
		}

		if columns[42] != "organization_contact.address.country__id" {
			t.Fatalf("expected column %d to be %s, got %s", 42, "organization_contact.address.country__id", columns[42])
		}

		if columns[43] != "organization_contact.address.country__name" {
			t.Fatalf("expected column %d to be %s, got %s", 43, "organization_contact.address.country__name", columns[43])
		}

		if columns[44] != "organization_contact.address.country__iso_alpha2" {
			t.Fatalf("expected column %d to be %s, got %s", 44, "organization_contact.address.country__iso_alpha2", columns[44])
		}

		if columns[45] != "organization_contact.address.country__iso_alpha3" {
			t.Fatalf("expected column %d to be %s, got %s", 45, "organization_contact.address.country__iso_alpha3", columns[45])
		}

		if columns[46] != "organization_contact.address.country__iso_numeric" {
			t.Fatalf("expected column %d to be %s, got %s", 46, "organization_contact.address.country__iso_numeric", columns[46])
		}

		if columns[47] != "organization_contact.address.country__created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 47, "organization_contact.address.country__created_at", columns[47])
		}

		if columns[48] != "organization_contact.address.country__updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 48, "organization_contact.address.country__updated_at", columns[48])
		}
	})
}

func TestGetOrganizationById(t *testing.T) {
	t.Run("Base", func(t *testing.T) {
		var sb strings.Builder

		query := GetOrganizationById(random_int64(nil))

		if _, err := query.WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		if diff := cmp.Diff(getOrganizationByIdSQL, sb.String()); diff != "" {
			t.Fatalf("unexpected result (-got +want):\n%s", diff)
		}
	})

	t.Run("Mod", func(t *testing.T) {
		var sb strings.Builder

		query := GetOrganizationById(random_int64(nil))

		if _, err := psql.Select(query).WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		queryDiff, err := testutils.QueryDiff(getOrganizationByIdSQL, sb.String(), formatQuery)
		if err != nil {
			t.Fatal(err)
		}
		if queryDiff != "" {
			fmt.Println(sb.String())
			t.Fatalf("unexpected result (-got +want):\n%s", queryDiff)
		}
	})

	t.Run("Scanning", func(t *testing.T) {
		if testDB == nil {
			t.Skip("skipping test, no DSN provided")
		}

		ctxTx, cancel := context.WithCancel(t.Context())
		defer cancel()

		tx, err := testDB.Begin(ctxTx)
		if err != nil {
			t.Fatalf("Error starting transaction: %v", err)
		}

		defer func() {
			if err := tx.Rollback(ctxTx); err != nil {
				t.Fatalf("Error rolling back transaction: %v", err)
			}
		}()

		query, args, err := bob.Build(ctxTx, psql.Select(GetOrganizationById(random_int64(nil))))
		if err != nil {
			t.Fatal(err)
		}

		rows, err := tx.QueryContext(ctxTx, query, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer rows.Close()

		columns, err := rows.Columns()
		if err != nil {
			t.Fatal(err)
		}

		if len(columns) != 49 {
			t.Fatalf("expected %d columns, got %d", 49, len(columns))
		}

		if columns[0] != "id" {
			t.Fatalf("expected column %d to be %s, got %s", 0, "id", columns[0])
		}

		if columns[1] != "name" {
			t.Fatalf("expected column %d to be %s, got %s", 1, "name", columns[1])
		}

		if columns[2] != "website" {
			t.Fatalf("expected column %d to be %s, got %s", 2, "website", columns[2])
		}

		if columns[3] != "mission_statement" {
			t.Fatalf("expected column %d to be %s, got %s", 3, "mission_statement", columns[3])
		}

		if columns[4] != "adoption_policy" {
			t.Fatalf("expected column %d to be %s, got %s", 4, "adoption_policy", columns[4])
		}

		if columns[5] != "adoption_url" {
			t.Fatalf("expected column %d to be %s, got %s", 5, "adoption_url", columns[5])
		}

		if columns[6] != "distance" {
			t.Fatalf("expected column %d to be %s, got %s", 6, "distance", columns[6])
		}

		if columns[7] != "created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 7, "created_at", columns[7])
		}

		if columns[8] != "updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 8, "updated_at", columns[8])
		}

		if columns[9] != "photos" {
			t.Fatalf("expected column %d to be %s, got %s", 9, "photos", columns[9])
		}

		if columns[10] != "socials" {
			t.Fatalf("expected column %d to be %s, got %s", 10, "socials", columns[10])
		}

		if columns[11] != "organization_work_hour__id" {
			t.Fatalf("expected column %d to be %s, got %s", 11, "organization_work_hour__id", columns[11])
		}

		if columns[12] != "organization_work_hour__organization_id" {
			t.Fatalf("expected column %d to be %s, got %s", 12, "organization_work_hour__organization_id", columns[12])
		}

		if columns[13] != "organization_work_hour__monday" {
			t.Fatalf("expected column %d to be %s, got %s", 13, "organization_work_hour__monday", columns[13])
		}

		if columns[14] != "organization_work_hour__tuesday" {
			t.Fatalf("expected column %d to be %s, got %s", 14, "organization_work_hour__tuesday", columns[14])
		}

		if columns[15] != "organization_work_hour__wednesday" {
			t.Fatalf("expected column %d to be %s, got %s", 15, "organization_work_hour__wednesday", columns[15])
		}

		if columns[16] != "organization_work_hour__thursday" {
			t.Fatalf("expected column %d to be %s, got %s", 16, "organization_work_hour__thursday", columns[16])
		}

		if columns[17] != "organization_work_hour__friday" {
			t.Fatalf("expected column %d to be %s, got %s", 17, "organization_work_hour__friday", columns[17])
		}

		if columns[18] != "organization_work_hour__saturday" {
			t.Fatalf("expected column %d to be %s, got %s", 18, "organization_work_hour__saturday", columns[18])
		}

		if columns[19] != "organization_work_hour__sunday" {
			t.Fatalf("expected column %d to be %s, got %s", 19, "organization_work_hour__sunday", columns[19])
		}

		if columns[20] != "organization_work_hour__created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 20, "organization_work_hour__created_at", columns[20])
		}

		if columns[21] != "organization_work_hour__updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 21, "organization_work_hour__updated_at", columns[21])
		}

		if columns[22] != "organization_contact__id" {
			t.Fatalf("expected column %d to be %s, got %s", 22, "organization_contact__id", columns[22])
		}

		if columns[23] != "organization_contact__organization_id" {
			t.Fatalf("expected column %d to be %s, got %s", 23, "organization_contact__organization_id", columns[23])
		}

		if columns[24] != "organization_contact__address_id" {
			t.Fatalf("expected column %d to be %s, got %s", 24, "organization_contact__address_id", columns[24])
		}

		if columns[25] != "organization_contact__phone" {
			t.Fatalf("expected column %d to be %s, got %s", 25, "organization_contact__phone", columns[25])
		}

		if columns[26] != "organization_contact__email" {
			t.Fatalf("expected column %d to be %s, got %s", 26, "organization_contact__email", columns[26])
		}

		if columns[27] != "organization_contact__created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 27, "organization_contact__created_at", columns[27])
		}

		if columns[28] != "organization_contact__updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 28, "organization_contact__updated_at", columns[28])
		}

		if columns[29] != "organization_contact.address__id" {
			t.Fatalf("expected column %d to be %s, got %s", 29, "organization_contact.address__id", columns[29])
		}

		if columns[30] != "organization_contact.address__country_id" {
			t.Fatalf("expected column %d to be %s, got %s", 30, "organization_contact.address__country_id", columns[30])
		}

		if columns[31] != "organization_contact.address__unit_number" {
			t.Fatalf("expected column %d to be %s, got %s", 31, "organization_contact.address__unit_number", columns[31])
		}

		if columns[32] != "organization_contact.address__street_number" {
			t.Fatalf("expected column %d to be %s, got %s", 32, "organization_contact.address__street_number", columns[32])
		}

		if columns[33] != "organization_contact.address__street_address" {
			t.Fatalf("expected column %d to be %s, got %s", 33, "organization_contact.address__street_address", columns[33])
		}

		if columns[34] != "organization_contact.address__city" {
			t.Fatalf("expected column %d to be %s, got %s", 34, "organization_contact.address__city", columns[34])
		}

		if columns[35] != "organization_contact.address__region" {
			t.Fatalf("expected column %d to be %s, got %s", 35, "organization_contact.address__region", columns[35])
		}

		if columns[36] != "organization_contact.address__postal_code" {
			t.Fatalf("expected column %d to be %s, got %s", 36, "organization_contact.address__postal_code", columns[36])
		}

		if columns[37] != "organization_contact.address__lat" {
			t.Fatalf("expected column %d to be %s, got %s", 37, "organization_contact.address__lat", columns[37])
		}

		if columns[38] != "organization_contact.address__lng" {
			t.Fatalf("expected column %d to be %s, got %s", 38, "organization_contact.address__lng", columns[38])
		}

		if columns[39] != "organization_contact.address__note" {
			t.Fatalf("expected column %d to be %s, got %s", 39, "organization_contact.address__note", columns[39])
		}

		if columns[40] != "organization_contact.address__created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 40, "organization_contact.address__created_at", columns[40])
		}

		if columns[41] != "organization_contact.address__updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 41, "organization_contact.address__updated_at", columns[41])
		}

		if columns[42] != "organization_contact.address.country__id" {
			t.Fatalf("expected column %d to be %s, got %s", 42, "organization_contact.address.country__id", columns[42])
		}

		if columns[43] != "organization_contact.address.country__name" {
			t.Fatalf("expected column %d to be %s, got %s", 43, "organization_contact.address.country__name", columns[43])
		}

		if columns[44] != "organization_contact.address.country__iso_alpha2" {
			t.Fatalf("expected column %d to be %s, got %s", 44, "organization_contact.address.country__iso_alpha2", columns[44])
		}

		if columns[45] != "organization_contact.address.country__iso_alpha3" {
			t.Fatalf("expected column %d to be %s, got %s", 45, "organization_contact.address.country__iso_alpha3", columns[45])
		}

		if columns[46] != "organization_contact.address.country__iso_numeric" {
			t.Fatalf("expected column %d to be %s, got %s", 46, "organization_contact.address.country__iso_numeric", columns[46])
		}

		if columns[47] != "organization_contact.address.country__created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 47, "organization_contact.address.country__created_at", columns[47])
		}

		if columns[48] != "organization_contact.address.country__updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 48, "organization_contact.address.country__updated_at", columns[48])
		}
	})
}
