// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var AnimalPhotoErrors = &animalPhotoErrors{
	ErrUniquePkAnimalPhotoId: &UniqueConstraintError{
		schema:  "",
		table:   "animal_photo",
		columns: []string{"id"},
		s:       "pk_animal_photo_id",
	},
}

type animalPhotoErrors struct {
	ErrUniquePkAnimalPhotoId *UniqueConstraintError
}
