// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var AnimalBreedErrors = &animalBreedErrors{
	ErrUniquePkAnimalBreedAnimalIdBreedId: &UniqueConstraintError{
		schema:  "",
		table:   "animal_breed",
		columns: []string{"animal_id", "breed_id"},
		s:       "pk_animal_breed_animal_id_breed_id",
	},
}

type animalBreedErrors struct {
	ErrUniquePkAnimalBreedAnimalIdBreedId *UniqueConstraintError
}
