// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var AnimalVideoErrors = &animalVideoErrors{
	ErrUniquePkAnimalVideoId: &UniqueConstraintError{
		schema:  "",
		table:   "animal_video",
		columns: []string{"id"},
		s:       "pk_animal_video_id",
	},
}

type animalVideoErrors struct {
	ErrUniquePkAnimalVideoId *UniqueConstraintError
}
