// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

import (
	"context"
	"errors"
	"testing"

	factory "github.com/dankobg/fluffly/db/dbfactory"
	models "github.com/dankobg/fluffly/db/dbmodel"
	"github.com/stephenafamo/bob"
)

func TestAnimalTypeUniqueConstraintErrors(t *testing.T) {
	if testDB == nil {
		t.Skip("No database connection provided")
	}

	f := factory.New()
	tests := []struct {
		name         string
		expectedErr  *UniqueConstraintError
		conflictMods func(context.Context, *testing.T, bob.Executor, *models.AnimalType) factory.AnimalTypeModSlice
	}{
		{
			name:        "ErrUniquePkAnimalTypeId",
			expectedErr: AnimalTypeErrors.ErrUniquePkAnimalTypeId,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.AnimalType) factory.AnimalTypeModSlice {
				shouldUpdate := false
				updateMods := make(factory.AnimalTypeModSlice, 0, 1)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewAnimalTypeWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.AnimalTypeModSlice{
					factory.AnimalTypeMods.ID(obj.ID),
				}
			},
		},
		{
			name:        "ErrUniqueAnimalTypeNameKey",
			expectedErr: AnimalTypeErrors.ErrUniqueAnimalTypeNameKey,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.AnimalType) factory.AnimalTypeModSlice {
				shouldUpdate := false
				updateMods := make(factory.AnimalTypeModSlice, 0, 1)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewAnimalTypeWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.AnimalTypeModSlice{
					factory.AnimalTypeMods.Name(obj.Name),
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancel := context.WithCancel(t.Context())
			t.Cleanup(cancel)

			tx, err := testDB.Begin(ctx)
			if err != nil {
				t.Fatalf("Couldn't start database transaction: %v", err)
			}

			defer func() {
				if err := tx.Rollback(ctx); err != nil {
					t.Fatalf("Error rolling back transaction: %v", err)
				}
			}()

			var exec bob.Executor = tx

			obj, err := f.NewAnimalTypeWithContext(ctx, factory.AnimalTypeMods.WithParentsCascading()).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			obj2, err := f.NewAnimalTypeWithContext(ctx).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			err = obj2.Update(ctx, exec, f.NewAnimalTypeWithContext(ctx, tt.conflictMods(ctx, t, exec, obj)...).BuildSetter())
			if !errors.Is(ErrUniqueConstraint, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !errors.Is(tt.expectedErr, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
			if !ErrUniqueConstraint.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !tt.expectedErr.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
		})
	}
}
