// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CountryErrors = &countryErrors{
	ErrUniquePkCountryId: &UniqueConstraintError{
		schema:  "",
		table:   "country",
		columns: []string{"id"},
		s:       "pk_country_id",
	},

	ErrUniqueUqCountryIsoAlpha2: &UniqueConstraintError{
		schema:  "",
		table:   "country",
		columns: []string{"iso_alpha2"},
		s:       "uq_country_iso_alpha2",
	},

	ErrUniqueUqCountryIsoAlpha3: &UniqueConstraintError{
		schema:  "",
		table:   "country",
		columns: []string{"iso_alpha3"},
		s:       "uq_country_iso_alpha3",
	},

	ErrUniqueUqCountryIsoNumeric: &UniqueConstraintError{
		schema:  "",
		table:   "country",
		columns: []string{"iso_numeric"},
		s:       "uq_country_iso_numeric",
	},

	ErrUniqueUqCountryName: &UniqueConstraintError{
		schema:  "",
		table:   "country",
		columns: []string{"name"},
		s:       "uq_country_name",
	},
}

type countryErrors struct {
	ErrUniquePkCountryId *UniqueConstraintError

	ErrUniqueUqCountryIsoAlpha2 *UniqueConstraintError

	ErrUniqueUqCountryIsoAlpha3 *UniqueConstraintError

	ErrUniqueUqCountryIsoNumeric *UniqueConstraintError

	ErrUniqueUqCountryName *UniqueConstraintError
}
