// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var OrganizationWorkHourErrors = &organizationWorkHourErrors{
	ErrUniquePkOrganizationWorkHourId: &UniqueConstraintError{
		schema:  "",
		table:   "organization_work_hour",
		columns: []string{"id"},
		s:       "pk_organization_work_hour_id",
	},

	ErrUniqueUqOrganizationWorkHourOrganizationId: &UniqueConstraintError{
		schema:  "",
		table:   "organization_work_hour",
		columns: []string{"organization_id"},
		s:       "uq_organization_work_hour_organization_id",
	},
}

type organizationWorkHourErrors struct {
	ErrUniquePkOrganizationWorkHourId *UniqueConstraintError

	ErrUniqueUqOrganizationWorkHourOrganizationId *UniqueConstraintError
}
