// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var UserErrors = &userErrors{
	ErrUniquePkUserId: &UniqueConstraintError{
		schema:  "",
		table:   "user",
		columns: []string{"id"},
		s:       "pk_user_id",
	},
}

type userErrors struct {
	ErrUniquePkUserId *UniqueConstraintError
}
