// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Address is an object representing the database table.
type Address struct {
	ID            int64                     `db:"id,pk,generated" `
	CountryID     int64                     `db:"country_id" `
	UnitNumber    null.Val[string]          `db:"unit_number" `
	StreetNumber  null.Val[string]          `db:"street_number" `
	StreetAddress string                    `db:"street_address" `
	City          string                    `db:"city" `
	Region        null.Val[string]          `db:"region" `
	PostalCode    null.Val[string]          `db:"postal_code" `
	Lat           null.Val[decimal.Decimal] `db:"lat" `
	LNG           null.Val[decimal.Decimal] `db:"lng" `
	Note          null.Val[string]          `db:"note" `
	CreatedAt     time.Time                 `db:"created_at" `
	UpdatedAt     time.Time                 `db:"updated_at" `

	R addressR `db:"-" `
}

// AddressSlice is an alias for a slice of pointers to Address.
// This should almost always be used instead of []*Address.
type AddressSlice []*Address

// Addresses contains methods to work with the address table
var Addresses = psql.NewTablex[*Address, AddressSlice, *AddressSetter]("", "address", buildAddressColumns("address"))

// AddressesQuery is a query on the address table
type AddressesQuery = *psql.ViewQuery[*Address, AddressSlice]

// addressR is where relationships are stored.
type addressR struct {
	Country              *Country                 // address.fk_address_country_id
	OrganizationContacts OrganizationContactSlice // organization_contact.fk_organization_contact_address_id
	UserContacts         UserContactSlice         // user_contact.fk_user_contact_address_id
}

func buildAddressColumns(alias string) addressColumns {
	return addressColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "country_id", "unit_number", "street_number", "street_address", "city", "region", "postal_code", "lat", "lng", "note", "created_at", "updated_at",
		).WithParent("address"),
		tableAlias:    alias,
		ID:            psql.Quote(alias, "id"),
		CountryID:     psql.Quote(alias, "country_id"),
		UnitNumber:    psql.Quote(alias, "unit_number"),
		StreetNumber:  psql.Quote(alias, "street_number"),
		StreetAddress: psql.Quote(alias, "street_address"),
		City:          psql.Quote(alias, "city"),
		Region:        psql.Quote(alias, "region"),
		PostalCode:    psql.Quote(alias, "postal_code"),
		Lat:           psql.Quote(alias, "lat"),
		LNG:           psql.Quote(alias, "lng"),
		Note:          psql.Quote(alias, "note"),
		CreatedAt:     psql.Quote(alias, "created_at"),
		UpdatedAt:     psql.Quote(alias, "updated_at"),
	}
}

type addressColumns struct {
	expr.ColumnsExpr
	tableAlias    string
	ID            psql.Expression
	CountryID     psql.Expression
	UnitNumber    psql.Expression
	StreetNumber  psql.Expression
	StreetAddress psql.Expression
	City          psql.Expression
	Region        psql.Expression
	PostalCode    psql.Expression
	Lat           psql.Expression
	LNG           psql.Expression
	Note          psql.Expression
	CreatedAt     psql.Expression
	UpdatedAt     psql.Expression
}

func (c addressColumns) Alias() string {
	return c.tableAlias
}

func (addressColumns) AliasedAs(alias string) addressColumns {
	return buildAddressColumns(alias)
}

// AddressSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type AddressSetter struct {
	CountryID     omit.Val[int64]               `db:"country_id" `
	UnitNumber    omitnull.Val[string]          `db:"unit_number" `
	StreetNumber  omitnull.Val[string]          `db:"street_number" `
	StreetAddress omit.Val[string]              `db:"street_address" `
	City          omit.Val[string]              `db:"city" `
	Region        omitnull.Val[string]          `db:"region" `
	PostalCode    omitnull.Val[string]          `db:"postal_code" `
	Lat           omitnull.Val[decimal.Decimal] `db:"lat" `
	LNG           omitnull.Val[decimal.Decimal] `db:"lng" `
	Note          omitnull.Val[string]          `db:"note" `
	CreatedAt     omit.Val[time.Time]           `db:"created_at" `
	UpdatedAt     omit.Val[time.Time]           `db:"updated_at" `
}

func (s AddressSetter) SetColumns() []string {
	vals := make([]string, 0, 12)
	if s.CountryID.IsValue() {
		vals = append(vals, "country_id")
	}
	if !s.UnitNumber.IsUnset() {
		vals = append(vals, "unit_number")
	}
	if !s.StreetNumber.IsUnset() {
		vals = append(vals, "street_number")
	}
	if s.StreetAddress.IsValue() {
		vals = append(vals, "street_address")
	}
	if s.City.IsValue() {
		vals = append(vals, "city")
	}
	if !s.Region.IsUnset() {
		vals = append(vals, "region")
	}
	if !s.PostalCode.IsUnset() {
		vals = append(vals, "postal_code")
	}
	if !s.Lat.IsUnset() {
		vals = append(vals, "lat")
	}
	if !s.LNG.IsUnset() {
		vals = append(vals, "lng")
	}
	if !s.Note.IsUnset() {
		vals = append(vals, "note")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s AddressSetter) Overwrite(t *Address) {
	if s.CountryID.IsValue() {
		t.CountryID = s.CountryID.MustGet()
	}
	if !s.UnitNumber.IsUnset() {
		t.UnitNumber = s.UnitNumber.MustGetNull()
	}
	if !s.StreetNumber.IsUnset() {
		t.StreetNumber = s.StreetNumber.MustGetNull()
	}
	if s.StreetAddress.IsValue() {
		t.StreetAddress = s.StreetAddress.MustGet()
	}
	if s.City.IsValue() {
		t.City = s.City.MustGet()
	}
	if !s.Region.IsUnset() {
		t.Region = s.Region.MustGetNull()
	}
	if !s.PostalCode.IsUnset() {
		t.PostalCode = s.PostalCode.MustGetNull()
	}
	if !s.Lat.IsUnset() {
		t.Lat = s.Lat.MustGetNull()
	}
	if !s.LNG.IsUnset() {
		t.LNG = s.LNG.MustGetNull()
	}
	if !s.Note.IsUnset() {
		t.Note = s.Note.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *AddressSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Addresses.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 12)
		if s.CountryID.IsValue() {
			vals[0] = psql.Arg(s.CountryID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if !s.UnitNumber.IsUnset() {
			vals[1] = psql.Arg(s.UnitNumber.MustGetNull())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if !s.StreetNumber.IsUnset() {
			vals[2] = psql.Arg(s.StreetNumber.MustGetNull())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.StreetAddress.IsValue() {
			vals[3] = psql.Arg(s.StreetAddress.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.City.IsValue() {
			vals[4] = psql.Arg(s.City.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.Region.IsUnset() {
			vals[5] = psql.Arg(s.Region.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if !s.PostalCode.IsUnset() {
			vals[6] = psql.Arg(s.PostalCode.MustGetNull())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if !s.Lat.IsUnset() {
			vals[7] = psql.Arg(s.Lat.MustGetNull())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.LNG.IsUnset() {
			vals[8] = psql.Arg(s.LNG.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if !s.Note.IsUnset() {
			vals[9] = psql.Arg(s.Note.MustGetNull())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[10] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[10] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[11] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[11] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s AddressSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s AddressSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 12)

	if s.CountryID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "country_id")...),
			psql.Arg(s.CountryID),
		}})
	}

	if !s.UnitNumber.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "unit_number")...),
			psql.Arg(s.UnitNumber),
		}})
	}

	if !s.StreetNumber.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "street_number")...),
			psql.Arg(s.StreetNumber),
		}})
	}

	if s.StreetAddress.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "street_address")...),
			psql.Arg(s.StreetAddress),
		}})
	}

	if s.City.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "city")...),
			psql.Arg(s.City),
		}})
	}

	if !s.Region.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "region")...),
			psql.Arg(s.Region),
		}})
	}

	if !s.PostalCode.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "postal_code")...),
			psql.Arg(s.PostalCode),
		}})
	}

	if !s.Lat.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lat")...),
			psql.Arg(s.Lat),
		}})
	}

	if !s.LNG.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "lng")...),
			psql.Arg(s.LNG),
		}})
	}

	if !s.Note.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "note")...),
			psql.Arg(s.Note),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindAddress retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAddress(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Address, error) {
	if len(cols) == 0 {
		return Addresses.Query(
			sm.Where(Addresses.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Addresses.Query(
		sm.Where(Addresses.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Addresses.Columns.Only(cols...)),
	).One(ctx, exec)
}

// AddressExists checks the presence of a single record by primary key
func AddressExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Addresses.Query(
		sm.Where(Addresses.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Address is retrieved from the database
func (o *Address) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Addresses.AfterSelectHooks.RunHooks(ctx, exec, AddressSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Addresses.AfterInsertHooks.RunHooks(ctx, exec, AddressSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Addresses.AfterUpdateHooks.RunHooks(ctx, exec, AddressSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Addresses.AfterDeleteHooks.RunHooks(ctx, exec, AddressSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Address
func (o *Address) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Address) pkEQ() dialect.Expression {
	return psql.Quote("address", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Address
func (o *Address) Update(ctx context.Context, exec bob.Executor, s *AddressSetter) error {
	v, err := Addresses.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Address record with an executor
func (o *Address) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Addresses.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Address using the executor
func (o *Address) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Addresses.Query(
		sm.Where(Addresses.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after AddressSlice is retrieved from the database
func (o AddressSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Addresses.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Addresses.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Addresses.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Addresses.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o AddressSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("address", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o AddressSlice) copyMatchingRows(from ...*Address) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o AddressSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Addresses.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Address:
				o.copyMatchingRows(retrieved)
			case []*Address:
				o.copyMatchingRows(retrieved...)
			case AddressSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Address or a slice of Address
				// then run the AfterUpdateHooks on the slice
				_, err = Addresses.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o AddressSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Addresses.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Address:
				o.copyMatchingRows(retrieved)
			case []*Address:
				o.copyMatchingRows(retrieved...)
			case AddressSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Address or a slice of Address
				// then run the AfterDeleteHooks on the slice
				_, err = Addresses.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o AddressSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals AddressSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Addresses.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o AddressSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Addresses.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o AddressSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Addresses.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Country starts a query for related objects on country
func (o *Address) Country(mods ...bob.Mod[*dialect.SelectQuery]) CountriesQuery {
	return Countries.Query(append(mods,
		sm.Where(Countries.Columns.ID.EQ(psql.Arg(o.CountryID))),
	)...)
}

func (os AddressSlice) Country(mods ...bob.Mod[*dialect.SelectQuery]) CountriesQuery {
	pkCountryID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkCountryID = append(pkCountryID, o.CountryID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkCountryID), "bigint[]")),
	))

	return Countries.Query(append(mods,
		sm.Where(psql.Group(Countries.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// OrganizationContacts starts a query for related objects on organization_contact
func (o *Address) OrganizationContacts(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationContactsQuery {
	return OrganizationContacts.Query(append(mods,
		sm.Where(OrganizationContacts.Columns.AddressID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AddressSlice) OrganizationContacts(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationContactsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return OrganizationContacts.Query(append(mods,
		sm.Where(psql.Group(OrganizationContacts.Columns.AddressID).OP("IN", PKArgExpr)),
	)...)
}

// UserContacts starts a query for related objects on user_contact
func (o *Address) UserContacts(mods ...bob.Mod[*dialect.SelectQuery]) UserContactsQuery {
	return UserContacts.Query(append(mods,
		sm.Where(UserContacts.Columns.AddressID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AddressSlice) UserContacts(mods ...bob.Mod[*dialect.SelectQuery]) UserContactsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return UserContacts.Query(append(mods,
		sm.Where(psql.Group(UserContacts.Columns.AddressID).OP("IN", PKArgExpr)),
	)...)
}

func attachAddressCountry0(ctx context.Context, exec bob.Executor, count int, address0 *Address, country1 *Country) (*Address, error) {
	setter := &AddressSetter{
		CountryID: omit.From(country1.ID),
	}

	err := address0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAddressCountry0: %w", err)
	}

	return address0, nil
}

func (address0 *Address) InsertCountry(ctx context.Context, exec bob.Executor, related *CountrySetter) error {
	country1, err := Countries.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachAddressCountry0(ctx, exec, 1, address0, country1)
	if err != nil {
		return err
	}

	address0.R.Country = country1

	country1.R.Addresses = append(country1.R.Addresses, address0)

	return nil
}

func (address0 *Address) AttachCountry(ctx context.Context, exec bob.Executor, country1 *Country) error {
	var err error

	_, err = attachAddressCountry0(ctx, exec, 1, address0, country1)
	if err != nil {
		return err
	}

	address0.R.Country = country1

	country1.R.Addresses = append(country1.R.Addresses, address0)

	return nil
}

func insertAddressOrganizationContacts0(ctx context.Context, exec bob.Executor, organizationContacts1 []*OrganizationContactSetter, address0 *Address) (OrganizationContactSlice, error) {
	for i := range organizationContacts1 {
		organizationContacts1[i].AddressID = omit.From(address0.ID)
	}

	ret, err := OrganizationContacts.Insert(bob.ToMods(organizationContacts1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAddressOrganizationContacts0: %w", err)
	}

	return ret, nil
}

func attachAddressOrganizationContacts0(ctx context.Context, exec bob.Executor, count int, organizationContacts1 OrganizationContactSlice, address0 *Address) (OrganizationContactSlice, error) {
	setter := &OrganizationContactSetter{
		AddressID: omit.From(address0.ID),
	}

	err := organizationContacts1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAddressOrganizationContacts0: %w", err)
	}

	return organizationContacts1, nil
}

func (address0 *Address) InsertOrganizationContacts(ctx context.Context, exec bob.Executor, related ...*OrganizationContactSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	organizationContacts1, err := insertAddressOrganizationContacts0(ctx, exec, related, address0)
	if err != nil {
		return err
	}

	address0.R.OrganizationContacts = append(address0.R.OrganizationContacts, organizationContacts1...)

	for _, rel := range organizationContacts1 {
		rel.R.Address = address0
	}
	return nil
}

func (address0 *Address) AttachOrganizationContacts(ctx context.Context, exec bob.Executor, related ...*OrganizationContact) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	organizationContacts1 := OrganizationContactSlice(related)

	_, err = attachAddressOrganizationContacts0(ctx, exec, len(related), organizationContacts1, address0)
	if err != nil {
		return err
	}

	address0.R.OrganizationContacts = append(address0.R.OrganizationContacts, organizationContacts1...)

	for _, rel := range related {
		rel.R.Address = address0
	}

	return nil
}

func insertAddressUserContacts0(ctx context.Context, exec bob.Executor, userContacts1 []*UserContactSetter, address0 *Address) (UserContactSlice, error) {
	for i := range userContacts1 {
		userContacts1[i].AddressID = omit.From(address0.ID)
	}

	ret, err := UserContacts.Insert(bob.ToMods(userContacts1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAddressUserContacts0: %w", err)
	}

	return ret, nil
}

func attachAddressUserContacts0(ctx context.Context, exec bob.Executor, count int, userContacts1 UserContactSlice, address0 *Address) (UserContactSlice, error) {
	setter := &UserContactSetter{
		AddressID: omit.From(address0.ID),
	}

	err := userContacts1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAddressUserContacts0: %w", err)
	}

	return userContacts1, nil
}

func (address0 *Address) InsertUserContacts(ctx context.Context, exec bob.Executor, related ...*UserContactSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	userContacts1, err := insertAddressUserContacts0(ctx, exec, related, address0)
	if err != nil {
		return err
	}

	address0.R.UserContacts = append(address0.R.UserContacts, userContacts1...)

	for _, rel := range userContacts1 {
		rel.R.Address = address0
	}
	return nil
}

func (address0 *Address) AttachUserContacts(ctx context.Context, exec bob.Executor, related ...*UserContact) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	userContacts1 := UserContactSlice(related)

	_, err = attachAddressUserContacts0(ctx, exec, len(related), userContacts1, address0)
	if err != nil {
		return err
	}

	address0.R.UserContacts = append(address0.R.UserContacts, userContacts1...)

	for _, rel := range related {
		rel.R.Address = address0
	}

	return nil
}

type addressWhere[Q psql.Filterable] struct {
	ID            psql.WhereMod[Q, int64]
	CountryID     psql.WhereMod[Q, int64]
	UnitNumber    psql.WhereNullMod[Q, string]
	StreetNumber  psql.WhereNullMod[Q, string]
	StreetAddress psql.WhereMod[Q, string]
	City          psql.WhereMod[Q, string]
	Region        psql.WhereNullMod[Q, string]
	PostalCode    psql.WhereNullMod[Q, string]
	Lat           psql.WhereNullMod[Q, decimal.Decimal]
	LNG           psql.WhereNullMod[Q, decimal.Decimal]
	Note          psql.WhereNullMod[Q, string]
	CreatedAt     psql.WhereMod[Q, time.Time]
	UpdatedAt     psql.WhereMod[Q, time.Time]
}

func (addressWhere[Q]) AliasedAs(alias string) addressWhere[Q] {
	return buildAddressWhere[Q](buildAddressColumns(alias))
}

func buildAddressWhere[Q psql.Filterable](cols addressColumns) addressWhere[Q] {
	return addressWhere[Q]{
		ID:            psql.Where[Q, int64](cols.ID),
		CountryID:     psql.Where[Q, int64](cols.CountryID),
		UnitNumber:    psql.WhereNull[Q, string](cols.UnitNumber),
		StreetNumber:  psql.WhereNull[Q, string](cols.StreetNumber),
		StreetAddress: psql.Where[Q, string](cols.StreetAddress),
		City:          psql.Where[Q, string](cols.City),
		Region:        psql.WhereNull[Q, string](cols.Region),
		PostalCode:    psql.WhereNull[Q, string](cols.PostalCode),
		Lat:           psql.WhereNull[Q, decimal.Decimal](cols.Lat),
		LNG:           psql.WhereNull[Q, decimal.Decimal](cols.LNG),
		Note:          psql.WhereNull[Q, string](cols.Note),
		CreatedAt:     psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:     psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Address) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Country":
		rel, ok := retrieved.(*Country)
		if !ok {
			return fmt.Errorf("address cannot load %T as %q", retrieved, name)
		}

		o.R.Country = rel

		if rel != nil {
			rel.R.Addresses = AddressSlice{o}
		}
		return nil
	case "OrganizationContacts":
		rels, ok := retrieved.(OrganizationContactSlice)
		if !ok {
			return fmt.Errorf("address cannot load %T as %q", retrieved, name)
		}

		o.R.OrganizationContacts = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Address = o
			}
		}
		return nil
	case "UserContacts":
		rels, ok := retrieved.(UserContactSlice)
		if !ok {
			return fmt.Errorf("address cannot load %T as %q", retrieved, name)
		}

		o.R.UserContacts = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Address = o
			}
		}
		return nil
	default:
		return fmt.Errorf("address has no relationship %q", name)
	}
}

type addressPreloader struct {
	Country func(...psql.PreloadOption) psql.Preloader
}

func buildAddressPreloader() addressPreloader {
	return addressPreloader{
		Country: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Country, CountrySlice](psql.PreloadRel{
				Name: "Country",
				Sides: []psql.PreloadSide{
					{
						From:        Addresses,
						To:          Countries,
						FromColumns: []string{"country_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Countries.Columns.Names(), opts...)
		},
	}
}

type addressThenLoader[Q orm.Loadable] struct {
	Country              func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	OrganizationContacts func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UserContacts         func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildAddressThenLoader[Q orm.Loadable]() addressThenLoader[Q] {
	type CountryLoadInterface interface {
		LoadCountry(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrganizationContactsLoadInterface interface {
		LoadOrganizationContacts(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UserContactsLoadInterface interface {
		LoadUserContacts(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return addressThenLoader[Q]{
		Country: thenLoadBuilder[Q](
			"Country",
			func(ctx context.Context, exec bob.Executor, retrieved CountryLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountry(ctx, exec, mods...)
			},
		),
		OrganizationContacts: thenLoadBuilder[Q](
			"OrganizationContacts",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationContactsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganizationContacts(ctx, exec, mods...)
			},
		),
		UserContacts: thenLoadBuilder[Q](
			"UserContacts",
			func(ctx context.Context, exec bob.Executor, retrieved UserContactsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUserContacts(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountry loads the address's Country into the .R struct
func (o *Address) LoadCountry(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Country = nil

	related, err := o.Country(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Addresses = AddressSlice{o}

	o.R.Country = related
	return nil
}

// LoadCountry loads the address's Country into the .R struct
func (os AddressSlice) LoadCountry(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	countries, err := os.Country(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range countries {

			if !(o.CountryID == rel.ID) {
				continue
			}

			rel.R.Addresses = append(rel.R.Addresses, o)

			o.R.Country = rel
			break
		}
	}

	return nil
}

// LoadOrganizationContacts loads the address's OrganizationContacts into the .R struct
func (o *Address) LoadOrganizationContacts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OrganizationContacts = nil

	related, err := o.OrganizationContacts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Address = o
	}

	o.R.OrganizationContacts = related
	return nil
}

// LoadOrganizationContacts loads the address's OrganizationContacts into the .R struct
func (os AddressSlice) LoadOrganizationContacts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizationContacts, err := os.OrganizationContacts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.OrganizationContacts = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range organizationContacts {

			if !(o.ID == rel.AddressID) {
				continue
			}

			rel.R.Address = o

			o.R.OrganizationContacts = append(o.R.OrganizationContacts, rel)
		}
	}

	return nil
}

// LoadUserContacts loads the address's UserContacts into the .R struct
func (o *Address) LoadUserContacts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UserContacts = nil

	related, err := o.UserContacts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Address = o
	}

	o.R.UserContacts = related
	return nil
}

// LoadUserContacts loads the address's UserContacts into the .R struct
func (os AddressSlice) LoadUserContacts(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	userContacts, err := os.UserContacts(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.UserContacts = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range userContacts {

			if !(o.ID == rel.AddressID) {
				continue
			}

			rel.R.Address = o

			o.R.UserContacts = append(o.R.UserContacts, rel)
		}
	}

	return nil
}

type addressJoins[Q dialect.Joinable] struct {
	typ                  string
	Country              modAs[Q, countryColumns]
	OrganizationContacts modAs[Q, organizationContactColumns]
	UserContacts         modAs[Q, userContactColumns]
}

func (j addressJoins[Q]) aliasedAs(alias string) addressJoins[Q] {
	return buildAddressJoins[Q](buildAddressColumns(alias), j.typ)
}

func buildAddressJoins[Q dialect.Joinable](cols addressColumns, typ string) addressJoins[Q] {
	return addressJoins[Q]{
		typ: typ,
		Country: modAs[Q, countryColumns]{
			c: Countries.Columns,
			f: func(to countryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Countries.Name().As(to.Alias())).On(
						to.ID.EQ(cols.CountryID),
					))
				}

				return mods
			},
		},
		OrganizationContacts: modAs[Q, organizationContactColumns]{
			c: OrganizationContacts.Columns,
			f: func(to organizationContactColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, OrganizationContacts.Name().As(to.Alias())).On(
						to.AddressID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		UserContacts: modAs[Q, userContactColumns]{
			c: UserContacts.Columns,
			f: func(to userContactColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, UserContacts.Name().As(to.Alias())).On(
						to.AddressID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
