// Code generated by BobGen psql v0.40.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Organization is an object representing the database table.
type Organization struct {
	ID               int64            `db:"id,pk,generated" `
	Name             string           `db:"name" `
	Website          null.Val[string] `db:"website" `
	MissionStatement null.Val[string] `db:"mission_statement" `
	AdoptionPolicy   null.Val[string] `db:"adoption_policy" `
	AdoptionURL      null.Val[string] `db:"adoption_url" `
	Distance         null.Val[string] `db:"distance" `
	CreatedAt        time.Time        `db:"created_at" `
	UpdatedAt        time.Time        `db:"updated_at" `

	R organizationR `db:"-" `
}

// OrganizationSlice is an alias for a slice of pointers to Organization.
// This should almost always be used instead of []*Organization.
type OrganizationSlice []*Organization

// Organizations contains methods to work with the organization table
var Organizations = psql.NewTablex[*Organization, OrganizationSlice, *OrganizationSetter]("", "organization", buildOrganizationColumns("organization"))

// OrganizationsQuery is a query on the organization table
type OrganizationsQuery = *psql.ViewQuery[*Organization, OrganizationSlice]

// organizationR is where relationships are stored.
type organizationR struct {
	Adoptions            AdoptionSlice           // adoption.fk_adoption_organization_id
	Animals              AnimalSlice             // animal.fk_animal_organization_id
	OrganizationContact  *OrganizationContact    // organization_contact.fk_organization_contact_user_id
	OrganizationPhotos   OrganizationPhotoSlice  // organization_photo.fk_organization_photo_organization_id
	OrganizationSocials  OrganizationSocialSlice // organization_social.fk_organization_social_organization_id
	OrganizationWorkHour *OrganizationWorkHour   // organization_work_hour.fk_organization_work_hour_organization_id
}

func buildOrganizationColumns(alias string) organizationColumns {
	return organizationColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "website", "mission_statement", "adoption_policy", "adoption_url", "distance", "created_at", "updated_at",
		).WithParent("organization"),
		tableAlias:       alias,
		ID:               psql.Quote(alias, "id"),
		Name:             psql.Quote(alias, "name"),
		Website:          psql.Quote(alias, "website"),
		MissionStatement: psql.Quote(alias, "mission_statement"),
		AdoptionPolicy:   psql.Quote(alias, "adoption_policy"),
		AdoptionURL:      psql.Quote(alias, "adoption_url"),
		Distance:         psql.Quote(alias, "distance"),
		CreatedAt:        psql.Quote(alias, "created_at"),
		UpdatedAt:        psql.Quote(alias, "updated_at"),
	}
}

type organizationColumns struct {
	expr.ColumnsExpr
	tableAlias       string
	ID               psql.Expression
	Name             psql.Expression
	Website          psql.Expression
	MissionStatement psql.Expression
	AdoptionPolicy   psql.Expression
	AdoptionURL      psql.Expression
	Distance         psql.Expression
	CreatedAt        psql.Expression
	UpdatedAt        psql.Expression
}

func (c organizationColumns) Alias() string {
	return c.tableAlias
}

func (organizationColumns) AliasedAs(alias string) organizationColumns {
	return buildOrganizationColumns(alias)
}

// OrganizationSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type OrganizationSetter struct {
	Name             omit.Val[string]     `db:"name" `
	Website          omitnull.Val[string] `db:"website" `
	MissionStatement omitnull.Val[string] `db:"mission_statement" `
	AdoptionPolicy   omitnull.Val[string] `db:"adoption_policy" `
	AdoptionURL      omitnull.Val[string] `db:"adoption_url" `
	Distance         omitnull.Val[string] `db:"distance" `
	CreatedAt        omit.Val[time.Time]  `db:"created_at" `
	UpdatedAt        omit.Val[time.Time]  `db:"updated_at" `
}

func (s OrganizationSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if !s.Website.IsUnset() {
		vals = append(vals, "website")
	}
	if !s.MissionStatement.IsUnset() {
		vals = append(vals, "mission_statement")
	}
	if !s.AdoptionPolicy.IsUnset() {
		vals = append(vals, "adoption_policy")
	}
	if !s.AdoptionURL.IsUnset() {
		vals = append(vals, "adoption_url")
	}
	if !s.Distance.IsUnset() {
		vals = append(vals, "distance")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s OrganizationSetter) Overwrite(t *Organization) {
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if !s.Website.IsUnset() {
		t.Website = s.Website.MustGetNull()
	}
	if !s.MissionStatement.IsUnset() {
		t.MissionStatement = s.MissionStatement.MustGetNull()
	}
	if !s.AdoptionPolicy.IsUnset() {
		t.AdoptionPolicy = s.AdoptionPolicy.MustGetNull()
	}
	if !s.AdoptionURL.IsUnset() {
		t.AdoptionURL = s.AdoptionURL.MustGetNull()
	}
	if !s.Distance.IsUnset() {
		t.Distance = s.Distance.MustGetNull()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *OrganizationSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Organizations.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.Name.IsValue() {
			vals[0] = psql.Arg(s.Name.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if !s.Website.IsUnset() {
			vals[1] = psql.Arg(s.Website.MustGetNull())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if !s.MissionStatement.IsUnset() {
			vals[2] = psql.Arg(s.MissionStatement.MustGetNull())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.AdoptionPolicy.IsUnset() {
			vals[3] = psql.Arg(s.AdoptionPolicy.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if !s.AdoptionURL.IsUnset() {
			vals[4] = psql.Arg(s.AdoptionURL.MustGetNull())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if !s.Distance.IsUnset() {
			vals[5] = psql.Arg(s.Distance.MustGetNull())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[6] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[7] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s OrganizationSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s OrganizationSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if !s.Website.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "website")...),
			psql.Arg(s.Website),
		}})
	}

	if !s.MissionStatement.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "mission_statement")...),
			psql.Arg(s.MissionStatement),
		}})
	}

	if !s.AdoptionPolicy.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "adoption_policy")...),
			psql.Arg(s.AdoptionPolicy),
		}})
	}

	if !s.AdoptionURL.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "adoption_url")...),
			psql.Arg(s.AdoptionURL),
		}})
	}

	if !s.Distance.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "distance")...),
			psql.Arg(s.Distance),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindOrganization retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindOrganization(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Organization, error) {
	if len(cols) == 0 {
		return Organizations.Query(
			sm.Where(Organizations.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Organizations.Query(
		sm.Where(Organizations.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Organizations.Columns.Only(cols...)),
	).One(ctx, exec)
}

// OrganizationExists checks the presence of a single record by primary key
func OrganizationExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Organizations.Query(
		sm.Where(Organizations.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Organization is retrieved from the database
func (o *Organization) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Organizations.AfterSelectHooks.RunHooks(ctx, exec, OrganizationSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Organizations.AfterInsertHooks.RunHooks(ctx, exec, OrganizationSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Organizations.AfterUpdateHooks.RunHooks(ctx, exec, OrganizationSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Organizations.AfterDeleteHooks.RunHooks(ctx, exec, OrganizationSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Organization
func (o *Organization) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Organization) pkEQ() dialect.Expression {
	return psql.Quote("organization", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Organization
func (o *Organization) Update(ctx context.Context, exec bob.Executor, s *OrganizationSetter) error {
	v, err := Organizations.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Organization record with an executor
func (o *Organization) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Organizations.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Organization using the executor
func (o *Organization) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Organizations.Query(
		sm.Where(Organizations.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after OrganizationSlice is retrieved from the database
func (o OrganizationSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Organizations.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Organizations.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Organizations.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Organizations.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o OrganizationSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("organization", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o OrganizationSlice) copyMatchingRows(from ...*Organization) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o OrganizationSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Organizations.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Organization:
				o.copyMatchingRows(retrieved)
			case []*Organization:
				o.copyMatchingRows(retrieved...)
			case OrganizationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Organization or a slice of Organization
				// then run the AfterUpdateHooks on the slice
				_, err = Organizations.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o OrganizationSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Organizations.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Organization:
				o.copyMatchingRows(retrieved)
			case []*Organization:
				o.copyMatchingRows(retrieved...)
			case OrganizationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Organization or a slice of Organization
				// then run the AfterDeleteHooks on the slice
				_, err = Organizations.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o OrganizationSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals OrganizationSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Organizations.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o OrganizationSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Organizations.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o OrganizationSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Organizations.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Adoptions starts a query for related objects on adoption
func (o *Organization) Adoptions(mods ...bob.Mod[*dialect.SelectQuery]) AdoptionsQuery {
	return Adoptions.Query(append(mods,
		sm.Where(Adoptions.Columns.OrganizationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os OrganizationSlice) Adoptions(mods ...bob.Mod[*dialect.SelectQuery]) AdoptionsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Adoptions.Query(append(mods,
		sm.Where(psql.Group(Adoptions.Columns.OrganizationID).OP("IN", PKArgExpr)),
	)...)
}

// Animals starts a query for related objects on animal
func (o *Organization) Animals(mods ...bob.Mod[*dialect.SelectQuery]) AnimalsQuery {
	return Animals.Query(append(mods,
		sm.Where(Animals.Columns.OrganizationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os OrganizationSlice) Animals(mods ...bob.Mod[*dialect.SelectQuery]) AnimalsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return Animals.Query(append(mods,
		sm.Where(psql.Group(Animals.Columns.OrganizationID).OP("IN", PKArgExpr)),
	)...)
}

// OrganizationContact starts a query for related objects on organization_contact
func (o *Organization) OrganizationContact(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationContactsQuery {
	return OrganizationContacts.Query(append(mods,
		sm.Where(OrganizationContacts.Columns.OrganizationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os OrganizationSlice) OrganizationContact(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationContactsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return OrganizationContacts.Query(append(mods,
		sm.Where(psql.Group(OrganizationContacts.Columns.OrganizationID).OP("IN", PKArgExpr)),
	)...)
}

// OrganizationPhotos starts a query for related objects on organization_photo
func (o *Organization) OrganizationPhotos(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationPhotosQuery {
	return OrganizationPhotos.Query(append(mods,
		sm.Where(OrganizationPhotos.Columns.OrganizationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os OrganizationSlice) OrganizationPhotos(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationPhotosQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return OrganizationPhotos.Query(append(mods,
		sm.Where(psql.Group(OrganizationPhotos.Columns.OrganizationID).OP("IN", PKArgExpr)),
	)...)
}

// OrganizationSocials starts a query for related objects on organization_social
func (o *Organization) OrganizationSocials(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationSocialsQuery {
	return OrganizationSocials.Query(append(mods,
		sm.Where(OrganizationSocials.Columns.OrganizationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os OrganizationSlice) OrganizationSocials(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationSocialsQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return OrganizationSocials.Query(append(mods,
		sm.Where(psql.Group(OrganizationSocials.Columns.OrganizationID).OP("IN", PKArgExpr)),
	)...)
}

// OrganizationWorkHour starts a query for related objects on organization_work_hour
func (o *Organization) OrganizationWorkHour(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationWorkHoursQuery {
	return OrganizationWorkHours.Query(append(mods,
		sm.Where(OrganizationWorkHours.Columns.OrganizationID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os OrganizationSlice) OrganizationWorkHour(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationWorkHoursQuery {
	pkID := make(pgtypes.Array[int64], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "bigint[]")),
	))

	return OrganizationWorkHours.Query(append(mods,
		sm.Where(psql.Group(OrganizationWorkHours.Columns.OrganizationID).OP("IN", PKArgExpr)),
	)...)
}

func insertOrganizationAdoptions0(ctx context.Context, exec bob.Executor, adoptions1 []*AdoptionSetter, organization0 *Organization) (AdoptionSlice, error) {
	for i := range adoptions1 {
		adoptions1[i].OrganizationID = omitnull.From(organization0.ID)
	}

	ret, err := Adoptions.Insert(bob.ToMods(adoptions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertOrganizationAdoptions0: %w", err)
	}

	return ret, nil
}

func attachOrganizationAdoptions0(ctx context.Context, exec bob.Executor, count int, adoptions1 AdoptionSlice, organization0 *Organization) (AdoptionSlice, error) {
	setter := &AdoptionSetter{
		OrganizationID: omitnull.From(organization0.ID),
	}

	err := adoptions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrganizationAdoptions0: %w", err)
	}

	return adoptions1, nil
}

func (organization0 *Organization) InsertAdoptions(ctx context.Context, exec bob.Executor, related ...*AdoptionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	adoptions1, err := insertOrganizationAdoptions0(ctx, exec, related, organization0)
	if err != nil {
		return err
	}

	organization0.R.Adoptions = append(organization0.R.Adoptions, adoptions1...)

	for _, rel := range adoptions1 {
		rel.R.Organization = organization0
	}
	return nil
}

func (organization0 *Organization) AttachAdoptions(ctx context.Context, exec bob.Executor, related ...*Adoption) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	adoptions1 := AdoptionSlice(related)

	_, err = attachOrganizationAdoptions0(ctx, exec, len(related), adoptions1, organization0)
	if err != nil {
		return err
	}

	organization0.R.Adoptions = append(organization0.R.Adoptions, adoptions1...)

	for _, rel := range related {
		rel.R.Organization = organization0
	}

	return nil
}

func insertOrganizationAnimals0(ctx context.Context, exec bob.Executor, animals1 []*AnimalSetter, organization0 *Organization) (AnimalSlice, error) {
	for i := range animals1 {
		animals1[i].OrganizationID = omitnull.From(organization0.ID)
	}

	ret, err := Animals.Insert(bob.ToMods(animals1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertOrganizationAnimals0: %w", err)
	}

	return ret, nil
}

func attachOrganizationAnimals0(ctx context.Context, exec bob.Executor, count int, animals1 AnimalSlice, organization0 *Organization) (AnimalSlice, error) {
	setter := &AnimalSetter{
		OrganizationID: omitnull.From(organization0.ID),
	}

	err := animals1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrganizationAnimals0: %w", err)
	}

	return animals1, nil
}

func (organization0 *Organization) InsertAnimals(ctx context.Context, exec bob.Executor, related ...*AnimalSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	animals1, err := insertOrganizationAnimals0(ctx, exec, related, organization0)
	if err != nil {
		return err
	}

	organization0.R.Animals = append(organization0.R.Animals, animals1...)

	for _, rel := range animals1 {
		rel.R.Organization = organization0
	}
	return nil
}

func (organization0 *Organization) AttachAnimals(ctx context.Context, exec bob.Executor, related ...*Animal) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	animals1 := AnimalSlice(related)

	_, err = attachOrganizationAnimals0(ctx, exec, len(related), animals1, organization0)
	if err != nil {
		return err
	}

	organization0.R.Animals = append(organization0.R.Animals, animals1...)

	for _, rel := range related {
		rel.R.Organization = organization0
	}

	return nil
}

func insertOrganizationOrganizationContact0(ctx context.Context, exec bob.Executor, organizationContact1 *OrganizationContactSetter, organization0 *Organization) (*OrganizationContact, error) {
	organizationContact1.OrganizationID = omit.From(organization0.ID)

	ret, err := OrganizationContacts.Insert(organizationContact1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertOrganizationOrganizationContact0: %w", err)
	}

	return ret, nil
}

func attachOrganizationOrganizationContact0(ctx context.Context, exec bob.Executor, count int, organizationContact1 *OrganizationContact, organization0 *Organization) (*OrganizationContact, error) {
	setter := &OrganizationContactSetter{
		OrganizationID: omit.From(organization0.ID),
	}

	err := organizationContact1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrganizationOrganizationContact0: %w", err)
	}

	return organizationContact1, nil
}

func (organization0 *Organization) InsertOrganizationContact(ctx context.Context, exec bob.Executor, related *OrganizationContactSetter) error {
	organizationContact1, err := insertOrganizationOrganizationContact0(ctx, exec, related, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationContact = organizationContact1

	organizationContact1.R.Organization = organization0

	return nil
}

func (organization0 *Organization) AttachOrganizationContact(ctx context.Context, exec bob.Executor, organizationContact1 *OrganizationContact) error {
	var err error

	_, err = attachOrganizationOrganizationContact0(ctx, exec, 1, organizationContact1, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationContact = organizationContact1

	organizationContact1.R.Organization = organization0

	return nil
}

func insertOrganizationOrganizationPhotos0(ctx context.Context, exec bob.Executor, organizationPhotos1 []*OrganizationPhotoSetter, organization0 *Organization) (OrganizationPhotoSlice, error) {
	for i := range organizationPhotos1 {
		organizationPhotos1[i].OrganizationID = omitnull.From(organization0.ID)
	}

	ret, err := OrganizationPhotos.Insert(bob.ToMods(organizationPhotos1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertOrganizationOrganizationPhotos0: %w", err)
	}

	return ret, nil
}

func attachOrganizationOrganizationPhotos0(ctx context.Context, exec bob.Executor, count int, organizationPhotos1 OrganizationPhotoSlice, organization0 *Organization) (OrganizationPhotoSlice, error) {
	setter := &OrganizationPhotoSetter{
		OrganizationID: omitnull.From(organization0.ID),
	}

	err := organizationPhotos1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrganizationOrganizationPhotos0: %w", err)
	}

	return organizationPhotos1, nil
}

func (organization0 *Organization) InsertOrganizationPhotos(ctx context.Context, exec bob.Executor, related ...*OrganizationPhotoSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	organizationPhotos1, err := insertOrganizationOrganizationPhotos0(ctx, exec, related, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationPhotos = append(organization0.R.OrganizationPhotos, organizationPhotos1...)

	for _, rel := range organizationPhotos1 {
		rel.R.Organization = organization0
	}
	return nil
}

func (organization0 *Organization) AttachOrganizationPhotos(ctx context.Context, exec bob.Executor, related ...*OrganizationPhoto) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	organizationPhotos1 := OrganizationPhotoSlice(related)

	_, err = attachOrganizationOrganizationPhotos0(ctx, exec, len(related), organizationPhotos1, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationPhotos = append(organization0.R.OrganizationPhotos, organizationPhotos1...)

	for _, rel := range related {
		rel.R.Organization = organization0
	}

	return nil
}

func insertOrganizationOrganizationSocials0(ctx context.Context, exec bob.Executor, organizationSocials1 []*OrganizationSocialSetter, organization0 *Organization) (OrganizationSocialSlice, error) {
	for i := range organizationSocials1 {
		organizationSocials1[i].OrganizationID = omit.From(organization0.ID)
	}

	ret, err := OrganizationSocials.Insert(bob.ToMods(organizationSocials1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertOrganizationOrganizationSocials0: %w", err)
	}

	return ret, nil
}

func attachOrganizationOrganizationSocials0(ctx context.Context, exec bob.Executor, count int, organizationSocials1 OrganizationSocialSlice, organization0 *Organization) (OrganizationSocialSlice, error) {
	setter := &OrganizationSocialSetter{
		OrganizationID: omit.From(organization0.ID),
	}

	err := organizationSocials1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrganizationOrganizationSocials0: %w", err)
	}

	return organizationSocials1, nil
}

func (organization0 *Organization) InsertOrganizationSocials(ctx context.Context, exec bob.Executor, related ...*OrganizationSocialSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	organizationSocials1, err := insertOrganizationOrganizationSocials0(ctx, exec, related, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationSocials = append(organization0.R.OrganizationSocials, organizationSocials1...)

	for _, rel := range organizationSocials1 {
		rel.R.Organization = organization0
	}
	return nil
}

func (organization0 *Organization) AttachOrganizationSocials(ctx context.Context, exec bob.Executor, related ...*OrganizationSocial) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	organizationSocials1 := OrganizationSocialSlice(related)

	_, err = attachOrganizationOrganizationSocials0(ctx, exec, len(related), organizationSocials1, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationSocials = append(organization0.R.OrganizationSocials, organizationSocials1...)

	for _, rel := range related {
		rel.R.Organization = organization0
	}

	return nil
}

func insertOrganizationOrganizationWorkHour0(ctx context.Context, exec bob.Executor, organizationWorkHour1 *OrganizationWorkHourSetter, organization0 *Organization) (*OrganizationWorkHour, error) {
	organizationWorkHour1.OrganizationID = omitnull.From(organization0.ID)

	ret, err := OrganizationWorkHours.Insert(organizationWorkHour1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertOrganizationOrganizationWorkHour0: %w", err)
	}

	return ret, nil
}

func attachOrganizationOrganizationWorkHour0(ctx context.Context, exec bob.Executor, count int, organizationWorkHour1 *OrganizationWorkHour, organization0 *Organization) (*OrganizationWorkHour, error) {
	setter := &OrganizationWorkHourSetter{
		OrganizationID: omitnull.From(organization0.ID),
	}

	err := organizationWorkHour1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrganizationOrganizationWorkHour0: %w", err)
	}

	return organizationWorkHour1, nil
}

func (organization0 *Organization) InsertOrganizationWorkHour(ctx context.Context, exec bob.Executor, related *OrganizationWorkHourSetter) error {
	organizationWorkHour1, err := insertOrganizationOrganizationWorkHour0(ctx, exec, related, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationWorkHour = organizationWorkHour1

	organizationWorkHour1.R.Organization = organization0

	return nil
}

func (organization0 *Organization) AttachOrganizationWorkHour(ctx context.Context, exec bob.Executor, organizationWorkHour1 *OrganizationWorkHour) error {
	var err error

	_, err = attachOrganizationOrganizationWorkHour0(ctx, exec, 1, organizationWorkHour1, organization0)
	if err != nil {
		return err
	}

	organization0.R.OrganizationWorkHour = organizationWorkHour1

	organizationWorkHour1.R.Organization = organization0

	return nil
}

type organizationWhere[Q psql.Filterable] struct {
	ID               psql.WhereMod[Q, int64]
	Name             psql.WhereMod[Q, string]
	Website          psql.WhereNullMod[Q, string]
	MissionStatement psql.WhereNullMod[Q, string]
	AdoptionPolicy   psql.WhereNullMod[Q, string]
	AdoptionURL      psql.WhereNullMod[Q, string]
	Distance         psql.WhereNullMod[Q, string]
	CreatedAt        psql.WhereMod[Q, time.Time]
	UpdatedAt        psql.WhereMod[Q, time.Time]
}

func (organizationWhere[Q]) AliasedAs(alias string) organizationWhere[Q] {
	return buildOrganizationWhere[Q](buildOrganizationColumns(alias))
}

func buildOrganizationWhere[Q psql.Filterable](cols organizationColumns) organizationWhere[Q] {
	return organizationWhere[Q]{
		ID:               psql.Where[Q, int64](cols.ID),
		Name:             psql.Where[Q, string](cols.Name),
		Website:          psql.WhereNull[Q, string](cols.Website),
		MissionStatement: psql.WhereNull[Q, string](cols.MissionStatement),
		AdoptionPolicy:   psql.WhereNull[Q, string](cols.AdoptionPolicy),
		AdoptionURL:      psql.WhereNull[Q, string](cols.AdoptionURL),
		Distance:         psql.WhereNull[Q, string](cols.Distance),
		CreatedAt:        psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:        psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Organization) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Adoptions":
		rels, ok := retrieved.(AdoptionSlice)
		if !ok {
			return fmt.Errorf("organization cannot load %T as %q", retrieved, name)
		}

		o.R.Adoptions = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Organization = o
			}
		}
		return nil
	case "Animals":
		rels, ok := retrieved.(AnimalSlice)
		if !ok {
			return fmt.Errorf("organization cannot load %T as %q", retrieved, name)
		}

		o.R.Animals = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Organization = o
			}
		}
		return nil
	case "OrganizationContact":
		rel, ok := retrieved.(*OrganizationContact)
		if !ok {
			return fmt.Errorf("organization cannot load %T as %q", retrieved, name)
		}

		o.R.OrganizationContact = rel

		if rel != nil {
			rel.R.Organization = o
		}
		return nil
	case "OrganizationPhotos":
		rels, ok := retrieved.(OrganizationPhotoSlice)
		if !ok {
			return fmt.Errorf("organization cannot load %T as %q", retrieved, name)
		}

		o.R.OrganizationPhotos = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Organization = o
			}
		}
		return nil
	case "OrganizationSocials":
		rels, ok := retrieved.(OrganizationSocialSlice)
		if !ok {
			return fmt.Errorf("organization cannot load %T as %q", retrieved, name)
		}

		o.R.OrganizationSocials = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Organization = o
			}
		}
		return nil
	case "OrganizationWorkHour":
		rel, ok := retrieved.(*OrganizationWorkHour)
		if !ok {
			return fmt.Errorf("organization cannot load %T as %q", retrieved, name)
		}

		o.R.OrganizationWorkHour = rel

		if rel != nil {
			rel.R.Organization = o
		}
		return nil
	default:
		return fmt.Errorf("organization has no relationship %q", name)
	}
}

type organizationPreloader struct {
	OrganizationContact  func(...psql.PreloadOption) psql.Preloader
	OrganizationWorkHour func(...psql.PreloadOption) psql.Preloader
}

func buildOrganizationPreloader() organizationPreloader {
	return organizationPreloader{
		OrganizationContact: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*OrganizationContact, OrganizationContactSlice](psql.PreloadRel{
				Name: "OrganizationContact",
				Sides: []psql.PreloadSide{
					{
						From:        Organizations,
						To:          OrganizationContacts,
						FromColumns: []string{"id"},
						ToColumns:   []string{"organization_id"},
					},
				},
			}, OrganizationContacts.Columns.Names(), opts...)
		},
		OrganizationWorkHour: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*OrganizationWorkHour, OrganizationWorkHourSlice](psql.PreloadRel{
				Name: "OrganizationWorkHour",
				Sides: []psql.PreloadSide{
					{
						From:        Organizations,
						To:          OrganizationWorkHours,
						FromColumns: []string{"id"},
						ToColumns:   []string{"organization_id"},
					},
				},
			}, OrganizationWorkHours.Columns.Names(), opts...)
		},
	}
}

type organizationThenLoader[Q orm.Loadable] struct {
	Adoptions            func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Animals              func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	OrganizationContact  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	OrganizationPhotos   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	OrganizationSocials  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	OrganizationWorkHour func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildOrganizationThenLoader[Q orm.Loadable]() organizationThenLoader[Q] {
	type AdoptionsLoadInterface interface {
		LoadAdoptions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type AnimalsLoadInterface interface {
		LoadAnimals(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrganizationContactLoadInterface interface {
		LoadOrganizationContact(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrganizationPhotosLoadInterface interface {
		LoadOrganizationPhotos(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrganizationSocialsLoadInterface interface {
		LoadOrganizationSocials(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrganizationWorkHourLoadInterface interface {
		LoadOrganizationWorkHour(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return organizationThenLoader[Q]{
		Adoptions: thenLoadBuilder[Q](
			"Adoptions",
			func(ctx context.Context, exec bob.Executor, retrieved AdoptionsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAdoptions(ctx, exec, mods...)
			},
		),
		Animals: thenLoadBuilder[Q](
			"Animals",
			func(ctx context.Context, exec bob.Executor, retrieved AnimalsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAnimals(ctx, exec, mods...)
			},
		),
		OrganizationContact: thenLoadBuilder[Q](
			"OrganizationContact",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationContactLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganizationContact(ctx, exec, mods...)
			},
		),
		OrganizationPhotos: thenLoadBuilder[Q](
			"OrganizationPhotos",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationPhotosLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganizationPhotos(ctx, exec, mods...)
			},
		),
		OrganizationSocials: thenLoadBuilder[Q](
			"OrganizationSocials",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationSocialsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganizationSocials(ctx, exec, mods...)
			},
		),
		OrganizationWorkHour: thenLoadBuilder[Q](
			"OrganizationWorkHour",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationWorkHourLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganizationWorkHour(ctx, exec, mods...)
			},
		),
	}
}

// LoadAdoptions loads the organization's Adoptions into the .R struct
func (o *Organization) LoadAdoptions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Adoptions = nil

	related, err := o.Adoptions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Organization = o
	}

	o.R.Adoptions = related
	return nil
}

// LoadAdoptions loads the organization's Adoptions into the .R struct
func (os OrganizationSlice) LoadAdoptions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	adoptions, err := os.Adoptions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Adoptions = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range adoptions {

			if !rel.OrganizationID.IsValue() {
				continue
			}
			if !(rel.OrganizationID.IsValue() && o.ID == rel.OrganizationID.MustGet()) {
				continue
			}

			rel.R.Organization = o

			o.R.Adoptions = append(o.R.Adoptions, rel)
		}
	}

	return nil
}

// LoadAnimals loads the organization's Animals into the .R struct
func (o *Organization) LoadAnimals(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Animals = nil

	related, err := o.Animals(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Organization = o
	}

	o.R.Animals = related
	return nil
}

// LoadAnimals loads the organization's Animals into the .R struct
func (os OrganizationSlice) LoadAnimals(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	animals, err := os.Animals(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Animals = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range animals {

			if !rel.OrganizationID.IsValue() {
				continue
			}
			if !(rel.OrganizationID.IsValue() && o.ID == rel.OrganizationID.MustGet()) {
				continue
			}

			rel.R.Organization = o

			o.R.Animals = append(o.R.Animals, rel)
		}
	}

	return nil
}

// LoadOrganizationContact loads the organization's OrganizationContact into the .R struct
func (o *Organization) LoadOrganizationContact(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OrganizationContact = nil

	related, err := o.OrganizationContact(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Organization = o

	o.R.OrganizationContact = related
	return nil
}

// LoadOrganizationContact loads the organization's OrganizationContact into the .R struct
func (os OrganizationSlice) LoadOrganizationContact(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizationContacts, err := os.OrganizationContact(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range organizationContacts {

			if !(o.ID == rel.OrganizationID) {
				continue
			}

			rel.R.Organization = o

			o.R.OrganizationContact = rel
			break
		}
	}

	return nil
}

// LoadOrganizationPhotos loads the organization's OrganizationPhotos into the .R struct
func (o *Organization) LoadOrganizationPhotos(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OrganizationPhotos = nil

	related, err := o.OrganizationPhotos(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Organization = o
	}

	o.R.OrganizationPhotos = related
	return nil
}

// LoadOrganizationPhotos loads the organization's OrganizationPhotos into the .R struct
func (os OrganizationSlice) LoadOrganizationPhotos(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizationPhotos, err := os.OrganizationPhotos(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.OrganizationPhotos = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range organizationPhotos {

			if !rel.OrganizationID.IsValue() {
				continue
			}
			if !(rel.OrganizationID.IsValue() && o.ID == rel.OrganizationID.MustGet()) {
				continue
			}

			rel.R.Organization = o

			o.R.OrganizationPhotos = append(o.R.OrganizationPhotos, rel)
		}
	}

	return nil
}

// LoadOrganizationSocials loads the organization's OrganizationSocials into the .R struct
func (o *Organization) LoadOrganizationSocials(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OrganizationSocials = nil

	related, err := o.OrganizationSocials(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Organization = o
	}

	o.R.OrganizationSocials = related
	return nil
}

// LoadOrganizationSocials loads the organization's OrganizationSocials into the .R struct
func (os OrganizationSlice) LoadOrganizationSocials(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizationSocials, err := os.OrganizationSocials(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.OrganizationSocials = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range organizationSocials {

			if !(o.ID == rel.OrganizationID) {
				continue
			}

			rel.R.Organization = o

			o.R.OrganizationSocials = append(o.R.OrganizationSocials, rel)
		}
	}

	return nil
}

// LoadOrganizationWorkHour loads the organization's OrganizationWorkHour into the .R struct
func (o *Organization) LoadOrganizationWorkHour(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OrganizationWorkHour = nil

	related, err := o.OrganizationWorkHour(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Organization = o

	o.R.OrganizationWorkHour = related
	return nil
}

// LoadOrganizationWorkHour loads the organization's OrganizationWorkHour into the .R struct
func (os OrganizationSlice) LoadOrganizationWorkHour(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizationWorkHours, err := os.OrganizationWorkHour(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range organizationWorkHours {

			if !rel.OrganizationID.IsValue() {
				continue
			}
			if !(rel.OrganizationID.IsValue() && o.ID == rel.OrganizationID.MustGet()) {
				continue
			}

			rel.R.Organization = o

			o.R.OrganizationWorkHour = rel
			break
		}
	}

	return nil
}

type organizationJoins[Q dialect.Joinable] struct {
	typ                  string
	Adoptions            modAs[Q, adoptionColumns]
	Animals              modAs[Q, animalColumns]
	OrganizationContact  modAs[Q, organizationContactColumns]
	OrganizationPhotos   modAs[Q, organizationPhotoColumns]
	OrganizationSocials  modAs[Q, organizationSocialColumns]
	OrganizationWorkHour modAs[Q, organizationWorkHourColumns]
}

func (j organizationJoins[Q]) aliasedAs(alias string) organizationJoins[Q] {
	return buildOrganizationJoins[Q](buildOrganizationColumns(alias), j.typ)
}

func buildOrganizationJoins[Q dialect.Joinable](cols organizationColumns, typ string) organizationJoins[Q] {
	return organizationJoins[Q]{
		typ: typ,
		Adoptions: modAs[Q, adoptionColumns]{
			c: Adoptions.Columns,
			f: func(to adoptionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Adoptions.Name().As(to.Alias())).On(
						to.OrganizationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Animals: modAs[Q, animalColumns]{
			c: Animals.Columns,
			f: func(to animalColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Animals.Name().As(to.Alias())).On(
						to.OrganizationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		OrganizationContact: modAs[Q, organizationContactColumns]{
			c: OrganizationContacts.Columns,
			f: func(to organizationContactColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, OrganizationContacts.Name().As(to.Alias())).On(
						to.OrganizationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		OrganizationPhotos: modAs[Q, organizationPhotoColumns]{
			c: OrganizationPhotos.Columns,
			f: func(to organizationPhotoColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, OrganizationPhotos.Name().As(to.Alias())).On(
						to.OrganizationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		OrganizationSocials: modAs[Q, organizationSocialColumns]{
			c: OrganizationSocials.Columns,
			f: func(to organizationSocialColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, OrganizationSocials.Name().As(to.Alias())).On(
						to.OrganizationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		OrganizationWorkHour: modAs[Q, organizationWorkHourColumns]{
			c: OrganizationWorkHours.Columns,
			f: func(to organizationWorkHourColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, OrganizationWorkHours.Name().As(to.Alias())).On(
						to.OrganizationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
